const test = require('node:test');
const assert = require('node:assert/strict');

process.env.AI_PROVIDER ||= 'openai';
process.env.AI_API_KEY ||= 'test-key';
process.env.AI_BASE_URL ||= 'https://example.test/v1';
process.env.AI_MODEL ||= 'test-model';

const dynamicScope = require('../src/services/autoSourceDynamicScope');
const expanded = require('../src/services/autoSourceExpandedDiscovery');
const routing = require('../src/services/autoSourceRoutingComposer');
const scoped = require('../src/services/autoSourceScopedDiscovery');
const simple = require('../src/services/autoSourceSimpleComposer');

const topic = 'Cloude menerapkan watermark';
const plan = {
  rawTopic: topic,
  canonicalTopic: topic,
  subjects: ['Cloude'],
  eventTerms: ['menerapkan watermark'],
  actionTerms: ['menerapkan'],
  contextTerms: ['watermark'],
  searchQueries: [topic],
  marketIntent: false,
  relation: 'event',
  planner: 'fallback'
};

function source(url, title, sentences) {
  return {
    url,
    finalUrl: url,
    title,
    text: sentences.join(' '),
    discovery: { publisher: new URL(url).hostname, score: 20 }
  };
}

const deepMindStory = source(
  'https://finance.yahoo.example/deepmind-watermark',
  'DeepMind partners with Google Cloud to watermark AI-generated images',
  [
    'In partnership with Google Cloud, Google DeepMind is launching a tool for watermarking and identifying AI-generated images.',
    'The tool embeds a digital watermark directly into image pixels.',
    'DeepMind says SynthID uses two AI models, one for watermarking and one for identifying.',
    'Another firm, Steg.AI, uses an AI model to apply watermarks that survive resizing and other edits.',
    'In recent U.S. Senate committee hearings, lawmakers emphasized transparency in generative AI.',
    'A related headline says Claude will also watermark generated text.'
  ]
);

const claudeStory = source(
  'https://siliconangle.example/claude-watermark',
  'Anthropic to start watermarking Claude-generated text, images',
  [
    'Anthropic has announced plans to embed an invisible watermark in text and images generated by Claude.',
    'The watermarking mechanism is designed to bring Claude into compliance with the European Union AI Act.',
    'Anthropic says text watermarking will be performed by Claude models released after August 2.',
    'According to the company, the watermark is invisible and persists if copied to other applications.',
    'The company did not specify how the text watermark works.',
    'However, a research paper released by Google DeepMind may provide clues.',
    'DeepMind watermarking supports text, images, videos and audio through SynthID.',
    'Another firm, Steg.AI, applies watermarks that survive resizing and other edits.',
    'A U.S. Senate committee hearing also discussed transparency in generative AI.',
    'Anthropic likewise plans to mark media files generated by Claude.',
    'OpenAI has also signed the voluntary Code of Practice.'
  ]
);

test('event source must name the requested subject in its headline or lead', () => {
  assert.equal(dynamicScope.eventLockSatisfied(plan, deepMindStory.title), true, 'the wrong headline still shares the watermark action');
  assert.equal(dynamicScope.sourceInScope(topic, deepMindStory, plan), false);
  assert.equal(expanded.fetchedContentRelevant(topic, deepMindStory, plan), false);
  assert.equal(scoped.softSourceScore(topic, deepMindStory, plan), -1, 'soft fallback must not re-admit the wrong story');

  assert.equal(dynamicScope.sourceInScope(topic, claudeStory, plan), true, 'the obvious Cloude/Claude typo remains accepted');
});

test('topic scoping removes comparison systems and article side-stories before AI Writer', () => {
  const prepared = routing.prepareSources(topic, [claudeStory], plan);
  assert.equal(prepared.length, 1);
  assert.ok(routing.factCount(topic, prepared[0], plan) >= 4);
  assert.match(prepared[0].text, /Claude|Anthropic/i);
  assert.match(prepared[0].text, /invisible and persists/i);
  assert.doesNotMatch(prepared[0].text, /Google DeepMind|SynthID|Steg\.AI|Senate|OpenAI/i);

  const packets = simple.buildSlidePackets(prepared, topic, 'Fakta singkat');
  assert.equal(packets.length, 4);
  assert.ok(packets.flatMap(packet => packet.evidence)
    .every(evidence => !/Google DeepMind|SynthID|Steg\.AI|Senate|OpenAI/i.test(evidence)));
});

test('scoped discovery keeps only the same Claude watermark story', async () => {
  const original = expanded.discover;
  expanded.discover = async () => ({
    topic,
    queries: [topic],
    providers: ['test'],
    publishers: ['finance.yahoo.example', 'siliconangle.example'],
    sources: [deepMindStory, claudeStory]
  });

  try {
    const result = await scoped.discover({ topic, topicPlan: plan });
    assert.equal(result.sources.length, 1);
    assert.equal(result.sources[0].finalUrl, claudeStory.finalUrl);
    assert.equal(result.scopeMode, 'strict');
  } finally {
    expanded.discover = original;
  }
});
