const test = require('node:test');
const assert = require('node:assert/strict');

process.env.AI_PROVIDER ||= 'openai';
process.env.AI_API_KEY ||= 'test-key';
process.env.AI_BASE_URL ||= 'https://example.test/v1';
process.env.AI_MODEL ||= 'test-model';

const simple = require('../src/services/autoSourceSimpleComposer');
const guard = require('../src/services/autoSourceIndonesianOutput');

test('English visible copy is detected while Indonesian technical copy is allowed', () => {
  assert.equal(guard.likelyEnglishVisible('Anthropic plans to embed invisible watermarks into text generated by supported Claude models'), true);
  assert.equal(guard.likelyEnglishVisible('For text, supported Claude models will weave an imperceptible watermark directly into responses'), true);
  assert.equal(guard.likelyEnglishVisible('Anthropic akan menambahkan watermark pada teks dari model Claude yang didukung'), false);
  assert.equal(guard.likelyEnglishVisible('Claude API tersedia untuk pengguna Enterprise'), false);
});

test('language-only repair keeps factual evidence metadata and produces Indonesian visible copy', async () => {
  const topic = 'Perusahaan AI akan menambahkan tanda air';
  const sources = [{
    title: 'AI company plans invisible watermarking for generated text',
    url: 'https://example.test/watermark',
    text: [
      'The AI company plans to embed invisible watermarks into text generated by supported models.',
      'Supported models will weave an imperceptible watermark directly into their responses.',
      'The watermark is designed to remain in generated text without changing the visible wording.',
      'The company is also working to add marking support to older models during a transition period.',
      'Users may continue to use supported models while the watermarking system is introduced.',
      'The company says the marking system is intended to identify AI-generated text.',
      'The rollout applies to supported text models first.',
      'Additional model support is planned later.'
    ].join(' ')
  }];

  const packets = simple.buildSlidePackets(sources, topic, 'Fakta singkat');
  assert.equal(packets.length, 4);
  const slides = packets.map((packet, index) => {
    const body = packet.evidence[0];
    return {
      section: packet.section,
      title: index === 0 ? 'Latest News AI company plans invisible watermarking' : `Supported models watermark update ${index + 1}`,
      body,
      points: [],
      claims: [{ field: `slide:${index}:body`, text: body, sourceId: packet.primarySourceId, evidence: body }]
    };
  });
  const result = { slides, hook: slides[0].title, body: slides[1].body, caption: slides[1].body, cta: slides[3].title };

  const translations = [
    'Perusahaan AI Siapkan Tanda Air Tak Terlihat',
    'Sistem Membantu Identifikasi Teks AI',
    'Pengguna Tetap Bisa Memakai Model',
    'Teks Tetap Terlihat Normal'
  ];
  const bodies = [
    'Perusahaan AI berencana menambahkan tanda air tak terlihat pada teks dari model yang didukung.',
    'Sistem penandaan ditujukan untuk mengidentifikasi teks yang dihasilkan oleh AI.',
    'Pengguna tetap dapat memakai model yang didukung selama peluncuran sistem watermark.',
    'Tanda air dirancang tetap berada dalam teks tanpa mengubah kata yang terlihat.'
  ];

  let calls = 0;
  const client = {
    chat: {
      completions: {
        create: async () => {
          calls += 1;
          return {
            choices: [{
              message: {
                content: {
                  slides: translations.map((title, index) => ({ title, body: bodies[index], points: [] }))
                }
              }
            }]
          };
        }
      }
    }
  };

  const repaired = await guard.ensureIndonesian({
    result,
    topic,
    format: 'Fakta singkat',
    sources,
    client
  });

  assert.equal(calls, 1);
  assert.equal(guard.needsIndonesianRepair(repaired), false);
  assert.ok(repaired.slides.every(slide => !guard.likelyEnglishVisible(slide.title) && !guard.likelyEnglishVisible(slide.body)));
  repaired.slides.forEach((slide, index) => {
    assert.equal(slide.claims[0].sourceId, packets[index].primarySourceId);
    assert.equal(slide.claims[0].evidence, packets[index].evidence[0]);
    assert.equal(slide.claims[0].text, slide.body);
  });
  assert.equal(repaired.hook, repaired.slides[0].title);
  assert.equal(repaired.cta, repaired.slides[3].title);
});

test('already Indonesian visible copy does not trigger a language repair call', async () => {
  const result = {
    slides: [
      { title: 'Fitur Baru Claude', body: 'Anthropic akan menambahkan tanda air pada teks Claude.', points: [] },
      { title: 'Tanda Air Tak Terlihat', body: 'Tanda air disisipkan langsung ke jawaban model yang didukung.', points: [] },
      { title: 'Teks Tetap Natural', body: 'Penandaan tidak mengubah kata yang terlihat oleh pengguna.', points: [] },
      { title: 'Model Lama Menyusul', body: 'Dukungan untuk model lama akan ditambahkan selama masa transisi.', points: [] }
    ]
  };
  let calls = 0;
  const client = { chat: { completions: { create: async () => { calls += 1; throw new Error('tidak boleh dipanggil'); } } } };
  const output = await guard.ensureIndonesian({ result, topic: 'Topik baru', sources: [], client });
  assert.equal(calls, 0);
  assert.equal(output, result);
});
