const test = require('node:test');
const assert = require('node:assert/strict');

process.env.AI_PROVIDER ||= 'openai';
process.env.AI_API_KEY ||= 'test-key';
process.env.AI_BASE_URL ||= 'https://example.test/v1';
process.env.AI_MODEL ||= 'test-model';

const simple = require('../src/services/autoSourceSimpleComposer');

const sources = [
  {
    title: 'Gemini mendapat kemampuan baru dari Google',
    url: 'https://one.test/gemini',
    text: [
      'Google memperbarui Gemini dengan kemampuan memahami dokumen yang diunggah pengguna.',
      'Gemini dapat merangkum isi dokumen panjang dan menjawab pertanyaan berdasarkan file tersebut.',
      'Fitur baru tersedia melalui aplikasi Gemini untuk pengguna yang memenuhi syarat.',
      'Google juga meningkatkan dukungan konteks percakapan pada aplikasi tersebut.',
      'Pembaruan ini diumumkan sebagai bagian dari pengembangan layanan Gemini.'
    ].join(' ')
  },
  {
    title: 'Gemini terhubung dengan layanan Google',
    url: 'https://two.test/gemini',
    text: [
      'Gemini dapat bekerja dengan beberapa layanan Google ketika pengguna memberikan izin.',
      'Integrasi membantu Gemini mengambil konteks dari layanan yang terhubung.',
      'Pengguna tetap dapat mengatur layanan mana yang boleh digunakan Gemini.',
      'Google menjelaskan integrasi tersebut sebagai bagian dari pengalaman asisten AI.',
      'Ketersediaan fitur dapat berbeda menurut akun dan wilayah.'
    ].join(' ')
  },
  {
    title: 'Gemini mendukung input multimodal',
    url: 'https://three.test/gemini',
    text: [
      'Gemini mendukung masukan teks dan gambar dalam satu percakapan.',
      'Pengguna dapat mengunggah gambar untuk dianalisis oleh Gemini.',
      'Model kemudian merespons berdasarkan konteks yang diberikan pengguna.',
      'Kemampuan multimodal menjadi salah satu fungsi utama aplikasi tersebut.',
      'Google terus memperluas dukungan jenis input pada Gemini.'
    ].join(' ')
  }
];

const claudeSources = [
  {
    title: 'Claude to start watermarking AI-generated content',
    url: 'https://one.test/claude-watermark',
    text: [
      'Anthropic has announced plans to embed invisible, machine-readable watermarks in text and images generated by Claude.',
      'New Claude models will support marking from launch, while support for existing models is still in progress.',
      'The marks will apply globally across Claude products and supported model deployments.',
      'Text watermarks may persist when users copy, paste, or lightly edit the output.'
    ].join(' ')
  },
  {
    title: 'Anthropic is watermarking Claude output',
    url: 'https://two.test/claude-watermark',
    text: [
      'Anthropic plans to start adding invisible watermarks to AI-generated Claude text and files.',
      'Claude text marking also applies when supported models are accessed through AWS, Google Cloud, or Microsoft Foundry.',
      'Anthropic says detection tools for users and third parties are coming in future documentation.',
      'FAQ: Can I see the watermark Claude adds to text?'
    ].join(' ')
  },
  {
    title: 'Anthropic to watermark Claude-generated text and images',
    url: 'https://three.test/claude-watermark',
    text: [
      'Anthropic PBC announced plans to insert an invisible watermark into text and images generated by Claude.',
      'Supported image files will use digitally signed C2PA provenance metadata.',
      'A missing detectable mark does not prove that content was created without generative AI.',
      'Watermarking happens at the model level rather than only in one Claude product.'
    ].join(' ')
  }
];

test('simple packets represent every selected source and never mix a source inside one slide', () => {
  const packets = simple.buildSlidePackets(sources, 'Aplikasi Gemini', 'Fakta singkat');
  assert.equal(packets.length, 4);
  const represented = new Set(packets.map(packet => packet.primarySourceId));
  assert.deepEqual(represented, new Set(['source-1', 'source-2', 'source-3']));
  packets.forEach(packet => {
    assert.ok(packet.evidence.length >= 1);
    const source = sources[Number(packet.primarySourceId.split('-')[1]) - 1];
    packet.evidence.forEach(evidence => assert.equal(simple.evidenceLiteralInSource(evidence, source), true));
  });
});

test('cross-source packets keep one announcement and choose distinct story details', () => {
  const topic = 'Cloude menerapkan watermark';
  const packets = simple.buildSlidePackets(claudeSources, topic, 'Fakta singkat');
  assert.equal(packets.length, 4);
  assert.equal(packets.filter(packet => /announc|plans? to (?:embed|start|insert)/i.test(packet.mainEvidence)).length, 1);
  assert.ok(packets.every(packet => !simple.questionOnlyEvidence(packet.mainEvidence)));
  for (let right = 1; right < packets.length; right += 1) {
    for (let left = 0; left < right; left += 1) {
      assert.equal(simple.sameFactContext(packets[left].mainEvidence, packets[right].mainEvidence, topic), false);
    }
  }
  assert.match(packets.map(packet => packet.mainEvidence).join(' '), /AWS|C2PA|detection|copy|model level|existing models/i);
  assert.equal(simple.sameFactContext(
    'Claude dari Anthropic akan mulai menandai konten yang dihasilkan AI.',
    'Anthropic mengumumkan rencana menyisipkan tanda air pada teks dan gambar yang dihasilkan Claude.',
    topic
  ), true, 'paraphrase lintas bahasa untuk pengumuman yang sama tetap terdeteksi sebagai duplikat');
});

test('FAQ evidence and dangling visible copy are rejected before rendering', () => {
  assert.equal(simple.questionOnlyEvidence('FAQ: Can I see the watermark Claude adds to text?'), true);
  assert.equal(simple.endsWithDanglingFragment('Tanda air yang terdeteksi hanya menunjukkan bahwa'), true);

  const packet = simple.buildSlidePackets(claudeSources, 'Cloude menerapkan watermark', 'Fakta singkat')[0];
  const normalized = simple.normalizeCandidate({ slides: [{
    title: 'Cara kerja watermark Claude',
    body: 'Watermark Claude tidak terlihat oleh pembaca.',
    points: ['Tanda air yang terdeteksi hanya menunjukkan bahwa', 'FAQ: Apakah watermark terlihat?'],
    claims: []
  }] }, [packet]);
  assert.deepEqual(normalized.slides[0].points, []);
});

test('caption combines two distinct supported slide facts instead of copying one slide', () => {
  const slides = [
    { body: 'Claude akan menambahkan watermark tak terlihat pada konten AI.' },
    { body: 'Penandaan berlaku pada model yang didukung di berbagai layanan.' },
    { body: 'Anthropic juga akan menambahkan watermark pada konten Claude.' },
    { body: 'Alat deteksi akan dijelaskan dalam dokumentasi mendatang.' }
  ];
  const caption = simple.buildCaption(slides, '', 'Cloude menerapkan watermark');
  assert.match(caption, /Claude akan menambahkan watermark/i);
  assert.match(caption, /berbagai layanan/i);
  assert.notEqual(caption, slides[0].body);
  assert.notEqual(caption, slides[1].body);
});

test('zero bullets are valid when body has a grounded factual claim', () => {
  const packets = simple.buildSlidePackets(sources, 'Aplikasi Gemini', 'Fakta singkat');
  const slides = packets.map((packet, index) => {
    const body = packet.evidence[0];
    return {
      section: packet.section,
      title: `Fakta Gemini ${index + 1}`,
      body,
      points: [],
      claims: [{
        field: `slide:${index}:body`,
        text: body,
        sourceId: packet.primarySourceId,
        evidence: packet.evidence[0]
      }]
    };
  });
  assert.deepEqual(simple.factualErrors({ slides }, packets, sources), []);
});

test('wrong source and unsupported numeric claim remain blockers', () => {
  const packets = simple.buildSlidePackets(sources, 'Aplikasi Gemini', 'Fakta singkat');
  const slides = packets.map((packet, index) => {
    const body = index === 0 ? 'Gemini digunakan oleh 99% pengguna.' : packet.evidence[0];
    return {
      title: `Fakta Gemini ${index + 1}`,
      body,
      points: [],
      claims: [{
        field: `slide:${index}:body`,
        text: body,
        sourceId: index === 1 ? 'source-1' : packet.primarySourceId,
        evidence: packet.evidence[0]
      }]
    };
  });
  const errors = simple.factualErrors({ slides }, packets, sources);
  assert.ok(errors.some(error => /slide:0:body: angka\/persentase tidak didukung/i.test(error)));
  assert.ok(errors.some(error => /slide:1:body: sourceId tidak sesuai/i.test(error)));
});

test('comma and dot percentage notation are treated as the same factual number', () => {
  assert.equal(simple.numbersSupported('Penetrasi mencapai 5.89%', 'Penetrasi mencapai 5,89 persen.'), true);
  assert.equal(simple.numbersSupported('Penetrasi mencapai 5.89%', 'Penetrasi mencapai 6,89 persen.'), false);
});

test('invalid bullet can be removed without destroying the body or whole carousel', () => {
  const packets = simple.buildSlidePackets(sources, 'Aplikasi Gemini', 'Fakta singkat');
  const slides = packets.map((packet, index) => {
    const body = packet.evidence[0];
    const point = index === 0 ? 'Angka palsu 88% pengguna' : '';
    return {
      section: packet.section,
      title: `Fakta Gemini ${index + 1}`,
      body,
      points: point ? [point] : [],
      claims: [
        { field: `slide:${index}:body`, text: body, sourceId: packet.primarySourceId, evidence: packet.evidence[0] },
        ...(point ? [{ field: `slide:${index}:point:0`, text: point, sourceId: packet.primarySourceId, evidence: packet.evidence[0] }] : [])
      ]
    };
  });
  const errors = simple.factualErrors({ slides }, packets, sources);
  assert.ok(errors.some(error => /^slide:0:point:0:/.test(error)));
  const cleaned = simple.dropInvalidPoints({ slides }, errors, packets);
  assert.equal(cleaned.slides[0].points.length, 0);
  assert.equal(cleaned.slides[0].body, slides[0].body);
});

test('production simple flow uses only writer plus fact-checker and returns grounded content', async () => {
  const packets = simple.buildSlidePackets(sources, 'Aplikasi Gemini', 'Fakta singkat');
  const slides = packets.map((packet, index) => {
    const body = packet.evidence[0];
    return {
      title: `Fakta Gemini ${index + 1}`,
      body,
      points: [],
      claims: [{ field: `slide:${index}:body`, text: body, sourceId: packet.primarySourceId, evidence: body }]
    };
  });
  let calls = 0;
  const client = {
    chat: {
      completions: {
        create: async () => {
          calls += 1;
          return { choices: [{ message: { content: { slides } } }] };
        }
      }
    }
  };

  const result = await simple.compose({
    options: { requestedTopic: 'Aplikasi Gemini', contentFormat: 'Fakta singkat' },
    sources,
    discovery: { searchedAt: '2026-08-13T00:00:00.000Z', queries: ['Aplikasi Gemini terbaru'], providers: ['test'] },
    client
  });

  assert.equal(calls, 2, 'writer + fact-checker only');
  assert.equal(result.verificationStatus, 'source_based');
  assert.equal(result.sourceMode, 'auto');
  assert.equal(result.slides.length, 4);
  assert.ok(result.slides.every(slide => slide.points.length === 0));
  assert.match(result.caption, new RegExp(result.slides[0].body.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.match(result.caption, new RegExp(result.slides[1].body.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.deepEqual(simple.factualErrors(result, packets, sources), []);
});
