const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const request = require('supertest');
const { createDatabase } = require('../src/db');
const { createApp } = require('../src/app');
const connector = require('../src/ai/connector');

const ok = body => new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });
const setup = (transport = async () => ok({ data: [{ url: 'data:image/png;base64,' }] })) => { const db = createDatabase(':memory:'); return { db, app: createApp({ db, aiTransport: transport }) }; };
const save = (db, provider, values = {}) => connector.save(db, provider, { apiKey: 'saved-secret', enabled: true, isDefault: true, retry: 0, ...values });
const generate = (app, body = {}) => request(app).post('/api/content-studio/generate').send({ prompt: 'campaign', mediaType: 'image', ...body });
const wait = async (app, id) => { for (let n = 0; n < 50; n += 1) { const row = (await request(app).get(`/api/content-studio/jobs/${id}`)).body; if (['Completed', 'Failed'].includes(row.status)) return row; await new Promise(r => setTimeout(r, 10)); } throw new Error('job remained non-terminal'); };

test('provider IDs are canonical: legacy rejected and correct ID accepted', async () => { const { db, app } = setup(); save(db, 'openai-images'); await generate(app, { provider: 'openai' }).expect(422); const accepted = await generate(app, { provider: 'openai-images' }).expect(202); assert.ok(accepted.body.ids[0]); db.close(); });

test('disabled provider is rejected before INSERT', async () => { const { db, app } = setup(); connector.save(db, 'openai-images', { apiKey: 'x', enabled: false }); await generate(app, { provider: 'openai-images' }).expect(409); assert.equal(db.prepare('SELECT count(*) n FROM ai_generations').get().n, 0); db.close(); });

test('missing API key is rejected before INSERT', async () => { const { db, app } = setup(); connector.save(db, 'openai-images', { enabled: true }); await generate(app, { provider: 'openai-images' }).expect(422); assert.equal(db.prepare('SELECT count(*) n FROM ai_generations').get().n, 0); db.close(); });

test('placeholder base URLs, Google Flow default endpoint, and Omni placeholder are rejected', async () => { for (const [provider, baseUrl, message] of [['openai-images','https://api.example.com','Base URL'],['google-flow','https://flow.googleapis.com','Google Flow'],['omni','https://api.example.com','Omni']]) { const { db, app } = setup(); save(db, provider, { baseUrl }); const result = await generate(app, { provider }).expect(409); assert.match(result.body.error, new RegExp(message)); assert.equal(db.prepare('SELECT count(*) n FROM ai_generations').get().n, 0); db.close(); } });

test('one and multiple unresolved prompt variables return 422 and create no rows', async () => { const { db, app } = setup(); save(db, 'openai-images'); let result = await generate(app, { prompt: '{{hook}}' }).expect(422); assert.deepEqual(result.body.unresolvedVariables, ['hook']); result = await generate(app, { prompt: '{{hook}} {{style}} {{brand}} {{product}} {{hook}}' }).expect(422); assert.deepEqual(result.body.unresolvedVariables, ['hook','style','brand','product']); assert.equal(db.prepare('SELECT count(*) n FROM ai_generations').get().n, 0); db.close(); });

for (const [name, thrown, type] of [['adapter', Object.assign(new Error('adapter broke'), { status: 500 }), 'Unknown Error'], ['authentication', Object.assign(new Error('bad credential'), { status: 401 }), 'Authentication Error'], ['timeout', Object.assign(new Error('timed out'), { code: 'ETIMEDOUT' }), 'Timeout']]) test(`${name} error persists Failed and never leaves Queued`, async () => { const { db, app } = setup(async () => { throw thrown; }); save(db, 'openai-images'); const queued = await generate(app).expect(202); const row = await wait(app, queued.body.ids[0]); assert.equal(row.status, 'Failed'); assert.equal(row.error_type, type); assert.match(row.error_message, new RegExp(thrown.message)); db.close(); });

test('startup recovery marks all in-flight lifecycle states Interrupted', () => { const db = createDatabase(':memory:'); for (const status of ['Queued','Preparing','Uploading','Generating','Waiting','Receiving','Downloading','Rendering','Retrying']) db.prepare('INSERT INTO ai_generations(id,provider,prompt,status) VALUES(?,?,?,?)').run(status, 'openai-images', 'x', status); createApp({ db }); const rows = db.prepare('SELECT * FROM ai_generations').all(); assert.ok(rows.every(row => row.status === 'Failed' && row.error_type === 'Interrupted' && row.error_message === 'Generation terhenti karena server direstart')); db.close(); });

test('valid mocked provider follows persisted lifecycle and completes', async () => { const seen = []; const { db, app } = setup(async () => { seen.push(db.prepare('SELECT status FROM ai_generations').get().status); return ok({ data: [] }); }); save(db, 'openai-images'); const queued = await generate(app).expect(202); assert.equal(queued.body.status, 'Queued'); const row = await wait(app, queued.body.ids[0]); assert.equal(row.status, 'Completed'); assert.ok(seen.includes('Generating')); db.close(); });

test('retry creates a new job with retryOf metadata and keeps old job', async () => { const { db, app } = setup(); save(db, 'openai-images'); const first = await generate(app).expect(202); await wait(app, first.body.ids[0]); const retried = await request(app).post(`/api/content-studio/jobs/${first.body.ids[0]}/retry`).expect(202); assert.notEqual(retried.body.id, first.body.ids[0]); const row = await wait(app, retried.body.id); assert.equal(row.metadata.retryOf, first.body.ids[0]); assert.ok(db.prepare('SELECT 1 FROM ai_generations WHERE id=?').get(first.body.ids[0])); db.close(); });

test('saved API key remains encrypted and listing a sole provider does not silently make it default', async () => { const { db, app } = setup(); save(db, 'openai-images', { isDefault: false }); const before = db.prepare("SELECT api_key_encrypted FROM ai_provider_settings WHERE provider='openai-images'").get().api_key_encrypted; const providers = await request(app).get('/api/content-studio/providers').expect(200); assert.equal(providers.body.length, 1); assert.deepEqual(providers.body[0].defaultCapabilities, []); assert.equal(db.prepare("SELECT COUNT(*) count FROM ai_provider_defaults").get().count, 0); const generated = await generate(app, { provider: 'openai-images' }).expect(202); assert.equal(generated.body.provider, 'openai-images'); assert.equal(db.prepare("SELECT api_key_encrypted FROM ai_provider_settings WHERE provider='openai-images'").get().api_key_encrypted, before); db.close(); });

test('single compatible provider UI hides selector and labels active provider', () => { const html = fs.readFileSync('public/index.html','utf8'); const js = fs.readFileSync('public/content-studio.js','utf8'); assert.match(html, /studio-active-provider/); assert.match(js, /visible\.length===1/); assert.match(js, /Provider aktif:/); });

test('a default for another capability is never used as video fallback', async () => { const { db, app } = setup(); save(db, 'openai-images'); save(db, 'google-veo', { isDefault: false }); const before = db.prepare('SELECT count(*) n FROM ai_generations').get().n; const result = await generate(app, { provider: undefined, mediaType: 'video' }).expect(409); assert.match(result.body.error, /Provider belum diaktifkan/); assert.equal(db.prepare('SELECT count(*) n FROM ai_generations').get().n, before); db.close(); });
