const test = require('node:test');
const assert = require('node:assert/strict');

const {
  extractFactBank,
  requiresEvidence,
  validateVerifiedContent,
  evidenceCandidates
} = require('../src/services/sourceFilter');

const contentService = {
  validateContent(content) {
    if (!Array.isArray(content.slides) || content.slides.length !== 4) return ['struktur berubah'];
    return [];
  }
};

const sources = [
  {
    url: 'https://example.test/article-a',
    text: [
      'Subscribe to our newsletter for more updates.',
      'The researcher says AI agents can work across longer tasks when goals and limits are clear.',
      'This voice experience is generated by AI.',
      'Teams still need to review important outputs before acting on them.'
    ].join(' ')
  },
  {
    url: 'https://example.test/article-b',
    text: [
      'Follow us for more stories.',
      'Independent testing found that human oversight remains important when agents handle multi-step work.',
      'Contact us for advertising information.'
    ].join(' ')
  }
];

function baseContent() {
  return {
    focus: { masalah: 'Tugas panjang', penyebab: 'Banyak tahap', solusi: 'Gunakan agen dengan batas jelas', hasil: 'Alur lebih terarah' },
    topic: 'Agen AI untuk proyek',
    hook: 'Agen AI mulai menangani tugas yang lebih panjang',
    body: 'Agen AI dapat bekerja lintas beberapa tahap.',
    caption: 'Cara melihat peran agen AI dalam pekerjaan panjang.',
    hashtags: [],
    cta: 'Tetap cek hasil pentingnya',
    trendKeywordsUsed: [],
    content_angle: 'agen untuk tugas panjang',
    primary_tool: 'tanpa tool',
    hook_pattern: 'pernyataan langsung',
    slides: [
      { section: 'PEMBUKA', title: 'Bukan Lagi Sekadar Satu Prompt', body: 'Agen AI mulai dipakai untuk rangkaian tugas yang lebih panjang.', points: [] },
      { section: 'PENJELASAN', title: 'Tujuan dan Batas Tetap Penting', body: 'Agen dapat bekerja lintas tahap ketika tujuan dan batasnya jelas.', points: [] },
      { section: 'PENJELASAN', title: 'Pengawasan Manusia Masih Dibutuhkan', body: 'Tim tetap perlu meninjau keluaran penting sebelum bertindak.', points: [] },
      { section: 'PENUTUP', title: 'Nilai Hasilnya, Bukan Hanya Otomasinya', body: 'Mulai dari alur yang mudah diperiksa.', points: [] }
    ]
  };
}

test('fact bank membuang boilerplate dan mempertahankan sourceId asal', () => {
  const bank = extractFactBank(sources, 'agen AI untuk proyek');
  assert.ok(bank.length >= 2);
  assert.ok(bank.some(item => item.sourceId === 'source-1'));
  assert.ok(bank.some(item => item.sourceId === 'source-2'));
  assert.ok(bank.every(item => !/newsletter|voice experience|follow us|contact us/i.test(item.evidence)));
});

test('evidenceCandidates tidak menganggap metadata website sebagai fakta', () => {
  const candidates = evidenceCandidates('Subscribe to our newsletter. Fakta produk tersedia untuk pengguna. This voice experience is generated by AI.');
  assert.deepEqual(candidates, ['Fakta produk tersedia untuk pengguna.']);
});

test('copy non-faktual tidak dipaksa punya evidence tetapi klaim faktual iya', () => {
  assert.equal(requiresEvidence('Cek konteks lengkap sebelum memutuskan', 'PENUTUP', 'body'), false);
  assert.equal(requiresEvidence('Sistem ini dapat menangani beberapa tahap kerja', 'PENJELASAN', 'body'), true);
  assert.equal(requiresEvidence('Dipakai oleh 80% tim', 'PENJELASAN', 'body'), true);
});

test('validator menjaga struktur normal dan menolak judul mentah, filler, slide kosong, serta claim tanpa evidence', () => {
  const base = baseContent();
  const candidate = {
    slides: base.slides.map((slide, index) => ({
      ...slide,
      claims: index === 1 ? [{
        field: 'slide:1:title',
        text: slide.title,
        sourceId: 'source-1',
        evidence: 'The researcher says AI agents can work across longer tasks when goals and limits are clear.'
      }, {
        field: 'slide:1:body',
        text: slide.body,
        sourceId: 'source-1',
        evidence: 'The researcher says AI agents can work across longer tasks when goals and limits are clear.'
      }] : index === 2 ? [{
        field: 'slide:2:title',
        text: slide.title,
        sourceId: 'source-2',
        evidence: 'Independent testing found that human oversight remains important when agents handle multi-step work.'
      }, {
        field: 'slide:2:body',
        text: slide.body,
        sourceId: 'source-1',
        evidence: 'Teams still need to review important outputs before acting on them.'
      }] : []
    }))
  };
  const checked = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: 'Agen AI untuk proyek',
    sources
  });
  assert.equal(checked.errors.length, 0);
  assert.equal(checked.content.slides.length, base.slides.length);

  const bad = JSON.parse(JSON.stringify(candidate));
  bad.slides[0].title = 'Agen AI untuk proyek';
  bad.slides[3].title = 'Lanjut baca tentang Agen AI untuk proyek';
  bad.slides[3].body = '';
  bad.slides[1].claims = [];
  const badChecked = validateVerifiedContent(base, bad, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: 'Agen AI untuk proyek',
    sources
  });
  assert.ok(badChecked.errors.some(error => /requestedTopic dipakai mentah/i.test(error)));
  assert.ok(badChecked.errors.some(error => /Lanjut baca tentang/i.test(error)));
  assert.ok(badChecked.errors.some(error => /tidak memiliki isi bermakna/i.test(error)));
  assert.ok(badChecked.errors.some(error => /tidak memiliki evidence/i.test(error)));
});

test('claim tidak boleh meminjam evidence dari sourceId lain', () => {
  const base = baseContent();
  const candidate = {
    slides: base.slides.map((slide, index) => ({
      ...slide,
      claims: index === 1 ? [{
        field: 'slide:1:body',
        text: slide.body,
        sourceId: 'source-2',
        evidence: 'The researcher says AI agents can work across longer tasks when goals and limits are clear.'
      }] : index === 2 ? [{
        field: 'slide:2:body',
        text: slide.body,
        sourceId: 'source-1',
        evidence: 'Teams still need to review important outputs before acting on them.'
      }] : []
    }))
  };
  const checked = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: 'Agen AI untuk proyek',
    sources
  });
  assert.ok(checked.errors.some(error => /Evidence tidak ditemukan pada source-2/i.test(error)));
});
