const test = require('node:test');
const assert = require('node:assert/strict');

const {
  extractFactBank,
  requiresEvidence,
  validateVerifiedContent,
  evidenceCandidates,
  validateManualTopicIdentity,
  dropUnsupportedPointClaims
} = require('../src/services/sourceFilter');

const contentService = {
  validateContent(content) {
    if (!Array.isArray(content.slides) || content.slides.length !== 4) return ['struktur berubah'];
    return [];
  }
};

const sources = [
  {
    url: 'https://example.test/article-a',
    text: [
      'Subscribe to our newsletter for more updates.',
      'The researcher says AI agents can work across longer tasks when goals and limits are clear.',
      'This voice experience is generated by AI.',
      'Teams still need to review important outputs before acting on them.'
    ].join(' ')
  },
  {
    url: 'https://example.test/article-b',
    text: [
      'Follow us for more stories.',
      'Independent testing found that human oversight remains important when agents handle multi-step work.',
      'Contact us for advertising information.'
    ].join(' ')
  }
];

function baseContent() {
  return {
    focus: { masalah: 'Tugas panjang', penyebab: 'Banyak tahap', solusi: 'Gunakan agen dengan batas jelas', hasil: 'Alur lebih terarah' },
    topic: 'Agen AI untuk proyek',
    hook: 'Agen AI mulai menangani tugas yang lebih panjang',
    body: 'Agen AI dapat bekerja lintas beberapa tahap.',
    caption: 'Cara melihat peran agen AI dalam pekerjaan panjang.',
    hashtags: [],
    cta: 'Tetap cek hasil pentingnya',
    trendKeywordsUsed: [],
    content_angle: 'agen untuk tugas panjang',
    primary_tool: 'tanpa tool',
    hook_pattern: 'pernyataan langsung',
    slides: [
      { section: 'PEMBUKA', title: 'Bukan Lagi Sekadar Satu Prompt', body: 'Agen AI mulai dipakai untuk rangkaian tugas yang lebih panjang.', points: [] },
      { section: 'PENJELASAN', title: 'Tujuan dan Batas Tetap Penting', body: 'Agen dapat bekerja lintas tahap ketika tujuan dan batasnya jelas.', points: [] },
      { section: 'PENJELASAN', title: 'Pengawasan Manusia Masih Dibutuhkan', body: 'Tim tetap perlu meninjau keluaran penting sebelum bertindak.', points: [] },
      { section: 'PENUTUP', title: 'Nilai Hasilnya, Bukan Hanya Otomasinya', body: 'Mulai dari alur yang mudah diperiksa.', points: [] }
    ]
  };
}

test('fact bank membuang boilerplate dan mempertahankan sourceId asal', () => {
  const bank = extractFactBank(sources, 'agen AI untuk proyek');
  assert.ok(bank.length >= 2);
  assert.ok(bank.some(item => item.sourceId === 'source-1'));
  assert.ok(bank.some(item => item.sourceId === 'source-2'));
  assert.ok(bank.every(item => !/newsletter|voice experience|follow us|contact us/i.test(item.evidence)));
});

test('evidenceCandidates tidak menganggap metadata website sebagai fakta', () => {
  const candidates = evidenceCandidates('Subscribe to our newsletter. Fakta produk tersedia untuk pengguna. This voice experience is generated by AI.');
  assert.deepEqual(candidates, ['Fakta produk tersedia untuk pengguna.']);
});

test('copy non-faktual tidak dipaksa punya evidence tetapi klaim faktual iya', () => {
  assert.equal(requiresEvidence('Cek konteks lengkap sebelum memutuskan', 'PENUTUP', 'body'), false);
  assert.equal(requiresEvidence('Sistem ini dapat menangani beberapa tahap kerja', 'PENJELASAN', 'body'), true);
  assert.equal(requiresEvidence('Dipakai oleh 80% tim', 'PENJELASAN', 'body'), true);
});

test('Fakta singkat menolak isi tengah question-only tetapi tetap membolehkan title dan pembuka berupa pertanyaan', () => {
  const evidence = 'Teams still need to review important outputs before acting on them.';
  const base = {
    ...baseContent(),
    slides: [
      { section: 'PEMBUKA', title: 'Apa itu pengawasan AI?', body: 'Kenali konteksnya sebelum bertindak.', points: [] },
      { section: 'FAKTA UTAMA', title: 'Mengapa tinjauan penting?', body: 'Bagaimana tim meninjau keluaran penting?', points: [] },
      { section: 'KONTEKS', title: 'Apa konteksnya?', body: 'Tim tetap perlu meninjau keluaran penting sebelum bertindak.', points: [] },
      { section: 'KESIMPULAN', title: 'Ringkasannya', body: 'Baca sesuai konteks sumber.', points: [] }
    ]
  };
  const candidate = {
    slides: base.slides.map((slide, index) => ({
      ...slide,
      claims: index === 2 ? [{ field: 'slide:2:body', text: slide.body, sourceId: 'source-1', evidence }] : []
    }))
  };

  const rejected = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: '',
    sources
  });
  assert.ok(rejected.errors.includes('slide:1:body: format Fakta singkat membutuhkan fakta terverifikasi dari sumber, bukan pertanyaan saja.'));
  assert.ok(!rejected.errors.some(error => /^slide:0:/i.test(error)), 'PEMBUKA question-only tetap boleh');

  candidate.slides[1].body = 'Tim tetap perlu meninjau keluaran penting sebelum bertindak.';
  candidate.slides[1].claims = [{ field: 'slide:1:body', text: candidate.slides[1].body, sourceId: 'source-1', evidence }];
  const accepted = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: '',
    sources
  });
  assert.deepEqual(accepted.errors, []);
  assert.equal(accepted.content.slides[1].title, 'Mengapa tinjauan penting?');

  candidate.slides[3].body = 'Apa manfaat utama pengawasan AI?';
  const questionConclusion = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: '',
    sources
  });
  assert.ok(questionConclusion.errors.includes('slide:3:body: format Fakta singkat membutuhkan kesimpulan bermakna, bukan pertanyaan saja.'));
  assert.ok(!questionConclusion.errors.some(error => /^slide:0:/i.test(error)), 'PEMBUKA question-only tetap boleh');

  candidate.slides[3].body = 'Ringkas fakta utama sebelum menerapkannya.';
  const neutralConclusion = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: '',
    sources
  });
  assert.deepEqual(neutralConclusion.errors, [], 'kesimpulan netral non-faktual tidak wajib claim');

  candidate.slides[3].body = 'Sistem dapat menggantikan semua keputusan manusia.';
  const factualConclusion = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: '',
    sources
  });
  assert.ok(factualConclusion.errors.includes('slide:3:body: klaim faktual tidak memiliki evidence.'));
});

test('validator menjaga struktur normal dan menolak judul mentah, filler, slide kosong, serta claim tanpa evidence', () => {
  const base = baseContent();
  const candidate = {
    slides: base.slides.map((slide, index) => ({
      ...slide,
      claims: index === 0 ? [{
        field: 'slide:0:body',
        text: slide.body,
        sourceId: 'source-1',
        evidence: 'The researcher says AI agents can work across longer tasks when goals and limits are clear.'
      }] : index === 1 ? [{
        field: 'slide:1:title',
        text: slide.title,
        sourceId: 'source-1',
        evidence: 'The researcher says AI agents can work across longer tasks when goals and limits are clear.'
      }, {
        field: 'slide:1:body',
        text: slide.body,
        sourceId: 'source-1',
        evidence: 'The researcher says AI agents can work across longer tasks when goals and limits are clear.'
      }] : index === 2 ? [{
        field: 'slide:2:title',
        text: slide.title,
        sourceId: 'source-2',
        evidence: 'Independent testing found that human oversight remains important when agents handle multi-step work.'
      }, {
        field: 'slide:2:body',
        text: slide.body,
        sourceId: 'source-1',
        evidence: 'Teams still need to review important outputs before acting on them.'
      }] : []
    }))
  };
  const checked = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: 'Agen AI untuk proyek',
    sources
  });
  assert.equal(checked.errors.length, 0);
  assert.equal(checked.content.slides.length, base.slides.length);

  const bad = JSON.parse(JSON.stringify(candidate));
  bad.slides[0].title = 'Agen AI untuk proyek';
  bad.slides[3].title = 'Lanjut baca tentang Agen AI untuk proyek';
  bad.slides[3].body = '';
  bad.slides[1].claims = [];
  const badChecked = validateVerifiedContent(base, bad, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: 'Agen AI untuk proyek',
    sources
  });
  assert.ok(badChecked.errors.some(error => /requestedTopic dipakai mentah/i.test(error)));
  assert.ok(badChecked.errors.some(error => /Lanjut baca tentang/i.test(error)));
  assert.ok(badChecked.errors.some(error => /tidak memiliki isi bermakna/i.test(error)));
  assert.ok(badChecked.errors.some(error => /tidak memiliki evidence/i.test(error)));
});

test('claim tidak boleh meminjam evidence dari sourceId lain', () => {
  const base = baseContent();
  const candidate = {
    slides: base.slides.map((slide, index) => ({
      ...slide,
      claims: index === 1 ? [{
        field: 'slide:1:body',
        text: slide.body,
        sourceId: 'source-2',
        evidence: 'The researcher says AI agents can work across longer tasks when goals and limits are clear.'
      }] : index === 2 ? [{
        field: 'slide:2:body',
        text: slide.body,
        sourceId: 'source-1',
        evidence: 'Teams still need to review important outputs before acting on them.'
      }] : []
    }))
  };
  const checked = validateVerifiedContent(base, candidate, {
    contentService,
    format: 'Fakta singkat',
    manualTopic: 'Agen AI untuk proyek',
    sources
  });
  assert.ok(checked.errors.some(error => /Evidence tidak ditemukan pada source-2/i.test(error)));
});

test('evidence paraphrase diperbaiki menjadi kutipan canonical dari source yang sama', () => {
  const canonical = 'Astra could reach a critical cybersecurity capability threshold.';
  const localSources = [{ text: canonical }];
  const slides = [
    { section: 'PEMBUKA', title: 'Konteks Astra', body: 'Baca sumbernya.', points: [] },
    {
      section: 'PENJELASAN',
      title: 'Tentang Astra',
      body: 'Astra dapat mencapai critical cybersecurity capability threshold.',
      points: [],
      claims: [{
        field: 'slide:1:body',
        text: 'Astra dapat mencapai critical cybersecurity capability threshold.',
        sourceId: 'source-1',
        evidence: 'Astra may hit the critical cybersecurity capability threshold.'
      }]
    },
    { section: 'KONTEKS', title: 'Tetap cermati', body: 'Periksa konteks sumber.', points: [] },
    { section: 'PENUTUP', title: 'Ringkasan', body: 'Simpan informasi ini.', points: [] }
  ];
  const checked = validateVerifiedContent({ ...baseContent(), slides }, { slides }, {
    contentService,
    format: '',
    manualTopic: '',
    sources: localSources
  });

  assert.deepEqual(checked.errors, []);
  assert.equal(checked.content.slides[1].claims[0].evidence, canonical);
});

test('claim dengan evidence invalid tidak memblokir recovery claim canonical', () => {
  const canonical = 'Astra could reach a critical cybersecurity capability threshold.';
  const localSources = [{ text: canonical }];
  const slides = [
    { section: 'PEMBUKA', title: 'Konteks Astra', body: 'Baca sumbernya.', points: [] },
    {
      section: 'PENJELASAN',
      title: 'Tentang Astra',
      body: 'Astra dapat mencapai critical cybersecurity capability threshold.',
      points: [],
      claims: [{
        field: 'slide:1:body',
        text: 'Klaim lain yang tidak didukung sumber',
        sourceId: 'source-1',
        evidence: 'Evidence rekaan provider yang tidak ada.'
      }]
    },
    { section: 'KONTEKS', title: 'Tetap cermati', body: 'Periksa konteks sumber.', points: [] },
    { section: 'PENUTUP', title: 'Ringkasan', body: 'Simpan informasi ini.', points: [] }
  ];
  const checked = validateVerifiedContent({ ...baseContent(), slides }, { slides }, {
    contentService,
    format: '',
    manualTopic: '',
    sources: localSources
  });

  assert.deepEqual(checked.errors, []);
  assert.deepEqual(checked.content.slides[1].claims, [{
    field: 'slide:1:body',
    text: slides[1].body,
    sourceId: 'source-1',
    evidence: canonical
  }]);
});

test('evidence invalid tanpa dukungan canonical tetap ditolak dengan field target', () => {
  const slides = baseContent().slides.map((slide, index) => ({
    ...slide,
    claims: index === 1 ? [{
      field: 'slide:1:body',
      text: slide.body,
      sourceId: 'source-1',
      evidence: 'Evidence rekaan provider yang tidak ada.'
    }] : []
  }));
  const checked = validateVerifiedContent(baseContent(), { slides }, {
    contentService,
    format: '',
    manualTopic: '',
    sources
  });

  assert.ok(checked.errors.includes('slide:1:body: Evidence tidak ditemukan pada source-1.'));
  assert.equal(checked.content.slides[1].claims.length, 0);
});

test('evidence exact yang sudah valid tidak diubah', () => {
  const exact = 'The researcher says AI agents can work across longer tasks when goals and limits are clear.';
  const candidate = {
    slides: baseContent().slides.map((slide, index) => ({
      ...slide,
      claims: index === 1 ? [{ field: 'slide:1:body', text: slide.body, sourceId: 'source-1', evidence: exact }] : []
    }))
  };
  const checked = validateVerifiedContent(baseContent(), candidate, {
    contentService,
    format: '',
    manualTopic: '',
    sources
  });

  assert.equal(checked.content.slides[1].claims[0].evidence, exact);
});


test('AI API dan GPT tidak diperlakukan sebagai identitas unik yang wajib muncul literal', () => {
  const genericSlides = [
    { title: 'Hambatan saat membuat video', body: 'Proses produksi bisa memiliki beberapa kendala.', points: [] },
    { title: 'Kenali sumber masalah', body: 'Periksa bagian proses yang paling sering menghambat.', points: [] }
  ];
  assert.deepEqual(validateManualTopicIdentity('Menghadapi masalah saat membuat video AI', genericSlides), []);
  const namedErrors = validateManualTopicIdentity('Google Maps rilis fitur AI', genericSlides);
  assert.ok(namedErrors.some(error => /google \/ maps/i.test(error)));
});

test('point yang gagal semantic support dibuang dengan aman dan claim point berikutnya dinomori ulang', () => {
  const content = {
    slides: [{
      section: 'MASALAH',
      title: 'Hambatan produksi video',
      body: 'Ada beberapa sumber hambatan dalam proses produksi.',
      points: ['Waktu render terlalu lama', 'Berpindah tool membuang waktu'],
      claims: [
        { field: 'slide:0:point:0', text: 'Waktu render terlalu lama', sourceId: 'source-1', evidence: 'Switching between tools can waste a significant amount of time during production.' },
        { field: 'slide:0:point:1', text: 'Berpindah tool membuang waktu', sourceId: 'source-1', evidence: 'Switching between tools can waste a significant amount of time during production.' }
      ]
    }]
  };
  const reduced = dropUnsupportedPointClaims(content, [
    'SEMANTIC_SUPPORT: slide:0:point:0 tidak didukung evidence: evidence mentions time loss due to tool switching, not specifically long render time'
  ]);
  assert.ok(reduced);
  assert.deepEqual(reduced.slides[0].points, ['Berpindah tool membuang waktu']);
  assert.equal(reduced.slides[0].claims.length, 1);
  assert.equal(reduced.slides[0].claims[0].field, 'slide:0:point:0');
  assert.equal(content.slides[0].points.length, 2);
});
