const OpenAI = require('openai');
const config = require('../config');
const sourceFilter = require('./sourceFilter');
const manualSourceDedupe = require('./manualSourceDedupe');

const MAX_ROLE_AUDIT_ATTEMPTS = 2;
const MAX_ROLE_REPAIR_ATTEMPTS = 4;
const ACTION = /\b(?:cek|periksa|memeriksa|buka|membuka|pilih|memilih|aktifkan|mengaktifkan|nonaktifkan|menonaktifkan|hapus|menghapus|keluarkan|mengeluarkan|putuskan|memutuskan|cabut|mencabut|ubah|mengubah|ganti|mengganti|reset|atur|mengatur|tinjau|meninjau|verifikasi|memverifikasi|konfirmasi|mengonfirmasi|gunakan|menggunakan|hindari|pastikan|jangan|laporkan|melaporkan|blokir|memblokir|amankan|mengamankan|perbarui|memperbarui|update|keluar|logout|hentikan|menghentikan|batasi|membatasi|simpan|menyimpan|bandingkan|membandingkan|pindai|scan|ketuk|tap|lakukan|ikuti|konsumsi|mengonsumsi)\b/i;
const ATTACKER = /\b(?:pelaku|penyerang|hacker|peretas|malware|spyware|aplikasi pihak ketiga|orang lain)\b/i;
const GENERIC_END = /\b(?:dengan langkah sederhana|dengan langkah mudah|tetap aman|bebas berinteraksi|pentingnya keamanan|lebih aman dan nyaman|jaga keamanan akun|semoga bermanfaat|yuk coba)\b/i;
const BOILER = /(?:baca\s+juga|read\s+also|cookie(?:\s+policy)?|privacy\s+(?:policy|notice)|kebijakan\s+privasi|syarat\s+dan\s+ketentuan|terms\s+of\s+use|copyright|hak\s+cipta|newsletter|subscribe|ikuti\s+kami|follow\s+us|login|sign\s+in|contact\s+us|hubungi\s+kami)/i;
const PRIVACY_METADATA = /(?:privacy\s+(?:policy|notice|statement)|kebijakan\s+privasi|pemberitahuan\s+privasi|cookie(?:\s+policy)?|syarat\s+dan\s+ketentuan|terms\s+of\s+use)/i;
const NON_PRIVACY_BOILERPLATE = /(?:baca\s+juga|read\s+also|cookie(?:\s+policy)?|terms\s+of\s+use|syarat\s+dan\s+ketentuan|copyright|hak\s+cipta|newsletter|subscribe|follow\s+(?:me|us)|ikuti\s+kami|sign\s+in|login|contact\s+us|hubungi\s+kami|(?:author|writer|contributor)\s+(?:bio|profile)|about\s+the\s+author|tentang\s+penulis|voice experience.*generated by ai|audio.*generated by ai|^(?:by|oleh|written by|ditulis oleh|edited by|disunting oleh)\s+[\p{L}.' -]{3,80}[.!]?$)/iu;
const STOP = new Set(['yang','dan','atau','dari','untuk','dengan','tentang','cara','adalah','pada','itu','ini','sebagai','dapat','bisa','lebih','juga']);
const fmt = v => String(v || '').trim().toLocaleLowerCase('id-ID');
const words = v => String(v || '').trim().split(/\s+/).filter(Boolean);
const bodyParts = s => [s?.body, ...(Array.isArray(s?.points) ? s.points : [])].map(v => String(v || '').trim()).filter(Boolean);
const bodyWords = s => bodyParts(s).reduce((n, v) => n + words(v).length, 0);
const factKey = c => `${String(c?.sourceId || '').trim()}::${String(c?.evidence || '').trim().toLocaleLowerCase('id-ID').replace(/\s+/g, ' ')}`;

function looksLikeUserAction(value) {
  const text = String(value || '').trim();
  const m = text.match(ACTION);
  return Boolean(m) && !ATTACKER.test(text.slice(0, m.index || 0));
}
function bankTokens(value) {
  return [...new Set(String(value || '').toLocaleLowerCase('id-ID').replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(t => t.length > 2 && !STOP.has(t)))];
}
function manualEvidenceCandidates(text) {
  return String(text || '').replace(/\r/g, '\n').split(/(?<=[.!?])\s+|\n+/).map(v => v.trim()).filter(Boolean).flatMap(sentence => {
    if (BOILER.test(sentence)) return [];
    const n = words(sentence).length;
    if (n >= 4 && n <= 32) return [sentence];
    if (n < 4) return [];
    return sentence.split(/(?<=[;:])\s+|\s+[—–]\s+|,\s+(?=(?:sedangkan|sementara|tetapi|namun|dan)\s+)/i)
      .map(v => v.trim()).filter(v => words(v).length >= 4 && words(v).length <= 32 && !BOILER.test(v));
  });
}
function extractManualFactBank(sources = [], topic = '') {
  const topicTerms = bankTokens(topic); const queues = [];
  (sources || []).forEach((source, i) => {
    const wanted = [...new Set([...topicTerms, ...bankTokens(source?.title)])]; const seen = new Set();
    const q = manualEvidenceCandidates(source?.text).map((evidence, order) => {
      const key = evidence.toLocaleLowerCase('id-ID').replace(/\s+/g, ' '); if (seen.has(key)) return null; seen.add(key);
      const tokens = new Set(bankTokens(evidence)); return { sourceId: `source-${i + 1}`, evidence, order, score: wanted.filter(t => tokens.has(t)).length };
    }).filter(Boolean).sort((a,b) => b.score - a.score || a.order - b.order); queues.push(q);
  });
  const out = [], seen = new Set();
  while (out.length < 36 && queues.some(q => q.length)) for (const q of queues) {
    const f = q.shift(); if (!f) continue; const key = factKey(f); if (!seen.has(key)) { seen.add(key); out.push({ sourceId:f.sourceId, evidence:f.evidence }); }
    if (out.length >= 36) break;
  }
  return out;
}
function distinctBank(bank = []) { const seen = new Set(); return bank.filter(f => { const k=factKey(f); if (!String(f?.evidence||'').trim() || seen.has(k)) return false; seen.add(k); return true; }); }
function factFallbackSections(n) { const mid=['FAKTA UTAMA','PENJELASAN','KONTEKS']; return Array.from({length:n},(_,i)=>i===0?'PEMBUKA':i===n-1?'KESIMPULAN':mid[Math.min(i-1,mid.length-1)]); }
function isFactFallback(content) {
  const s=content?.slides||[]; return s.length>=4 && /^PEMBUKA$/i.test(s[0]?.section||'') && /^KESIMPULAN$/i.test(s.at(-1)?.section||'') && s.slice(1,-1).every(x=>/^(?:FAKTA UTAMA|PENJELASAN|KONTEKS)$/i.test(x?.section||''));
}
function effectiveManualFormat(content, requestedFormat) { return content?.__manualGuardFallback===true && isFactFallback(content) ? 'Fakta singkat' : requestedFormat; }

function deterministicRoleErrors(content, format, { fallbackMode=false }={}) {
  const f=fmt(format), s=content?.slides||[], e=[]; if (!s.length) return ['slide:0:role: carousel tidak memiliki slide.'];
  if (fallbackMode || f==='fakta singkat') { if (!isFactFallback(content)) e.push('slide:0:role: fallback Fakta singkat harus memakai PEMBUKA → FAKTA/PENJELASAN/KONTEKS → KESIMPULAN.'); return e; }
  if (f==='tutorial langkah' || f==='masalah dan solusi') {
    const re=f==='tutorial langkah'?/^LANGKAH\b/i:/^SOLUSI$/i, name=f==='tutorial langkah'?'LANGKAH':'SOLUSI'; const idx=[]; let bad=0;
    s.forEach((x,i)=>{ if(!re.test(x?.section||''))return; idx.push(i); if(!bodyParts(x).some(looksLikeUserAction)){bad++;e.push(`slide:${i}:role: ${name} harus berisi tindakan konkret pengguna; fitur, mekanisme, risiko, tanda, atau tindakan pelaku bukan ${name}.`);} });
    if(f==='masalah dan solusi'&&!s.some(x=>/^MASALAH$/i.test(x?.section||'')))e.push('slide:0:role: format Masalah dan solusi wajib memiliki MASALAH.');
    if(idx.length<2)e.push(`slide:${Math.min(2,s.length-1)}:role: ${f==='tutorial langkah'?'Tutorial langkah membutuhkan minimal dua LANGKAH berbeda.':'format Masalah dan solusi membutuhkan minimal dua SOLUSI berbeda.'}`);
    const last=s.length-1;if(/^HASIL(?:\/PENUTUP)?$/i.test(s[last]?.section||'')&&(idx.length<2||bad))e.push(`slide:${last}:role: HASIL tidak boleh dipakai bila langkah/solusi sebelumnya belum valid.`);
  } else if(f==='listicle') {
    if(isFactFallback(content))e.push('slide:0:role: Listicle tidak boleh diam-diam berubah menjadi Fakta singkat.');
    const idx=s.map((x,i)=>/^ITEM\s+\d+$/i.test(x?.section||'')?i:-1).filter(i=>i>=0); if(idx.length<Math.min(3,s.length))e.push('slide:1:role: Listicle harus memiliki minimal tiga ITEM berbeda jika sumber menyediakan fakta yang cukup.');
    idx.forEach((i,n)=>{if(Number(String(s[i].section).match(/\d+/)?.[0]||0)!==n+1)e.push(`slide:${i}:role: nomor ITEM Listicle harus berurutan mulai 1.`);});
  } else if(f==='tips cepat') {
    const tips=s.filter(x=>/^TIPS?\s*\d*$/i.test(x?.section||'')); if(tips.length<2)e.push('slide:1:role: Tips cepat membutuhkan minimal dua tips/tindakan berbeda.'); tips.forEach(x=>{if(!bodyParts(x).some(looksLikeUserAction))e.push(`slide:${s.indexOf(x)}:role: tips harus berupa tindakan konkret pengguna.`);});
  } else if(f==='before-after') {
    if(!s.some(x=>/^BEFORE$/i.test(x?.section||'')))e.push('slide:0:role: Before-after membutuhkan BEFORE.'); if(!s.some(x=>/^AFTER$/i.test(x?.section||'')))e.push(`slide:${s.length-1}:role: Before-after membutuhkan AFTER.`);
  }
  return [...new Set(e)];
}
function contentDensityErrors(content, bank=[]) {
  const s=content?.slides||[], b=distinctBank(bank); if(!b.length)return ['coverage:density: FACT_BANK kosong.']; const e=[]; const min=b.length>=4?17:b.length>=2?12:7;
  s.forEach((x,i)=>{const n=bodyWords(x);if(n<min)e.push(`slide:${i}:density: isi terlalu tipis (${n} kata); target minimal ${min} kata substantif dari sumber.`);if(i===s.length-1&&GENERIC_END.test(bodyParts(x).join(' '))&&!(x?.claims||[]).some(c=>factKey(c)))e.push(`slide:${i}:density: penutup masih generik tanpa fakta/outcome source-backed.`);});
  const used=new Set(s.flatMap(x=>(x?.claims||[]).map(factKey).filter(k=>!k.endsWith('::')))); const req=b.length>=4?Math.min(b.length,Math.max(4,s.length)):Math.min(b.length,Math.max(1,s.length-1)); if(used.size<req)e.push(`coverage:density: hanya ${used.size} fakta canonical dipakai; gunakan minimal ${req} fakta berbeda yang relevan.`); return [...new Set(e)];
}

function fieldValueForKey(content, key) {
  const match = String(key || '').match(/^slide:(\d+):(title|body|point:(\d+))$/i);
  if (!match) return '';
  const slide = content?.slides?.[Number(match[1])];
  if (!slide) return '';
  if (match[2].toLocaleLowerCase('en-US') === 'title') return String(slide.title || '').trim();
  if (match[2].toLocaleLowerCase('en-US') === 'body') return String(slide.body || '').trim();
  return String(slide.points?.[Number(match[3])] || '').trim();
}

function filterManualPrivacyBoilerplateErrors(errors = [], content) {
  return errors.filter(error => {
    const text = String(error || '');
    const match = text.match(/^(slide:\d+:(?:title|body|point:\d+)): metadata\/boilerplate website masuk ke konten\.$/i);
    if (!match) return true;
    const value = fieldValueForKey(content, match[1]);
    if (!/\b(?:privacy|privasi)\b/i.test(value)) return true;
    // Suppress only the historical false positive where the bare privacy word is
    // the sole boilerplate match. Any real metadata marker keeps the error.
    if (PRIVACY_METADATA.test(value) || NON_PRIVACY_BOILERPLATE.test(value)) return true;
    return false;
  });
}

function formatRule(format, fallbackMode) {
  const f=fmt(format); if(fallbackMode||f==='fakta singkat')return 'Fakta singkat wajib PEMBUKA → fakta/konteks → KESIMPULAN; jangan membuat langkah palsu.';
  if(f==='listicle')return 'LISTICLE: setiap ITEM adalah item/fakta berbeda dari artikel utama. Jika artikel berisi 4–5 item, prioritaskan semua item itu; related-content/teaser harus ditolak.';
  if(f==='tutorial langkah')return 'Tutorial: minimal dua LANGKAH tindakan pengguna yang didukung sumber.';
  if(f==='masalah dan solusi')return 'Masalah dan solusi: MASALAH + minimal dua SOLUSI tindakan pengguna; fitur/mekanisme bukan solusi.';
  if(f==='tips cepat')return 'Tips cepat: minimal dua tips konkret berbeda yang didukung sumber.';
  if(f==='before-after')return 'Before-after: BEFORE dan AFTER harus punya hubungan yang dinyatakan sumber.';
  return 'Pertahankan fungsi format yang diminta.';
}
function auditPrompt(draft,bank,format,topic,sources,fallbackMode){return `AUDIT PERAN FORMAT — FINAL Manual + URL. Jangan menulis ulang.\nTOPIK PENGGUNA: ${JSON.stringify(topic)}\nFORMAT: ${JSON.stringify(format)}\nSOURCE TITLES: ${JSON.stringify((sources||[]).map(s=>s?.title||''))}\nATURAN FORMAT: ${formatRule(format,fallbackMode)}\nTolak isi dari artikel terkait, Baca Juga, rekomendasi, sidebar, teaser, atau topik lain. Title/body/points/evidence harus satu ide dan setiap fakta harus didukung FACT_BANK. Jangan tambah sebab/manfaat/kepastian dari pengetahuan luar.\nFACT_BANK: ${JSON.stringify(bank)}\nSLIDES: ${JSON.stringify(draft?.slides||[])}\nKembalikan HANYA JSON {"formatFit":true,"invalid":[{"slideIndex":1,"reason":"..."}]}; kedua field wajib.`;}
function parseAudit(r){const raw=r?.choices?.[0]?.message?.content;if(!raw)throw new Error('Audit final kosong.');const p=JSON.parse(raw);if(typeof p?.formatFit!=='boolean')throw new Error('Audit final wajib memiliki formatFit boolean.');if(!Array.isArray(p?.invalid))throw new Error('Audit final wajib memiliki invalid array.');return{formatFit:p.formatFit,invalid:p.invalid.map(x=>({slideIndex:Number(x?.slideIndex),reason:String(x?.reason||'').trim()})).filter(x=>Number.isInteger(x.slideIndex)&&x.slideIndex>=0)};}
async function auditRoles(openai,draft,bank,format,topic='',sources=[],fallbackMode=false){let last;for(let i=0;i<MAX_ROLE_AUDIT_ATTEMPTS;i++)try{return parseAudit(await openai.chat.completions.create({model:config.aiModel,messages:[{role:'system',content:'Anda auditor source-grounded ketat. Tolak related-content.'},{role:'user',content:auditPrompt(draft,bank,format,topic,sources,fallbackMode)}],response_format:{type:'json_object'}}));}catch(e){last=e;}throw Object.assign(new Error(`Audit final gagal; konten tidak boleh dianggap valid tanpa audit: ${last?.message||'provider gagal'}`),{status:422});}

function rebuildPrompt(draft,bank,format,errors,topic,sources){
  const f=fmt(format); let structure='Gunakan 4–5 slide sesuai fungsi format.';
  if(f==='listicle')structure='LISTICLE: buat 4–5 slide ITEM 1..N; satu item utama berbeda per slide. Jika artikel punya 4–5 item, pakai item itu—jangan buang slot untuk intro/penutup generik.';
  else if(f==='fakta singkat')structure=`Gunakan pola section ${JSON.stringify(factFallbackSections(Math.min(5,Math.max(4,draft?.slides?.length||4))))}.`;
  else if(f==='tutorial langkah')structure='PEMBUKA → minimal dua LANGKAH pengguna → HASIL/PENUTUP; jangan mengarang langkah.';
  else if(f==='masalah dan solusi')structure='MASALAH → minimal dua SOLUSI pengguna → HASIL/PENUTUP; fitur/mekanisme bukan solusi.';
  else if(f==='tips cepat')structure='PEMBUKA → minimal dua TIPS tindakan berbeda → PENUTUP.';
  else if(f==='before-after')structure='BEFORE → PROSES/PERUBAHAN → AFTER → PENUTUP hanya bila hubungan didukung sumber.';
  const density=distinctBank(bank).length>=4?'Targetkan sekitar 18–32 kata substantif total pada body/points per slide; body 12–22 kata + 1–2 points 3–7 kata bila ada fakta pendukung berbeda.':'Isi setiap slide sepadat mungkin dari fakta yang ada tanpa mengarang.';
  return `PERBAIKAN FINAL QUALITY — REBUILD Manual + URL. Tulis ulang SELURUH carousel.\nTOPIK: ${JSON.stringify(topic)}\nFORMAT WAJIB: ${JSON.stringify(format)}\n${structure}\n${density}\nERROR: ${JSON.stringify(errors)}\nSOURCE TITLES: ${JSON.stringify((sources||[]).map(s=>s?.title||''))}\nATURAN KERAS:\n- HANYA FACT_BANK; dilarang pengetahuan luar dan artikel terkait, Baca Juga, rekomendasi, sidebar, teaser.\n- Setiap body/point faktual wajib claim field tepat + sourceId + evidence PERSIS FACT_BANK. Jika title membuat klaim faktual, title juga wajib punya claim field slide:X:title.\n- Gunakan fakta canonical berbeda antar-slide; jangan parafrase fakta sama sebagai item baru.\n- Body maks 24 kata; title maks 12; maks 3 points, tiap point maks 7 kata; Bahasa Indonesia natural.\n- Pertahankan modalitas (dapat/bisa/mungkin), jangan menguatkan jadi pasti.\n- Untuk Tutorial/Masalah/Tips, hanya tindakan pengguna yang didukung evidence boleh jadi LANGKAH/SOLUSI/TIPS. Informasi fitur atau kemampuan produk tidak boleh disamarkan menjadi SOLUSI/LANGKAH.\n- Tidak ada filler/CTA motivasi kosong.\nFACT_BANK: ${JSON.stringify(bank)}\nCURRENT: ${JSON.stringify(draft?.slides||[])}\nKembalikan HANYA JSON {"slides":[{"section":"...","title":"...","body":"...","points":[],"claims":[{"field":"slide:0:body","text":"...","sourceId":"source-1","evidence":"..."}]}]}.`;
}
function parseSlides(r){const raw=r?.choices?.[0]?.message?.content;if(!raw)throw new Error('Rebuild final kosong.');const p=JSON.parse(raw);if(!Array.isArray(p?.slides)||p.slides.length<4||p.slides.length>5)throw new Error('Rebuild final harus menghasilkan 4–5 slide.');return p.slides.map(s=>({section:String(s?.section||'').trim(),title:String(s?.title||'').trim(),body:String(s?.body||'').trim(),points:Array.isArray(s?.points)?s.points.map(v=>String(v||'').trim()).filter(Boolean):[],claims:Array.isArray(s?.claims)?s.claims.map(c=>({field:String(c?.field||'').trim(),text:String(c?.text||'').trim(),sourceId:String(c?.sourceId||'').trim(),evidence:String(c?.evidence||'').trim()})).filter(c=>c.field||c.text||c.sourceId||c.evidence):[]}));}
function syncTop(content){const s=content?.slides||[];if(!s.length)return content;const first=s[0],mid=s.find((x,i)=>i>0&&(x.body||x.points?.length))||first,last=s.at(-1),main=x=>String(x?.body||'').trim()||(x?.points||[]).join(' ').trim()||String(x?.title||'').trim();return{...content,hook:String(first?.title||content.hook||'').trim(),body:main(mid),caption:main(mid),cta:String(last?.title||content.cta||'').trim()};}
async function validateFinal(contentService,draft,options,sources,openai,format){const base={...draft,slides:draft.slides.map(x=>({...x,section:String(x?.section||'').trim()}))};const checked=sourceFilter.validateVerifiedContent(base,{slides:draft.slides},{contentService,format,manualTopic:options.requestedTopic||'',sources,autoSourceTopic:false});const validationErrors=filterManualPrivacyBoilerplateErrors(checked.errors,checked.content||draft);if(validationErrors.length)return{content:checked.content||draft,errors:validationErrors};const errors=await sourceFilter.auditClaimSemantics(openai,checked.content,options.requestedTopic||draft?.topic||'',format);return{content:syncTop(checked.content),errors};}

async function repairManualSourceRoles({contentService,generated,options={},sources=[],client}){
  const requested=options.contentFormat||'Fakta singkat',topic=options.requestedTopic||generated?.topic||'',bank=distinctBank(extractManualFactBank(sources,topic));
  if(!bank.length)throw Object.assign(new Error('URL berhasil dibaca tetapi tidak menghasilkan fakta artikel utama yang dapat diverifikasi.'),{status:422});
  const openai=client||new OpenAI({apiKey:config.aiApiKey,baseURL:config.aiBaseUrl});let draft={...generated,slides:(generated?.slides||[]).map(x=>({...x}))};delete draft.effectiveContentFormat;delete draft.__manualGuardFallback;let fallback=false,last=[];
  for(let attempt=0;attempt<=MAX_ROLE_REPAIR_ATTEMPTS;attempt++){
    const format=fallback?'Fakta singkat':requested,role=deterministicRoleErrors(draft,format,{fallbackMode:fallback}),density=contentDensityErrors(draft,bank),dup=manualSourceDedupe.manualCrossSlideDuplicateErrors(draft),audit=await auditRoles(openai,draft,bank,format,topic,sources,fallback),auditErr=audit.invalid.map(x=>`slide:${x.slideIndex}:audit: ${x.reason||'isi tidak sesuai artikel utama/format.'}`);
    if(!fallback&&!audit.formatFit&&fmt(requested)!=='fakta singkat'){fallback=true;last=[`format: sumber tidak cukup untuk ${requested}; gunakan Fakta singkat tanpa mengarang.`,...auditErr];}
    else {let validation=[];if(!role.length&&!density.length&&!dup.length&&!auditErr.length&&audit.formatFit){const final=await validateFinal(contentService,draft,options,sources,openai,format);validation=final.errors;if(!validation.length){const clean=syncTop(final.content);delete clean.effectiveContentFormat;delete clean.__manualGuardFallback;return fallback?{...clean,effectiveContentFormat:'Fakta singkat'}:clean;}}last=[...role,...density,...dup,...auditErr,...validation];}
    if(attempt===MAX_ROLE_REPAIR_ATTEMPTS)break;
    try{const r=await openai.chat.completions.create({model:config.aiModel,messages:[{role:'system',content:'Bangun ulang carousel Manual + URL hanya dari artikel utama.'},{role:'user',content:rebuildPrompt(draft,bank,fallback?'Fakta singkat':requested,last,topic,sources)}],response_format:{type:'json_object'}});draft={...draft,slides:parseSlides(r)};}catch(e){last=[`JSON rebuild final tidak valid: ${e.message}`];}
  }
  throw Object.assign(new Error(`Topik manual + URL belum dapat dibuat tanpa mengarang setelah final rebuild: ${last[0]||'kualitas konten tidak valid'}`),{status:422,validationErrors:last});
}

module.exports={repairManualSourceRoles,deterministicRoleErrors,contentDensityErrors,looksLikeUserAction,effectiveManualFormat,auditRoles,MAX_ROLE_AUDIT_ATTEMPTS,MAX_ROLE_REPAIR_ATTEMPTS,extractManualFactBank,manualEvidenceCandidates,filterManualPrivacyBoilerplateErrors};
