const { joinGatewayUrl } = require('../providers/NineRouterProvider');
const CACHE_TTL = 10 * 60 * 1000;
const fields = ['capability', 'capabilities', 'modality', 'modalities', 'type', 'service', 'service_kind', 'input_modalities', 'output_modalities'];
const values = value => Array.isArray(value) ? value : value && typeof value === 'object' ? Object.entries(value).filter(([, enabled]) => enabled).map(([name]) => name) : value == null ? [] : [value];
function configuredMapping() { try { return JSON.parse(process.env.NINEROUTER_CAPABILITY_MAP || '{}'); } catch { return {}; } }
function modelCapabilities(model, mapping = configuredMapping()) { const id = String(typeof model === 'string' ? model : model.id || model.name || '').trim(); const metadata = typeof model === 'object' && model ? fields.flatMap(field => values(model[field])).map(String) : []; const source = metadata.length ? metadata : values(mapping[id]).map(String); const result = new Set(); for (const item of source.map(value => value.toLowerCase())) { if (/text|chat|language/.test(item)) result.add('text'); if (/image/.test(item)) result.add('image'); if (/video/.test(item)) result.add('video'); } return result; }
function normalizeModels(payload, mapping) { const result = { text: [], image: [], video: [], unknown: [] }; const models = Array.isArray(payload) ? payload : payload?.data || payload?.models; if (!Array.isArray(models)) throw new Error('Respons katalog model 9Router tidak valid'); for (const model of models) { const id = String(typeof model === 'string' ? model : model?.id || model?.name || '').trim(); if (!id) continue; const capabilities = modelCapabilities(model, mapping); if (!capabilities.size) result.unknown.push(id); else for (const capability of capabilities) result[capability].push(id); } for (const capability of Object.keys(result)) result[capability] = [...new Set(result[capability])].sort(); return result; }
class NineRouterModels { constructor({ db, connector, transport = fetch, ttl = CACHE_TTL }) { this.db = db; this.connector = connector; this.transport = transport; this.ttl = ttl; this.cached = null; } async get({ refresh = false } = {}) { if (!refresh && this.cached && Date.now() - this.cached.at < this.ttl) return this.cached.value; const config = this.connector.configured(this.connector.setting(this.db, '9router')); const headers = { Accept: 'application/json' }; if (config.api_key) headers.Authorization = `Bearer ${config.api_key}`; const response = await this.transport(joinGatewayUrl(config.base_url, '/v1/models'), { headers }); if (!response.ok) throw Object.assign(new Error(await response.text() || `HTTP ${response.status}`), { status: response.status }); let payload; try { payload = await response.json(); } catch { throw Object.assign(new Error('Respons katalog model 9Router tidak valid'), { status: 502 }); } const value = normalizeModels(payload); this.cached = { at: Date.now(), value }; return value; } }
module.exports = { NineRouterModels, normalizeModels, modelCapabilities, CACHE_TTL };
