const OpenAI = require('openai');
const config = require('../config');

const MAX_FACTS = 36;
const MAX_VERIFY_ATTEMPTS = 3;
const TOPIC_STOPWORDS = new Set(['yang', 'dan', 'atau', 'dari', 'untuk', 'dengan', 'tentang', 'cara', 'adalah', 'pada', 'itu', 'ini', 'sebagai']);
const GROUNDING_STOPWORDS = new Set([
  ...TOPIC_STOPWORDS,
  'ai', 'api', 'gpt', 'agar', 'karena', 'saat', 'ketika', 'oleh', 'dalam', 'lebih', 'juga', 'akan',
  'bisa', 'dapat', 'sebelum', 'setelah', 'mereka', 'kami', 'kamu', 'anda', 'tersebut', 'sebuah',
  'para', 'jadi', 'menggunakan', 'digunakan', 'dipakai', 'membantu', 'memungkinkan', 'mendukung',
  'memiliki', 'menjadi', 'termasuk', 'hadir'
]);
const NEGATION_TOKENS = new Set(['tidak', 'bukan', 'belum', 'tanpa']);
const GENERIC_ENTITY_TOKENS = new Set(['ai', 'api', 'gpt']);
const TOPIC_RELEVANCE_STOPWORDS = new Set([
  ...TOPIC_STOPWORDS,
  'ai', 'api', 'gpt', 'era', 'digital', 'teknologi', 'semakin', 'maju', 'baru',
  'fitur', 'rilis', 'resmi', 'cara', 'gunakan', 'menggunakan', 'buat', 'bisa', 'dapat'
]);
const NEUTRAL_RELEVANCE_TOKENS = new Set([
  'cek', 'baca', 'lihat', 'simpan', 'bandingkan', 'perhatikan', 'pelajari', 'periksa',
  'konteks', 'sumber', 'temuan', 'detail', 'bagian', 'relevan', 'utama', 'lengkap',
  'kesimpulan', 'menyimpulkan', 'membagikan', 'informasi', 'sebelum', 'setelah',
  'fokus', 'pilih', 'kebutuhan', 'pendekatan'
]);
const BOILERPLATE = /(?:cookie|privacy|privasi|terms of use|syarat dan ketentuan|copyright|hak cipta|newsletter|subscribe|follow\s+(?:me|us)|ikuti kami|sign in|login|contact us|hubungi kami|(?:author|writer|contributor)\s+(?:bio|profile)|about the author|tentang penulis|voice experience.*generated by ai|audio.*generated by ai|^(?:by|oleh|written by|ditulis oleh|edited by|disunting oleh)\s+[\p{L}.' -]{3,80}[.!]?$)/iu;
const FACT_VERBS = /\b(?:adalah|merupakan|memiliki|menggunakan|digunakan|dipakai|meluncurkan|diluncurkan|merilis|dirilis|menawarkan|menyebut|mengatakan|menurut|menunjukkan|menemukan|mengungkap|mengumumkan|melaporkan|menyatakan|menjelaskan|mencapai|meningkat|menurun|berasal|didirikan|bekerja|mampu|dapat|bisa|membantu|menghasilkan|mengubah|menjadi|termasuk|tersedia|dikembangkan|mencatat|menilai|menganggap|memungkinkan|menggantikan|berpotensi|berisiko|mendukung|hadir)\b/i;
const FACT_MARKERS = /\b(?:risiko|temuan|fitur|kemampuan|resmi|gratis|berbayar|rilis|peluncuran|versi|akurasi|kinerja|statistik|persentase|pengguna|pelanggan|perusahaan|model)\b/i;
const ASSERTIVE_FACT_MARKERS = /\b(?:resmi|gratis|berbayar|rilis|peluncuran|versi|akurasi|kinerja|statistik|persentase)\b/i;
const NON_FACTUAL_START = /^(?:coba|baca|lihat|simpan|cek|pilih|mulai|bandingkan|pertimbangkan|fokus|jelajahi|ikuti|bagikan|tanyakan|pikirkan|perhatikan|gunakan|buat|atur|hindari|pastikan|sesuaikan|tentukan|uji|evaluasi|catat|pelajari)\b/i;
const NEUTRAL_SOURCE_COPY = /^(?:cek|baca|lihat|simpan|periksa|pelajari|bandingkan|perhatikan)\s+(?:konteks|sumber|artikel|detail|temuan|informasi|bagian|versi)\b/i;
const ENGLISH_DISPLAY_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'to', 'of', 'in', 'on', 'for', 'with', 'from', 'by',
  'is', 'are', 'was', 'were', 'be', 'been', 'being', 'has', 'have', 'had', 'do', 'does',
  'did', 'not', "don't", "doesn't", 'can', 'could', 'should', 'would', 'will', 'most',
  'about', 'without', 'into', 'that', 'this', 'these', 'those', 'as', 'than', 'which', 'who',
  'when', 'why', 'how'
]);
const INDONESIAN_DISPLAY_WORDS = new Set([
  'yang', 'dan', 'atau', 'untuk', 'dengan', 'dari', 'di', 'pada', 'adalah', 'merupakan',
  'tidak', 'bukan', 'belum', 'bisa', 'dapat', 'akan', 'ini', 'itu', 'agar', 'karena',
  'sebagai', 'tentang', 'sebelum', 'setelah', 'lebih', 'oleh', 'dalam', 'juga', 'saat'
]);

const words = value => String(value || '').trim().split(/\s+/).filter(Boolean);
const normalize = value => String(value || '')
  .toLocaleLowerCase('id-ID')
  .replace(/&nbsp;/gi, ' ')
  .replace(/[^a-z0-9%\s]/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();
const tokens = value => new Set(normalize(value).split(' ').filter(Boolean));

function topicTokens(value) {
  return [...tokens(value)].filter(token => (token.length > 2 || token === 'ai') && !TOPIC_STOPWORDS.has(token));
}

function topicEntityTokens(value) {
  const raw = String(value || '').match(/[A-Za-z0-9][A-Za-z0-9.-]*/g) || [];
  const strong = new Set();
  raw.forEach((token, index) => {
    const acronym = /^[A-Z0-9]{2,}$/.test(token);
    const internalCapital = /[a-z][A-Z]/.test(token);
    if (acronym || internalCapital) strong.add(normalize(token));
    const currentTitle = /^[A-Z][a-z0-9.-]+$/.test(token);
    const next = raw[index + 1];
    const nextTitle = next && /^[A-Z][a-z0-9.-]+$/.test(next);
    if (currentTitle && nextTitle) {
      strong.add(normalize(token));
      strong.add(normalize(next));
    }
  });
  return [...strong].filter(Boolean);
}

function evidenceCandidates(text) {
  const sentences = String(text || '').replace(/\s+/g, ' ').trim().split(/(?<=[.!?])\s+/);
  return sentences.flatMap(sentence => {
    const clean = sentence.trim();
    if (!clean || BOILERPLATE.test(clean)) return [];
    if (words(clean).length >= 4 && words(clean).length <= 32) return [clean];
    return clean.split(/(?<=[;:])\s+|\s+[—–]\s+|,\s+(?=(?:while|but|however|sedangkan|sementara|tetapi|namun|dan)\s+)/i)
      .map(value => value.trim())
      .filter(value => words(value).length >= 4 && words(value).length <= 32 && !BOILERPLATE.test(value));
  });
}

function extractFactBank(sources = [], topic = '') {
  const requested = topicTokens(topic);
  const perSource = sources.map((source, sourceIndex) => {
    const wanted = [...new Set([...requested, ...topicTokens(source?.title || '')])];
    const seen = new Set();
    return evidenceCandidates(source?.text).map((evidence, order) => {
      const normalized = normalize(evidence);
      if (!normalized || seen.has(normalized)) return null;
      seen.add(normalized);
      const evidenceTokens = tokens(evidence);
      const overlap = wanted.filter(token => evidenceTokens.has(token)).length;
      return { sourceId: `source-${sourceIndex + 1}`, evidence, overlap, score: overlap * 100 - order, order };
    }).filter(Boolean).sort((a, b) => b.score - a.score || a.order - b.order);
  });
  const relevantCount = perSource.reduce((sum, queue) => sum + queue.filter(fact => fact.overlap > 0).length, 0);
  const eligible = relevantCount >= 4 ? perSource.map(queue => queue.filter(fact => fact.overlap > 0)) : perSource;
  const bank = [];
  const seenEvidence = new Set();
  while (bank.length < MAX_FACTS && eligible.some(queue => queue.length)) {
    for (const queue of eligible) {
      const fact = queue.shift();
      if (!fact) continue;
      const key = normalize(fact.evidence);
      if (!seenEvidence.has(key)) {
        seenEvidence.add(key);
        bank.push({ sourceId: fact.sourceId, evidence: fact.evidence });
      }
      if (bank.length >= MAX_FACTS) break;
    }
  }
  return bank;
}

function numericTokens(value) { return String(value || '').match(/\b\d+(?:[.,]\d+)?%?\b/g) || []; }
function isQuestion(value) { return /\?\s*$/.test(String(value || '').trim()); }

function likelyEnglishDisplayText(value) {
  const displayTokens = String(value || '').toLocaleLowerCase('en-US').match(/[a-z]+(?:'[a-z]+)?/g) || [];
  if (displayTokens.length < 4) return false;
  const englishScore = displayTokens.filter(token => ENGLISH_DISPLAY_WORDS.has(token)).length;
  const indonesianScore = displayTokens.filter(token => INDONESIAN_DISPLAY_WORDS.has(token)).length;
  if (englishScore >= 2 && englishScore > indonesianScore) return true;
  return displayTokens.length >= 6 && englishScore >= 1 && indonesianScore === 0;
}

function requiresEvidence(value, section = '', kind = 'body') {
  const text = String(value || '').trim();
  if (!text) return false;
  if (numericTokens(text).length) return true;
  if (/\b(?:rp|usd|dolar|persen|tahun|bulan|hari|jam|menit|juta|miliar|triliun)\b/i.test(text)) return true;
  if (NON_FACTUAL_START.test(text)) return false;
  if (isQuestion(text)) return false;
  if (FACT_VERBS.test(text)) return true;
  if (kind === 'point') return ASSERTIVE_FACT_MARKERS.test(text);
  if (FACT_MARKERS.test(text)) return true;
  return false;
}

function isNeutralSourceCopy(value, slideIndex, totalSlides) {
  const text = String(value || '').trim();
  if (!text) return true;
  const edge = slideIndex === 0 || slideIndex === totalSlides - 1;
  if (edge && isQuestion(text)) return true;
  return NEUTRAL_SOURCE_COPY.test(text);
}

function requiresSourceEvidence(value, section = '', kind = 'body', slideIndex = 0, totalSlides = 0, format = '') {
  const text = String(value || '').trim();
  if (!text) return false;
  if (requiresEvidence(text, section, kind)) return true;
  if (String(format || '').toLocaleLowerCase('id-ID') !== 'masalah dan solusi') return false;
  if (isNeutralSourceCopy(text, slideIndex, totalSlides)) return false;
  if (kind === 'title') return false;
  return words(text).length >= 2;
}

function slideFields(slide, slideIndex) {
  const fields = [
    { key: `slide:${slideIndex}:title`, value: String(slide?.title || '').trim(), kind: 'title' },
    { key: `slide:${slideIndex}:body`, value: String(slide?.body || '').trim(), kind: 'body' }
  ];
  (slide?.points || []).forEach((point, pointIndex) => fields.push({ key: `slide:${slideIndex}:point:${pointIndex}`, value: String(point || '').trim(), kind: 'point' }));
  return fields;
}

function sourceMap(sources = []) { return new Map(sources.map((source, index) => [`source-${index + 1}`, normalize(source?.text || '')])); }
function normalizeClaims(slides = []) {
  return slides.flatMap((slide, slideIndex) => (Array.isArray(slide?.claims) ? slide.claims : []).map(claim => ({
    slideIndex, field: String(claim?.field || '').trim(), text: String(claim?.text || '').trim(), sourceId: String(claim?.sourceId || '').trim(), evidence: String(claim?.evidence || '').trim()
  })));
}

function pruneUnneededClaims(content, format = '') {
  if (!content || !Array.isArray(content.slides)) return content;
  const totalSlides = content.slides.length;
  return { ...content, slides: content.slides.map((slide, slideIndex) => ({
    ...slide,
    claims: (Array.isArray(slide?.claims) ? slide.claims : []).filter(claim => {
      const field = slideFields(slide, slideIndex).find(item => item.key === String(claim?.field || ''));
      return Boolean(field?.value) && requiresSourceEvidence(field.value, slide.section, field.kind, slideIndex, totalSlides, format);
    })
  })) };
}

function normalizeFactSections(slides = [], format = '') {
  if (String(format || '').toLocaleLowerCase('id-ID') !== 'fakta singkat' || !Array.isArray(slides)) return slides;
  const labels = slides.length === 4 ? ['PEMBUKA', 'FAKTA UTAMA', 'KONTEKS', 'KESIMPULAN'] : slides.length === 5 ? ['PEMBUKA', 'FAKTA UTAMA', 'PENJELASAN', 'KONTEKS', 'KESIMPULAN'] : slides.map((_, index) => index === 0 ? 'PEMBUKA' : index === slides.length - 1 ? 'KESIMPULAN' : 'PENJELASAN');
  return slides.map((slide, index) => ({ ...slide, section: labels[index] }));
}

function groundingTerms(value) { return [...tokens(value)].filter(token => (token.length > 2 || token === 'ai') && !GROUNDING_STOPWORDS.has(token)); }
function evidenceSupport(text, evidence) {
  const textNorm = normalize(text); const evidenceNorm = normalize(evidence);
  if (!textNorm || !evidenceNorm) return { exact: false, matches: 0, total: 0, score: 0 };
  const claimNumbers = numericTokens(text); const evidenceNumbers = new Set(numericTokens(evidence));
  if (!claimNumbers.every(number => evidenceNumbers.has(number))) return { exact: false, matches: 0, total: 0, score: 0 };
  const claimNegations = [...tokens(text)].filter(token => NEGATION_TOKENS.has(token)); const evidenceTokenSet = tokens(evidence);
  if (claimNegations.some(token => !evidenceTokenSet.has(token))) return { exact: false, matches: 0, total: 0, score: 0 };
  const exact = evidenceNorm.includes(textNorm); const terms = groundingTerms(text); const matches = terms.filter(token => evidenceTokenSet.has(token)).length;
  return { exact, matches, total: terms.length, score: terms.length ? matches / terms.length : 0 };
}

function recoverMissingClaims(candidate, sources = [], format = '') {
  if (!candidate || !Array.isArray(candidate.slides)) return candidate;
  const existing = new Set(normalizeClaims(candidate.slides).map(claim => claim.field).filter(Boolean));
  const evidence = sources.flatMap((source, index) => evidenceCandidates(source?.text).map(item => ({ sourceId: `source-${index + 1}`, evidence: item })));
  const totalSlides = candidate.slides.length;
  candidate.slides.forEach((slide, slideIndex) => {
    for (const field of slideFields(slide, slideIndex)) {
      if (!field.value || existing.has(field.key) || !requiresSourceEvidence(field.value, slide.section, field.kind, slideIndex, totalSlides, format)) continue;
      let best = null;
      for (const item of evidence) {
        const support = evidenceSupport(field.value, item.evidence);
        const acceptable = support.exact || (support.total >= 3 && support.matches >= 3 && support.score >= 0.8);
        if (!acceptable) continue;
        if (!best || Number(support.exact) > Number(best.support.exact) || support.score > best.support.score) best = { item, support };
      }
      if (!best) continue;
      if (!Array.isArray(slide.claims)) slide.claims = [];
      slide.claims.push({ field: field.key, text: field.value, sourceId: best.item.sourceId, evidence: best.item.evidence }); existing.add(field.key);
    }
  });
  return candidate;
}

function topicRelevanceTerms(manualTopic) {
  const entityTerms = topicEntityTokens(manualTopic).filter(token => !GENERIC_ENTITY_TOKENS.has(token));
  if (entityTerms.length) return entityTerms;
  return [...tokens(manualTopic)].filter(token => token.length > 2 && !TOPIC_RELEVANCE_STOPWORDS.has(token));
}
function validateSlideTopicRelevance(manualTopic, slides = [], verifiedClaimFields = new Set()) {
  const terms = topicRelevanceTerms(manualTopic); if (!manualTopic || !terms.length) return [];
  const errors = [];
  slides.forEach((slide, index) => {
    const edgeSlide = index === 0 || index === slides.length - 1 || /^(?:PEMBUKA|HOOK|PENUTUP|CTA|TRANSISI)$/i.test(String(slide?.section || '').trim());
    if (edgeSlide) return;
    const fields = slideFields(slide, index); if (fields.some(field => verifiedClaimFields.has(field.key))) return;
    const visibleTokens = tokens(fields.map(field => field.value).join(' ')); if (terms.some(term => visibleTokens.has(term))) return;
    const introducedSpecificTerms = [...visibleTokens].filter(token => token.length > 2 && !TOPIC_RELEVANCE_STOPWORDS.has(token) && !NEUTRAL_RELEVANCE_TOKENS.has(token) && !terms.includes(token));
    if (introducedSpecificTerms.length >= 2) errors.push(`Slide ${index + 1}: isi claim-free menyimpang dari inti topik manual; perbaiki agar tetap membahas ${manualTopic}.`);
  });
  return errors;
}
function validateManualTopicIdentity(manualTopic, slides = []) {
  const anchors = topicEntityTokens(manualTopic); if (!anchors.length) return [];
  const required = anchors.filter(anchor => !GENERIC_ENTITY_TOKENS.has(anchor)); if (!required.length) return [];
  const carouselTokens = tokens(slides.map(slide => `${slide?.title || ''} ${slide?.body || ''} ${(slide?.points || []).join(' ')}`).join(' '));
  return required.some(anchor => carouselTokens.has(anchor)) ? [] : [`Isi carousel kehilangan objek utama topik manual: ${required.join(' / ')}.`];
}

function validateVerifiedContent(base, candidate, { contentService, format, manualTopic, sources }) {
  const errors = [];
  if (!candidate || !Array.isArray(candidate.slides)) return ['Verifier tidak mengembalikan slides.'];
  if (candidate.slides.length !== base.slides.length) errors.push('Verifier mengubah jumlah slide.');
  const requestedNorm = normalize(manualTopic); const maps = sourceMap(sources);
  candidate.slides.forEach((slide, index) => {
    const baseSlide = base.slides[index]; if (!baseSlide) return;
    if (String(slide.section || '').trim() !== String(baseSlide.section || '').trim()) errors.push(`Slide ${index + 1}: section berubah.`);
    if (!String(slide.title || '').trim()) errors.push(`Slide ${index + 1}: title kosong.`);
    if (!String(slide.body || '').trim() && !(slide.points || []).length) errors.push(`Slide ${index + 1}: tidak memiliki isi bermakna.`);
    if (requestedNorm && normalize(slide.title) === requestedNorm) errors.push(`Slide ${index + 1}: requestedTopic dipakai mentah sebagai judul.`);
    for (const field of slideFields(slide, index)) if (field.value && likelyEnglishDisplayText(field.value)) errors.push(`${field.key}: copy tampil harus Bahasa Indonesia.`);
    const rendered = `${slide.title || ''} ${slide.body || ''} ${(slide.points || []).join(' ')}`;
    if (/lanjut\s+baca\s+tentang/i.test(rendered)) errors.push(`Slide ${index + 1}: memakai filler "Lanjut baca tentang".`);
    if (BOILERPLATE.test(rendered)) errors.push(`Slide ${index + 1}: metadata/boilerplate website masuk ke konten.`);
  });
  errors.push(...validateManualTopicIdentity(manualTopic, candidate.slides)); recoverMissingClaims(candidate, sources, format);
  const claims = normalizeClaims(candidate.slides); const claimByField = new Map(); const verifiedClaimFields = new Set();
  for (const claim of claims) {
    let validClaim = true;
    if (!claim.field || !claim.text || !claim.sourceId || !claim.evidence) { errors.push('Claim verifier tidak lengkap.'); continue; }
    if (!maps.has(claim.sourceId)) { errors.push(`Claim memakai sourceId yang tidak tersedia: ${claim.sourceId}.`); validClaim = false; }
    const evidenceNorm = normalize(claim.evidence);
    if (!evidenceNorm || !maps.get(claim.sourceId)?.includes(evidenceNorm)) { errors.push(`Evidence tidak ditemukan pada ${claim.sourceId}.`); validClaim = false; }
    if (words(claim.evidence).length < 4 || words(claim.evidence).length > 32) { errors.push('Evidence harus 4–32 kata.'); validClaim = false; }
    const claimNumbers = numericTokens(claim.text); const evidenceNumbers = new Set(numericTokens(claim.evidence));
    if (!claimNumbers.every(number => evidenceNumbers.has(number))) { errors.push(`Angka pada claim tidak didukung evidence: ${claim.text}.`); validClaim = false; }
    if (claimByField.has(claim.field)) { errors.push(`Field ${claim.field} memiliki claim ganda.`); validClaim = false; }
    claimByField.set(claim.field, claim); if (validClaim) verifiedClaimFields.add(claim.field);
  }
  const totalSlides = candidate.slides.length;
  candidate.slides.forEach((slide, slideIndex) => { for (const field of slideFields(slide, slideIndex)) {
    if (!field.value) continue; const needsEvidence = requiresSourceEvidence(field.value, slide.section, field.kind, slideIndex, totalSlides, format); const claim = claimByField.get(field.key);
    if (needsEvidence && !claim) errors.push(`${field.key}: klaim faktual tidak memiliki evidence.`);
    if (claim && normalize(claim.text) !== normalize(field.value)) errors.push(`${field.key}: claim.text tidak sama dengan copy field.`);
  }});
  errors.push(...validateSlideTopicRelevance(manualTopic, candidate.slides, verifiedClaimFields));
  const verified = { ...base, slides: candidate.slides, verificationStatus: 'source_based', unsupportedClaims: [] };
  const first = verified.slides[0]; const informative = verified.slides.find(slide => String(slide.body || '').trim() || (slide.points || []).length) || first; const last = verified.slides.at(-1);
  verified.hook = String(first?.title || base.hook || '').trim(); verified.body = String(informative?.body || informative?.points?.join(' ') || base.body || '').trim(); verified.caption = verified.body; verified.cta = String(last?.title || base.cta || '').trim();
  if (contentService?.validateContent) errors.push(...contentService.validateContent(verified, { format, manualTopic: '', validateCopy: false }));
  return { errors: [...new Set(errors)], content: verified };
}

function dropUnsupportedPointClaims(content, semanticErrors = []) {
  if (!content || !Array.isArray(content.slides) || !Array.isArray(semanticErrors)) return null;
  const targets = semanticErrors.map(error => { const match = String(error || '').match(/SEMANTIC_SUPPORT:\s+slide:(\d+):point:(\d+)\b/); return match ? { slideIndex: Number(match[1]), pointIndex: Number(match[2]) } : null; }).filter(Boolean);
  if (!targets.length) return null;
  const slides = content.slides.map(slide => ({ ...slide, points: Array.isArray(slide?.points) ? [...slide.points] : [], claims: Array.isArray(slide?.claims) ? slide.claims.map(claim => ({ ...claim })) : [] }));
  let changed = false; const grouped = new Map();
  for (const target of targets) { if (!grouped.has(target.slideIndex)) grouped.set(target.slideIndex, new Set()); grouped.get(target.slideIndex).add(target.pointIndex); }
  for (const [slideIndex, pointIndexes] of grouped) {
    const slide = slides[slideIndex]; if (!slide) continue;
    for (const pointIndex of [...pointIndexes].sort((a, b) => b - a)) {
      if (pointIndex < 0 || pointIndex >= slide.points.length) continue;
      if (!String(slide.body || '').trim() && slide.points.length <= 1) continue;
      slide.points.splice(pointIndex, 1);
      slide.claims = slide.claims.flatMap(claim => { const match = String(claim?.field || '').match(new RegExp(`^slide:${slideIndex}:point:(\\d+)$`)); if (!match) return [claim]; const i = Number(match[1]); if (i === pointIndex) return []; return i > pointIndex ? [{ ...claim, field: `slide:${slideIndex}:point:${i - 1}` }] : [claim]; });
      changed = true;
    }
  }
  return changed ? { ...content, slides } : null;
}

function semanticAuditPrompt(content, topic) {
  const claims = normalizeClaims(content?.slides || []).map(({ field, text, sourceId, evidence }) => ({ field, text, sourceId, evidence }));
  const slides = (content?.slides || []).map((slide, index) => ({ index, section: slide?.section || '', title: slide?.title || '', body: slide?.body || '', points: slide?.points || [] }));
  return `Anda auditor entailment dan koherensi carousel bilingual Indonesia-Inggris. Gunakan HANYA SLIDES dan pasangan claim.text/evidence yang diberikan. Jangan memakai pengetahuan luar.\n\nTOPIK UTAMA: ${JSON.stringify(topic || '')}\nSLIDES: ${JSON.stringify(slides)}\nCLAIMS: ${JSON.stringify(claims)}\n\nUntuk setiap claim, tandai unsupported bila salah satu berlaku:\n1. evidence tidak menyatakan makna yang sama dengan claim.text;\n2. claim menambahkan tujuan, sebab-akibat, manfaat, aplikasi, risiko, keselamatan, masa depan, atau kesimpulan yang tidak dinyatakan evidence;\n3. claim bertentangan dengan evidence;\n4. claim mungkin benar secara umum tetapi evidence yang dipasangkan tidak membuktikannya;\n5. claim/evidence menyimpang jauh dari TOPIK UTAMA atau hanya mengambil side-note artikel;\n6. pada alur masalah-solusi, sebuah solusi/tips tidak benar-benar menjawab masalah yang dijelaskan sebelumnya, walaupun keduanya secara terpisah ada di sumber; tandai field solusi/tips itu unsupported;\n7. sebuah hasil/manfaat tidak merupakan konsekuensi yang didukung dari solusi sebelumnya; tandai field hasil/manfaat itu unsupported;\n8. title, body, dan points dalam slide membahas objek/masalah berbeda sehingga maknanya tidak nyambung; tandai field substantif yang menyimpang.\n\nJangan menolak hanya karena beda bahasa. Parafrase Indonesia dianggap supported jika maknanya setia. Fokus pada hubungan makna, bukan kemiripan kata.\nKembalikan HANYA JSON {"unsupported":[{"field":"slide:0:body","reason":"alasan singkat"}]}. Jika semua didukung dan koheren, kembalikan {"unsupported":[]}.`;
}

async function auditClaimSemantics(openai, content, topic) {
  const claims = normalizeClaims(content?.slides || []); if (!claims.length) return [];
  const response = await openai.chat.completions.create({ model: config.aiModel, messages: [
    { role: 'system', content: 'Anda auditor fakta dan koherensi ketat. Evidence harus mendukung arti claim, dan hubungan masalah-solusi-hasil harus benar-benar nyambung.' },
    { role: 'user', content: semanticAuditPrompt(content, topic) }
  ], response_format: { type: 'json_object' } });
  let parsed; try { parsed = parseJsonResponse(response); } catch (error) { return [`SEMANTIC_SUPPORT: audit tidak mengembalikan JSON valid: ${error.message}`]; }
  if (!Array.isArray(parsed.unsupported)) return ['SEMANTIC_SUPPORT: audit tidak mengembalikan array unsupported.'];
  const known = new Set(claims.map(claim => claim.field));
  return parsed.unsupported.filter(item => item?.field && known.has(String(item.field))).map(item => `SEMANTIC_SUPPORT: ${String(item.field)} tidak didukung evidence: ${String(item.reason || 'makna claim melampaui evidence')}`);
}

function verifierPrompt({ base, draft = base, bank, topic, format, errors = [] }) {
  const totalSlides = draft?.slides?.length || base?.slides?.length || 0;
  const requiredClaimFields = (draft?.slides || []).flatMap((slide, slideIndex) => slideFields(slide, slideIndex).filter(field => field.value && requiresSourceEvidence(field.value, slide.section, field.kind, slideIndex, totalSlides, format)).map(field => ({ field: field.key, text: field.value })));
  const factFormatRules = String(format || '').toLocaleLowerCase('id-ID') === 'fakta singkat' ? '- FORMAT FAKTA SINGKAT: section sudah dikunci sebagai label netral fakta. Dilarang mengubahnya menjadi MASALAH, PENYEBAB, SOLUSI, HASIL, TUTORIAL, atau LANGKAH. Jangan memaksa alur sebab-solusi-hasil.' : '';
  const problemSolutionRule = String(format || '').toLocaleLowerCase('id-ID') === 'masalah dan solusi' ? '- FORMAT MASALAH DAN SOLUSI: semua masalah, solusi, tips, rekomendasi, dan instruksi konkret wajib didukung FACT_BANK. Setiap SOLUSI harus langsung menjawab MASALAH yang dibahas, dan HASIL harus benar-benar mengikuti solusi berdasarkan sumber. Jangan mencampur masalah A dengan solusi B hanya karena keduanya ada di artikel.' : '';
  return `Anda adalah FILTER/VERIFIER fakta untuk carousel Indonesia. Anda BUKAN pembuat struktur carousel baru.\n\nTOPIK REFERENSI: ${JSON.stringify(topic || '')}\nFORMAT: ${JSON.stringify(format || '')}\nFIELD SUBSTANTIF YANG WAJIB PUNYA CLAIM: ${JSON.stringify(requiredClaimFields)}\n\nATURAN WAJIB:\n- Pertahankan JUMLAH slide, URUTAN slide, dan SECTION persis seperti ORIGINAL_CONTENT.\n${factFormatRules}\n${problemSolutionRule}\n- requestedTopic hanya referensi; jangan jadikan judul mentah.\n- Pertahankan identitas objek utama dan gaya natural ORIGINAL_CONTENT.\n- Setiap slide harus berada pada inti TOPIK dan FACT_BANK; jangan ambil side-note hanya karena faktanya benar.\n- Jangan memperkenalkan tutorial, tool, workflow, strategi, atau saran yang tidak ada di sumber.\n- COPY TAMPIL wajib Bahasa Indonesia natural, seperti manusia menjelaskan dengan ringkas; hindari kalimat kaku, terjemahan literal, jargon tak perlu, dan pengulangan ide.\n- Rapikan hierarki teks: title = satu ide utama singkat; body = penjelasan inti; points = detail pendukung. Jangan menaruh ide berbeda yang saling berebut dalam satu slide.\n- Title, body, dan points pada slide yang sama wajib membahas objek/masalah yang sama dan saling melengkapi.\n- Pada Masalah dan solusi, cek hubungan antarslide: MASALAH → penyebab/konteks → SOLUSI → HASIL harus logis dan didukung sumber. Jika sumber tidak menghubungkan dua hal, jangan hubungkan sendiri.\n- Evidence dalam claims wajib kutipan asli FACT_BANK; jangan diterjemahkan.\n- Semua copy substantif format Masalah dan solusi wajib punya claim. Perintah/tips tetap wajib evidence.\n- Evidence harus MEMBUKTIKAN ARTI claim.text, bukan sekadar punya kata mirip.\n- Satu claim hanya satu sourceId/evidence; jangan gabungkan sumber menjadi kesimpulan baru.\n- Jika copy tidak didukung, ubah hanya copy itu ke fakta terdekat yang didukung. Jangan mengarang.\n- Hook/pertanyaan/transisi/CTA netral boleh tanpa claim jika tidak faktual.\n- BATAS COPY: title maks 12 kata; body maks 24 kata; points maks 3; tiap point maks 7 kata.\n- Jika SEMANTIC_SUPPORT muncul, perbaiki FIELD PERSIS itu dengan evidence yang relevan. Jika point tak punya dukungan, hapus point.\n- Dilarang filler, metadata website, byline, newsletter, judul topik mentah, atau "Lanjut baca tentang ...".\n- Jangan mengubah hashtag, focus, metadata angle/tool, atau struktur di luar slides.\n- Jangan membuat angka/nama/tanggal/manfaat/sebab-akibat baru.\n\nField claim: slide:<index>:title | slide:<index>:body | slide:<index>:point:<pointIndex>. claim.text harus sama persis dengan copy field.\n\nFACT_BANK: ${JSON.stringify(bank)}\nORIGINAL_STRUCTURE: ${JSON.stringify((base?.slides || []).map(slide => ({ section: slide.section })))}\nCURRENT_DRAFT: ${JSON.stringify(draft)}\n${errors.length ? `ERROR SEBELUMNYA:\n- ${errors.join('\n- ')}` : ''}\n\nKembalikan HANYA JSON: {"slides":[{"section":"...","title":"...","body":"...","points":[],"claims":[{"field":"slide:0:body","text":"...","sourceId":"source-1","evidence":"..."}]}]}`;
}

function parseJsonResponse(response) { const raw = response?.choices?.[0]?.message?.content; if (!raw) throw new Error('Verifier sumber tidak mengembalikan konten.'); return JSON.parse(raw); }

async function generateFilteredContent({ content, previousTopics = [], options = {}, sources = [], client }) {
  let base = await content.generateContent(previousTopics, { ...options, useSources: false, skipCopyValidation: true, skipManualTopicValidation: true, sourceContext: '', sources: [] }, client);
  if (!Array.isArray(base?.slides) || !base.slides.length) throw Object.assign(new Error('Konten normal tidak memiliki slide terstruktur untuk diverifikasi sumber.'), { status: 422 });
  base = { ...base, slides: normalizeFactSections(base.slides, options.contentFormat) };
  const topic = options.requestedTopic || options.mainTopic || base.topic || ''; const bank = extractFactBank(sources, topic);
  if (!bank.length) throw Object.assign(new Error('Sumber tidak memiliki fakta yang layak untuk memverifikasi konten.'), { status: 422 });
  const openai = client || new OpenAI({ apiKey: config.aiApiKey, baseURL: config.aiBaseUrl }); let errors = []; let draft = base;
  for (let attempt = 1; attempt <= MAX_VERIFY_ATTEMPTS; attempt += 1) {
    const response = await openai.chat.completions.create({ model: config.aiModel, messages: [
      { role: 'system', content: 'Anda memfilter fakta dan koherensi carousel. Sumber hanya untuk verifikasi; jangan mengganti struktur.' },
      { role: 'user', content: verifierPrompt({ base, draft, bank, topic, format: options.contentFormat, errors }) }
    ], response_format: { type: 'json_object' } });
    let candidate; try { candidate = parseJsonResponse(response); } catch (error) { errors = [`JSON verifier tidak valid: ${error.message}`]; continue; }
    const checked = validateVerifiedContent(base, candidate, { contentService: content, format: options.contentFormat, manualTopic: options.topicSource === 'manual' ? options.requestedTopic : '', sources });
    if (!checked.errors.length) {
      const semanticReady = pruneUnneededClaims(checked.content, options.contentFormat); const semanticErrors = await auditClaimSemantics(openai, semanticReady, topic);
      if (!semanticErrors.length) return checked.content;
      const reduced = dropUnsupportedPointClaims(checked.content, semanticErrors);
      if (reduced) {
        const reducedChecked = validateVerifiedContent(base, { slides: reduced.slides }, { contentService: content, format: options.contentFormat, manualTopic: options.topicSource === 'manual' ? options.requestedTopic : '', sources });
        if (!reducedChecked.errors.length) {
          const remainingSemanticErrors = await auditClaimSemantics(openai, reducedChecked.content, topic);
          if (!remainingSemanticErrors.length) return reducedChecked.content;
          errors = remainingSemanticErrors; draft = { ...base, slides: reducedChecked.content.slides }; continue;
        }
      }
      errors = semanticErrors; draft = { ...base, slides: checked.content.slides }; continue;
    }
    errors = checked.errors; draft = { ...base, slides: Array.isArray(candidate.slides) ? candidate.slides : draft.slides };
  }
  throw Object.assign(new Error(`Konten tidak lolos filter fakta sumber: ${errors[0] || 'verifikasi gagal'}`), { status: 422, validationErrors: errors });
}

module.exports = { generateFilteredContent, extractFactBank, requiresEvidence, requiresSourceEvidence, validateVerifiedContent, validateManualTopicIdentity, validateSlideTopicRelevance, topicRelevanceTerms, topicEntityTokens, evidenceCandidates, recoverMissingClaims, evidenceSupport, likelyEnglishDisplayText, normalizeFactSections, auditClaimSemantics, dropUnsupportedPointClaims, pruneUnneededClaims, MAX_VERIFY_ATTEMPTS };
