const OpenAI = require('openai');
const config = require('../config');

const MAX_FACTS = 36;
const MAX_VERIFY_ATTEMPTS = 3;
const TOPIC_STOPWORDS = new Set(['yang', 'dan', 'atau', 'dari', 'untuk', 'dengan', 'tentang', 'cara', 'adalah', 'pada', 'itu', 'ini', 'sebagai']);
const GROUNDING_STOPWORDS = new Set([
  ...TOPIC_STOPWORDS,
  'ai', 'api', 'gpt', 'agar', 'karena', 'saat', 'ketika', 'oleh', 'dalam', 'lebih', 'juga', 'akan',
  'bisa', 'dapat', 'sebelum', 'setelah', 'mereka', 'kami', 'kamu', 'anda', 'tersebut', 'sebuah',
  'para', 'jadi', 'menggunakan', 'digunakan', 'dipakai', 'membantu', 'memungkinkan', 'mendukung',
  'memiliki', 'menjadi', 'termasuk', 'hadir'
]);
const NEGATION_TOKENS = new Set(['tidak', 'bukan', 'belum', 'tanpa']);
const GENERIC_ENTITY_TOKENS = new Set(['ai', 'api', 'gpt']);
const BOILERPLATE = /(?:cookie|privacy|privasi|terms of use|syarat dan ketentuan|copyright|hak cipta|newsletter|subscribe|follow\s+(?:me|us)|ikuti kami|sign in|login|contact us|hubungi kami|(?:author|writer|contributor)\s+(?:bio|profile)|about the author|tentang penulis|voice experience.*generated by ai|audio.*generated by ai|^(?:by|oleh|written by|ditulis oleh|edited by|disunting oleh)\s+[\p{L}.' -]{3,80}[.!]?$)/iu;
const FACT_VERBS = /\b(?:adalah|merupakan|memiliki|menggunakan|digunakan|dipakai|meluncurkan|diluncurkan|merilis|dirilis|menawarkan|menyebut|mengatakan|menurut|menunjukkan|menemukan|mengungkap|mengumumkan|melaporkan|menyatakan|menjelaskan|mencapai|meningkat|menurun|berasal|didirikan|bekerja|mampu|dapat|bisa|membantu|menghasilkan|mengubah|menjadi|termasuk|tersedia|dikembangkan|mencatat|menilai|menganggap|memungkinkan|menggantikan|berpotensi|berisiko|mendukung|hadir)\b/i;
const FACT_MARKERS = /\b(?:risiko|temuan|fitur|kemampuan|resmi|gratis|berbayar|rilis|peluncuran|versi|akurasi|kinerja|statistik|persentase|pengguna|pelanggan|perusahaan|model)\b/i;
const ASSERTIVE_FACT_MARKERS = /\b(?:resmi|gratis|berbayar|rilis|peluncuran|versi|akurasi|kinerja|statistik|persentase)\b/i;
const NON_FACTUAL_START = /^(?:coba|baca|lihat|simpan|cek|pilih|mulai|bandingkan|pertimbangkan|fokus|jelajahi|ikuti|bagikan|tanyakan|pikirkan|perhatikan|gunakan|buat|atur|hindari|pastikan|sesuaikan|tentukan|uji|evaluasi|catat|pelajari)\b/i;

const words = value => String(value || '').trim().split(/\s+/).filter(Boolean);
const normalize = value => String(value || '')
  .toLocaleLowerCase('id-ID')
  .replace(/&nbsp;/gi, ' ')
  .replace(/[^a-z0-9%\s]/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();
const tokens = value => new Set(normalize(value).split(' ').filter(Boolean));

function topicTokens(value) {
  return [...tokens(value)].filter(token => (token.length > 2 || token === 'ai') && !TOPIC_STOPWORDS.has(token));
}

function topicEntityTokens(value) {
  const raw = String(value || '').match(/[A-Za-z0-9][A-Za-z0-9.-]*/g) || [];
  const strong = new Set();
  raw.forEach((token, index) => {
    const acronym = /^[A-Z0-9]{2,}$/.test(token);
    const internalCapital = /[a-z][A-Z]/.test(token);
    if (acronym || internalCapital) strong.add(normalize(token));

    const currentTitle = /^[A-Z][a-z0-9.-]+$/.test(token);
    const next = raw[index + 1];
    const nextTitle = next && /^[A-Z][a-z0-9.-]+$/.test(next);
    if (currentTitle && nextTitle) {
      strong.add(normalize(token));
      strong.add(normalize(next));
    }
  });
  return [...strong].filter(Boolean);
}

function evidenceCandidates(text) {
  const sentences = String(text || '').replace(/\s+/g, ' ').trim().split(/(?<=[.!?])\s+/);
  return sentences.flatMap(sentence => {
    const clean = sentence.trim();
    if (!clean || BOILERPLATE.test(clean)) return [];
    if (words(clean).length >= 4 && words(clean).length <= 32) return [clean];
    return clean.split(/(?<=[;:])\s+|\s+[—–]\s+|,\s+(?=(?:while|but|however|sedangkan|sementara|tetapi|namun|dan)\s+)/i)
      .map(value => value.trim())
      .filter(value => words(value).length >= 4 && words(value).length <= 32 && !BOILERPLATE.test(value));
  });
}

function extractFactBank(sources = [], topic = '') {
  const wanted = topicTokens(topic);
  const perSource = sources.map((source, sourceIndex) => {
    const seen = new Set();
    return evidenceCandidates(source?.text).map((evidence, order) => {
      const normalized = normalize(evidence);
      if (!normalized || seen.has(normalized)) return null;
      seen.add(normalized);
      const evidenceTokens = tokens(evidence);
      const overlap = wanted.filter(token => evidenceTokens.has(token)).length;
      return {
        sourceId: `source-${sourceIndex + 1}`,
        evidence,
        score: overlap * 100 - order,
        order
      };
    }).filter(Boolean).sort((a, b) => b.score - a.score || a.order - b.order);
  });

  const bank = [];
  const seenEvidence = new Set();
  while (bank.length < MAX_FACTS && perSource.some(queue => queue.length)) {
    for (const queue of perSource) {
      const fact = queue.shift();
      if (!fact) continue;
      const key = normalize(fact.evidence);
      if (!seenEvidence.has(key)) {
        seenEvidence.add(key);
        bank.push({ sourceId: fact.sourceId, evidence: fact.evidence });
      }
      if (bank.length >= MAX_FACTS) break;
    }
  }
  return bank;
}

function numericTokens(value) {
  return String(value || '').match(/\b\d+(?:[.,]\d+)?%?\b/g) || [];
}

function isQuestion(value) {
  return /\?\s*$/.test(String(value || '').trim());
}

function requiresEvidence(value, section = '', kind = 'body') {
  const text = String(value || '').trim();
  if (!text) return false;
  if (numericTokens(text).length) return true;
  if (/\b(?:rp|usd|dolar|persen|tahun|bulan|hari|jam|menit|juta|miliar|triliun)\b/i.test(text)) return true;

  // Commands, advice, CTAs and questions are not factual assertions by
  // themselves. This prevents listicle instructions such as "Gunakan AI untuk
  // membantu ..." from being rejected merely because they contain a factual
  // verb elsewhere in the sentence.
  if (NON_FACTUAL_START.test(text)) return false;
  if (isQuestion(text)) return false;

  if (FACT_VERBS.test(text)) return true;
  // A short point such as "Fitur AI untuk riset" is a label, while stronger
  // markers such as "resmi/rilis/akurasi" still assert a fact and need proof.
  if (kind === 'point') return ASSERTIVE_FACT_MARKERS.test(text);
  if (FACT_MARKERS.test(text)) return true;
  return false;
}

function slideFields(slide, slideIndex) {
  const fields = [
    { key: `slide:${slideIndex}:title`, value: String(slide?.title || '').trim(), kind: 'title' },
    { key: `slide:${slideIndex}:body`, value: String(slide?.body || '').trim(), kind: 'body' }
  ];
  (slide?.points || []).forEach((point, pointIndex) => fields.push({
    key: `slide:${slideIndex}:point:${pointIndex}`,
    value: String(point || '').trim(),
    kind: 'point'
  }));
  return fields;
}

function sourceMap(sources = []) {
  return new Map(sources.map((source, index) => [`source-${index + 1}`, normalize(source?.text || '')]));
}

function normalizeClaims(slides = []) {
  return slides.flatMap((slide, slideIndex) => (Array.isArray(slide?.claims) ? slide.claims : []).map(claim => ({
    slideIndex,
    field: String(claim?.field || '').trim(),
    text: String(claim?.text || '').trim(),
    sourceId: String(claim?.sourceId || '').trim(),
    evidence: String(claim?.evidence || '').trim()
  })));
}

function groundingTerms(value) {
  return [...tokens(value)].filter(token => (token.length > 2 || token === 'ai') && !GROUNDING_STOPWORDS.has(token));
}

function evidenceSupport(text, evidence) {
  const textNorm = normalize(text);
  const evidenceNorm = normalize(evidence);
  if (!textNorm || !evidenceNorm) return { exact: false, matches: 0, total: 0, score: 0 };

  const claimNumbers = numericTokens(text);
  const evidenceNumbers = new Set(numericTokens(evidence));
  if (!claimNumbers.every(number => evidenceNumbers.has(number))) {
    return { exact: false, matches: 0, total: 0, score: 0 };
  }

  const claimNegations = [...tokens(text)].filter(token => NEGATION_TOKENS.has(token));
  const evidenceTokenSet = tokens(evidence);
  if (claimNegations.some(token => !evidenceTokenSet.has(token))) {
    return { exact: false, matches: 0, total: 0, score: 0 };
  }

  const exact = evidenceNorm.includes(textNorm);
  const terms = groundingTerms(text);
  const matches = terms.filter(token => evidenceTokenSet.has(token)).length;
  const score = terms.length ? matches / terms.length : 0;
  return { exact, matches, total: terms.length, score };
}

function recoverMissingClaims(candidate, sources = []) {
  if (!candidate || !Array.isArray(candidate.slides)) return candidate;
  const existing = new Set(normalizeClaims(candidate.slides).map(claim => claim.field).filter(Boolean));
  const evidence = sources.flatMap((source, index) => evidenceCandidates(source?.text).map(item => ({
    sourceId: `source-${index + 1}`,
    evidence: item
  })));

  candidate.slides.forEach((slide, slideIndex) => {
    for (const field of slideFields(slide, slideIndex)) {
      if (!field.value || existing.has(field.key) || !requiresEvidence(field.value, slide.section, field.kind)) continue;

      let best = null;
      for (const item of evidence) {
        const support = evidenceSupport(field.value, item.evidence);
        const acceptable = support.exact || (support.total >= 3 && support.matches >= 3 && support.score >= 0.8);
        if (!acceptable) continue;
        if (!best || Number(support.exact) > Number(best.support.exact) || support.score > best.support.score) {
          best = { item, support };
        }
      }

      if (!best) continue;
      if (!Array.isArray(slide.claims)) slide.claims = [];
      slide.claims.push({
        field: field.key,
        text: field.value,
        sourceId: best.item.sourceId,
        evidence: best.item.evidence
      });
      existing.add(field.key);
    }
  });
  return candidate;
}

function validateManualTopicIdentity(manualTopic, slides = []) {
  const anchors = topicEntityTokens(manualTopic);
  if (!anchors.length) return [];

  // Generic acronyms such as AI/API/GPT are weak identity signals. When a
  // specific multi-token name/product is present, accepting one specific token
  // avoids false rejection of natural shorthand such as "Google Maps" ->
  // "Maps", while still rejecting a carousel that loses the identity entirely.
  const specific = anchors.filter(anchor => !GENERIC_ENTITY_TOKENS.has(anchor));
  const required = specific.length ? specific : anchors;
  const carouselTokens = tokens(slides.map(slide => `${slide?.title || ''} ${slide?.body || ''} ${(slide?.points || []).join(' ')}`).join(' '));
  if (required.some(anchor => carouselTokens.has(anchor))) return [];
  return [`Isi carousel kehilangan objek utama topik manual: ${required.join(' / ')}.`];
}

function validateVerifiedContent(base, candidate, { contentService, format, manualTopic, sources }) {
  const errors = [];
  if (!candidate || !Array.isArray(candidate.slides)) return ['Verifier tidak mengembalikan slides.'];
  if (candidate.slides.length !== base.slides.length) errors.push('Verifier mengubah jumlah slide.');

  const requestedNorm = normalize(manualTopic);
  const maps = sourceMap(sources);
  candidate.slides.forEach((slide, index) => {
    const baseSlide = base.slides[index];
    if (!baseSlide) return;
    if (String(slide.section || '').trim() !== String(baseSlide.section || '').trim()) errors.push(`Slide ${index + 1}: section berubah.`);
    if (!String(slide.title || '').trim()) errors.push(`Slide ${index + 1}: title kosong.`);
    if (!String(slide.body || '').trim() && !(slide.points || []).length) errors.push(`Slide ${index + 1}: tidak memiliki isi bermakna.`);
    if (requestedNorm && normalize(slide.title) === requestedNorm) errors.push(`Slide ${index + 1}: requestedTopic dipakai mentah sebagai judul.`);
    const rendered = `${slide.title || ''} ${slide.body || ''} ${(slide.points || []).join(' ')}`;
    if (/lanjut\s+baca\s+tentang/i.test(rendered)) errors.push(`Slide ${index + 1}: memakai filler "Lanjut baca tentang".`);
    if (BOILERPLATE.test(rendered)) errors.push(`Slide ${index + 1}: metadata/boilerplate website masuk ke konten.`);
  });
  errors.push(...validateManualTopicIdentity(manualTopic, candidate.slides));

  // If the verifier omitted a claim that is already stated almost verbatim in
  // the supplied source, recover it deterministically. The threshold is kept
  // deliberately strict; weak lexical similarity never converts unsupported
  // copy into a verified claim.
  recoverMissingClaims(candidate, sources);

  const claims = normalizeClaims(candidate.slides);
  const claimByField = new Map();
  for (const claim of claims) {
    if (!claim.field || !claim.text || !claim.sourceId || !claim.evidence) {
      errors.push('Claim verifier tidak lengkap.');
      continue;
    }
    if (!maps.has(claim.sourceId)) {
      errors.push(`Claim memakai sourceId yang tidak tersedia: ${claim.sourceId}.`);
      continue;
    }
    const evidenceNorm = normalize(claim.evidence);
    if (!evidenceNorm || !maps.get(claim.sourceId).includes(evidenceNorm)) {
      errors.push(`Evidence tidak ditemukan pada ${claim.sourceId}.`);
      continue;
    }
    if (words(claim.evidence).length < 4 || words(claim.evidence).length > 32) errors.push('Evidence harus 4–32 kata.');
    const claimNumbers = numericTokens(claim.text);
    const evidenceNumbers = new Set(numericTokens(claim.evidence));
    if (!claimNumbers.every(number => evidenceNumbers.has(number))) errors.push(`Angka pada claim tidak didukung evidence: ${claim.text}.`);
    if (claimByField.has(claim.field)) errors.push(`Field ${claim.field} memiliki claim ganda.`);
    claimByField.set(claim.field, claim);
  }

  candidate.slides.forEach((slide, slideIndex) => {
    for (const field of slideFields(slide, slideIndex)) {
      if (!field.value) continue;
      const needsEvidence = requiresEvidence(field.value, slide.section, field.kind);
      const claim = claimByField.get(field.key);
      if (needsEvidence && !claim) errors.push(`${field.key}: klaim faktual tidak memiliki evidence.`);
      if (claim && normalize(claim.text) !== normalize(field.value)) errors.push(`${field.key}: claim.text tidak sama dengan copy field.`);
    }
  });

  const verified = {
    ...base,
    slides: candidate.slides,
    verificationStatus: 'source_based',
    unsupportedClaims: []
  };
  const first = verified.slides[0];
  const informative = verified.slides.find(slide => String(slide.body || '').trim() || (slide.points || []).length) || first;
  const last = verified.slides.at(-1);
  verified.hook = String(first?.title || base.hook || '').trim();
  verified.body = String(informative?.body || informative?.points?.join(' ') || base.body || '').trim();
  verified.caption = verified.body;
  verified.cta = String(last?.title || base.cta || '').trim();

  if (contentService?.validateContent) {
    // Source mode has its own entity-aware topic check above. Do not re-run the
    // older literal word-overlap gate, which rejects valid paraphrases.
    errors.push(...contentService.validateContent(verified, { format, manualTopic: '', validateCopy: false }));
  }
  return { errors: [...new Set(errors)], content: verified };
}

function verifierPrompt({ base, bank, topic, format, errors = [] }) {
  return `Anda adalah FILTER/VERIFIER fakta untuk carousel Indonesia. Anda BUKAN pembuat struktur carousel baru.

TOPIK REFERENSI: ${JSON.stringify(topic || '')}
FORMAT: ${JSON.stringify(format || '')}

ATURAN WAJIB:
- Pertahankan JUMLAH slide, URUTAN slide, dan SECTION persis seperti ORIGINAL_CONTENT.
- requestedTopic hanya referensi topik. Jangan menjadikannya judul mentah.
- Jika topik menyebut nama orang, produk, model, atau perusahaan, identitas itu harus tetap muncul secara natural dalam carousel.
- Pertahankan gaya natural ORIGINAL_CONTENT sebanyak mungkin.
- Source hanya untuk FILTER/VERIFIKASI fakta, bukan untuk menentukan struktur atau jumlah slide.
- Jangan menambah URL/sumber apa pun.
- Untuk copy faktual yang tetap dipakai, sertakan claim dengan sourceId + evidence PERSIS dari FACT_BANK.
- AUDIT SETIAP title, body, dan point sebelum mengembalikan JSON: semua pernyataan faktual wajib punya claim; saran/CTA/instruksi non-faktual tidak perlu claim.
- Satu claim hanya boleh memakai satu sourceId/evidence. Jangan gabungkan beberapa sumber menjadi kesimpulan baru.
- Jika fakta ORIGINAL_CONTENT tidak didukung, ubah hanya copy faktual itu menjadi fakta terdekat yang benar-benar didukung, atau menjadi copy non-faktual yang tetap berguna. Jangan mengarang.
- Hook, pertanyaan, transisi, CTA, saran, dan instruksi non-faktual boleh tanpa claim.
- Jangan memberi claim pada copy yang sebenarnya hanya saran/CTA jika tidak ada fakta di dalamnya.
- Setiap slide wajib tetap memiliki title dan minimal body atau points yang bermakna.
- Title, body, dan points dalam satu slide harus saling melengkapi. Jangan mengulang kalimat atau ide yang sama di field berbeda.
- Dilarang slide kosong, filler, metadata website, byline/contributor/newsletter, judul hanya topik mentah, atau "Lanjut baca tentang ...".
- Jangan mengubah hashtag, focus, metadata angle/tool, atau struktur di luar slides.
- Jangan membuat angka/nama/tanggal/manfaat/sebab-akibat baru.

Untuk setiap claim gunakan field key persis:
slide:<index>:title
slide:<index>:body
slide:<index>:point:<pointIndex>
index dimulai dari 0.
claim.text harus sama persis dengan copy field yang didukung.

FACT_BANK (hanya dari URL yang diberikan user):
${JSON.stringify(bank)}

ORIGINAL_CONTENT:
${JSON.stringify(base)}
${errors.length ? `\nERROR VERIFIKASI SEBELUMNYA YANG HARUS DIPERBAIKI:\n- ${errors.join('\n- ')}` : ''}

Kembalikan HANYA JSON:
{"slides":[{"section":"...","title":"...","body":"...","points":[],"claims":[{"field":"slide:0:body","text":"...","sourceId":"source-1","evidence":"..."}]}]}`;
}

function parseJsonResponse(response) {
  const raw = response?.choices?.[0]?.message?.content;
  if (!raw) throw new Error('Verifier sumber tidak mengembalikan konten.');
  return JSON.parse(raw);
}

async function generateFilteredContent({ content, previousTopics = [], options = {}, sources = [], client }) {
  // The legacy manual-topic validator is a literal token-overlap gate. Keep the
  // requested topic in generation, but let the source verifier perform the
  // entity-aware final topic check instead of that older hard gate.
  const baseTopicSource = options.topicSource === 'manual' ? 'trending' : options.topicSource;
  const base = await content.generateContent(previousTopics, {
    ...options,
    topicSource: baseTopicSource,
    useSources: false,
    skipCopyValidation: true,
    sourceContext: '',
    sources: []
  }, client);

  if (!Array.isArray(base?.slides) || !base.slides.length) {
    throw Object.assign(new Error('Konten normal tidak memiliki slide terstruktur untuk diverifikasi sumber.'), { status: 422 });
  }

  const topic = options.requestedTopic || options.mainTopic || base.topic || '';
  const bank = extractFactBank(sources, topic);
  if (!bank.length) throw Object.assign(new Error('Sumber tidak memiliki fakta yang layak untuk memverifikasi konten.'), { status: 422 });

  const openai = client || new OpenAI({ apiKey: config.aiApiKey, baseURL: config.aiBaseUrl });
  let errors = [];
  for (let attempt = 1; attempt <= MAX_VERIFY_ATTEMPTS; attempt += 1) {
    const response = await openai.chat.completions.create({
      model: config.aiModel,
      messages: [
        { role: 'system', content: 'Anda memfilter fakta carousel. Sumber hanya untuk verifikasi fakta; jangan mengganti struktur konten.' },
        { role: 'user', content: verifierPrompt({ base, bank, topic, format: options.contentFormat, errors }) }
      ],
      response_format: { type: 'json_object' }
    });
    let candidate;
    try { candidate = parseJsonResponse(response); }
    catch (error) { errors = [`JSON verifier tidak valid: ${error.message}`]; continue; }

    const checked = validateVerifiedContent(base, candidate, {
      contentService: content,
      format: options.contentFormat,
      manualTopic: options.topicSource === 'manual' ? options.requestedTopic : '',
      sources
    });
    if (!checked.errors.length) return checked.content;
    errors = checked.errors;
  }

  throw Object.assign(new Error(`Konten tidak lolos filter fakta sumber: ${errors[0] || 'verifikasi gagal'}`), {
    status: 422,
    validationErrors: errors
  });
}

module.exports = {
  generateFilteredContent,
  extractFactBank,
  requiresEvidence,
  validateVerifiedContent,
  validateManualTopicIdentity,
  topicEntityTokens,
  evidenceCandidates,
  recoverMissingClaims,
  evidenceSupport,
  MAX_VERIFY_ATTEMPTS
};
