const OpenAI = require('openai');
const config = require('../config');

const MAX_FACTS = 36;
const MAX_VERIFY_ATTEMPTS = 3;
const MAX_SAFE_RECOVERY_ATTEMPTS = 4;
const TOPIC_STOPWORDS = new Set(['yang', 'dan', 'atau', 'dari', 'untuk', 'dengan', 'tentang', 'cara', 'adalah', 'pada', 'itu', 'ini', 'sebagai']);
const GROUNDING_STOPWORDS = new Set([
  ...TOPIC_STOPWORDS,
  'ai', 'api', 'gpt', 'agar', 'karena', 'saat', 'ketika', 'oleh', 'dalam', 'lebih', 'juga', 'akan',
  'bisa', 'dapat', 'sebelum', 'setelah', 'mereka', 'kami', 'kamu', 'anda', 'tersebut', 'sebuah',
  'para', 'jadi', 'menggunakan', 'digunakan', 'dipakai', 'membantu', 'memungkinkan', 'mendukung',
  'memiliki', 'menjadi', 'termasuk', 'hadir'
]);
const NEGATION_TOKENS = new Set(['tidak', 'bukan', 'belum', 'tanpa']);
const GENERIC_ENTITY_TOKENS = new Set(['ai', 'api', 'gpt']);
const TOPIC_RELEVANCE_STOPWORDS = new Set([
  ...TOPIC_STOPWORDS,
  'ai', 'api', 'gpt', 'era', 'digital', 'teknologi', 'semakin', 'maju', 'baru',
  'fitur', 'rilis', 'resmi', 'cara', 'gunakan', 'menggunakan', 'buat', 'bisa', 'dapat'
]);
const NEUTRAL_RELEVANCE_TOKENS = new Set([
  'cek', 'baca', 'lihat', 'simpan', 'bandingkan', 'perhatikan', 'pelajari', 'periksa',
  'konteks', 'sumber', 'temuan', 'detail', 'bagian', 'relevan', 'utama', 'lengkap',
  'kesimpulan', 'menyimpulkan', 'membagikan', 'informasi', 'sebelum', 'setelah',
  'fokus', 'pilih', 'kebutuhan', 'pendekatan'
]);
const BOILERPLATE = /(?:cookie|privacy|privasi|terms of use|syarat dan ketentuan|copyright|hak cipta|newsletter|subscribe|follow\s+(?:me|us)|ikuti kami|sign in|login|contact us|hubungi kami|(?:author|writer|contributor)\s+(?:bio|profile)|about the author|tentang penulis|voice experience.*generated by ai|audio.*generated by ai|^(?:by|oleh|written by|ditulis oleh|edited by|disunting oleh)\s+[\p{L}.' -]{3,80}[.!]?$)/iu;
const FACT_VERBS = /\b(?:adalah|merupakan|memiliki|menggunakan|digunakan|dipakai|meluncurkan|diluncurkan|merilis|dirilis|menawarkan|menyebut|mengatakan|menurut|menunjukkan|menemukan|mengungkap|mengumumkan|melaporkan|menyatakan|menjelaskan|mencapai|meningkat|menurun|berasal|didirikan|bekerja|mampu|dapat|bisa|membantu|menghasilkan|mengubah|menjadi|termasuk|tersedia|dikembangkan|mencatat|menilai|menganggap|memungkinkan|menggantikan|berpotensi|berisiko|mendukung|hadir)\b/i;
const FACT_MARKERS = /\b(?:risiko|temuan|fitur|kemampuan|resmi|gratis|berbayar|rilis|peluncuran|versi|akurasi|kinerja|statistik|persentase|pengguna|pelanggan|perusahaan|model)\b/i;
const ASSERTIVE_FACT_MARKERS = /\b(?:resmi|gratis|berbayar|rilis|peluncuran|versi|akurasi|kinerja|statistik|persentase)\b/i;
const NON_FACTUAL_START = /^(?:coba|baca|lihat|simpan|cek|pilih|mulai|bandingkan|pertimbangkan|fokus|jelajahi|ikuti|bagikan|tanyakan|pikirkan|perhatikan|gunakan|buat|atur|hindari|pastikan|sesuaikan|tentukan|uji|evaluasi|catat|pelajari)\b/i;
const NEUTRAL_SOURCE_COPY = /^(?:cek|baca|lihat|simpan|periksa|pelajari|bandingkan|perhatikan)\s+(?:konteks|sumber|artikel|detail|temuan|informasi|bagian|versi)\b/i;
const ENGLISH_DISPLAY_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'to', 'of', 'in', 'on', 'for', 'with', 'from', 'by',
  'is', 'are', 'was', 'were', 'be', 'been', 'being', 'has', 'have', 'had', 'do', 'does',
  'did', 'not', "don't", "doesn't", 'can', 'could', 'should', 'would', 'will', 'most',
  'about', 'without', 'into', 'that', 'this', 'these', 'those', 'as', 'than', 'which', 'who',
  'when', 'why', 'how'
]);
const INDONESIAN_DISPLAY_WORDS = new Set([
  'yang', 'dan', 'atau', 'untuk', 'dengan', 'dari', 'di', 'pada', 'adalah', 'merupakan',
  'tidak', 'bukan', 'belum', 'bisa', 'dapat', 'akan', 'ini', 'itu', 'agar', 'karena',
  'sebagai', 'tentang', 'sebelum', 'setelah', 'lebih', 'oleh', 'dalam', 'juga', 'saat'
]);

const words = value => String(value || '').trim().split(/\s+/).filter(Boolean);
const normalize = value => String(value || '')
  .toLocaleLowerCase('id-ID')
  .replace(/&nbsp;/gi, ' ')
  .replace(/[^a-z0-9%\s]/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();
const tokens = value => new Set(normalize(value).split(' ').filter(Boolean));

function topicTokens(value) {
  return [...tokens(value)].filter(token => (token.length > 2 || token === 'ai') && !TOPIC_STOPWORDS.has(token));
}

function topicEntityTokens(value) {
  const raw = String(value || '').match(/[A-Za-z0-9][A-Za-z0-9.-]*/g) || [];
  const strong = new Set();
  raw.forEach((token, index) => {
    const acronym = /^[A-Z0-9]{2,}$/.test(token);
    const internalCapital = /[a-z][A-Z]/.test(token);
    if (acronym || internalCapital) strong.add(normalize(token));
    const currentTitle = /^[A-Z][a-z0-9.-]+$/.test(token);
    const next = raw[index + 1];
    const nextTitle = next && /^[A-Z][a-z0-9.-]+$/.test(next);
    if (currentTitle && nextTitle) {
      strong.add(normalize(token));
      strong.add(normalize(next));
    }
  });
  return [...strong].filter(Boolean);
}

function evidenceCandidates(text) {
  const sentences = String(text || '').replace(/\s+/g, ' ').trim().split(/(?<=[.!?])\s+/);
  return sentences.flatMap(sentence => {
    const clean = sentence.trim();
    if (!clean || BOILERPLATE.test(clean)) return [];
    if (words(clean).length >= 4 && words(clean).length <= 32) return [clean];
    return clean.split(/(?<=[;:])\s+|\s+[—–]\s+|,\s+(?=(?:while|but|however|sedangkan|sementara|tetapi|namun|dan)\s+)/i)
      .map(value => value.trim())
      .filter(value => words(value).length >= 4 && words(value).length <= 32 && !BOILERPLATE.test(value));
  });
}

function extractFactBank(sources = [], topic = '') {
  const requested = topicTokens(topic);
  const perSource = sources.map((source, sourceIndex) => {
    const wanted = [...new Set([...requested, ...topicTokens(source?.title || '')])];
    const seen = new Set();
    return evidenceCandidates(source?.text).map((evidence, order) => {
      const normalized = normalize(evidence);
      if (!normalized || seen.has(normalized)) return null;
      seen.add(normalized);
      const evidenceTokens = tokens(evidence);
      const overlap = wanted.filter(token => evidenceTokens.has(token)).length;
      return { sourceId: `source-${sourceIndex + 1}`, evidence, overlap, score: overlap * 100 - order, order };
    }).filter(Boolean).sort((a, b) => b.score - a.score || a.order - b.order);
  });
  const relevantCount = perSource.reduce((sum, queue) => sum + queue.filter(fact => fact.overlap > 0).length, 0);
  const eligible = relevantCount >= 4 ? perSource.map(queue => queue.filter(fact => fact.overlap > 0)) : perSource;
  const bank = [];
  const seenEvidence = new Set();
  while (bank.length < MAX_FACTS && eligible.some(queue => queue.length)) {
    for (const queue of eligible) {
      const fact = queue.shift();
      if (!fact) continue;
      const key = normalize(fact.evidence);
      if (!seenEvidence.has(key)) {
        seenEvidence.add(key);
        bank.push({ sourceId: fact.sourceId, evidence: fact.evidence });
      }
      if (bank.length >= MAX_FACTS) break;
    }
  }
  return bank;
}

function numericTokens(value) {
  return String(value || '').match(/\b\d+(?:[.,]\d+)?%?\b/g) || [];
}

function isQuestion(value) {
  return /\?\s*$/.test(String(value || '').trim());
}

function likelyEnglishDisplayText(value) {
  const displayTokens = String(value || '').toLocaleLowerCase('en-US').match(/[a-z]+(?:'[a-z]+)?/g) || [];
  if (displayTokens.length < 4) return false;
  const englishScore = displayTokens.filter(token => ENGLISH_DISPLAY_WORDS.has(token)).length;
  const indonesianScore = displayTokens.filter(token => INDONESIAN_DISPLAY_WORDS.has(token)).length;
  if (englishScore >= 2 && englishScore > indonesianScore) return true;
  return displayTokens.length >= 6 && englishScore >= 1 && indonesianScore === 0;
}

function requiresEvidence(value, section = '', kind = 'body') {
  const text = String(value || '').trim();
  if (!text) return false;
  if (numericTokens(text).length) return true;
  if (/\b(?:rp|usd|dolar|persen|tahun|bulan|hari|jam|menit|juta|miliar|triliun)\b/i.test(text)) return true;
  if (NON_FACTUAL_START.test(text)) return false;
  if (isQuestion(text)) return false;
  if (FACT_VERBS.test(text)) return true;
  if (kind === 'point') return ASSERTIVE_FACT_MARKERS.test(text);
  if (FACT_MARKERS.test(text)) return true;
  return false;
}

function isNeutralSourceCopy(value, slideIndex, totalSlides) {
  const text = String(value || '').trim();
  if (!text) return true;
  const edge = slideIndex === 0 || slideIndex === totalSlides - 1;
  if (edge && isQuestion(text)) return true;
  return NEUTRAL_SOURCE_COPY.test(text);
}

function requiresSourceEvidence(value, section = '', kind = 'body', slideIndex = 0, totalSlides = 0, format = '') {
  const text = String(value || '').trim();
  if (!text) return false;
  if (requiresEvidence(text, section, kind)) return true;
  const normalizedFormat = String(format || '').toLocaleLowerCase('id-ID');
  if (normalizedFormat === 'fakta singkat'
    && kind !== 'title'
    && !isQuestion(text)
    && /^(?:FAKTA UTAMA|PENJELASAN|KONTEKS)$/i.test(String(section || '').trim())) return true;
  if (normalizedFormat !== 'masalah dan solusi') return false;
  if (isNeutralSourceCopy(text, slideIndex, totalSlides)) return false;
  // Neutral/problem-framing titles are structural copy, not factual claims.
  // Numeric/factual titles are already caught by requiresEvidence() above.
  if (kind === 'title') return false;
  return words(text).length >= 2;
}

function slideFields(slide, slideIndex) {
  const fields = [
    { key: `slide:${slideIndex}:title`, value: String(slide?.title || '').trim(), kind: 'title' },
    { key: `slide:${slideIndex}:body`, value: String(slide?.body || '').trim(), kind: 'body' }
  ];
  (slide?.points || []).forEach((point, pointIndex) => fields.push({
    key: `slide:${slideIndex}:point:${pointIndex}`,
    value: String(point || '').trim(),
    kind: 'point'
  }));
  return fields;
}

function sourceMap(sources = []) {
  return new Map(sources.map((source, index) => [`source-${index + 1}`, normalize(source?.text || '')]));
}

function normalizeClaims(slides = []) {
  return slides.flatMap((slide, slideIndex) => (Array.isArray(slide?.claims) ? slide.claims : []).map(claim => ({
    slideIndex,
    field: String(claim?.field || '').trim(),
    text: String(claim?.text || '').trim(),
    sourceId: String(claim?.sourceId || '').trim(),
    evidence: String(claim?.evidence || '').trim()
  })));
}

function pruneUnneededClaims(content, format = '') {
  if (!content || !Array.isArray(content.slides)) return content;
  const totalSlides = content.slides.length;
  return {
    ...content,
    slides: content.slides.map((slide, slideIndex) => ({
      ...slide,
      claims: (Array.isArray(slide?.claims) ? slide.claims : []).filter(claim => {
        const field = slideFields(slide, slideIndex).find(item => item.key === String(claim?.field || ''));
        return Boolean(field?.value) && requiresSourceEvidence(field.value, slide.section, field.kind, slideIndex, totalSlides, format);
      })
    }))
  };
}

function normalizeFactSections(slides = [], format = '') {
  if (String(format || '').toLocaleLowerCase('id-ID') !== 'fakta singkat' || !Array.isArray(slides)) return slides;
  const labels = slides.length === 4
    ? ['PEMBUKA', 'FAKTA UTAMA', 'KONTEKS', 'KESIMPULAN']
    : slides.length === 5
      ? ['PEMBUKA', 'FAKTA UTAMA', 'PENJELASAN', 'KONTEKS', 'KESIMPULAN']
      : slides.map((_, index) => index === 0 ? 'PEMBUKA' : index === slides.length - 1 ? 'KESIMPULAN' : 'PENJELASAN');
  return slides.map((slide, index) => ({ ...slide, section: labels[index] }));
}

function groundingTerms(value) {
  return [...tokens(value)].filter(token => (token.length > 2 || token === 'ai') && !GROUNDING_STOPWORDS.has(token));
}

function evidenceSupport(text, evidence) {
  const textNorm = normalize(text);
  const evidenceNorm = normalize(evidence);
  if (!textNorm || !evidenceNorm) return { exact: false, matches: 0, total: 0, score: 0 };
  const claimNumbers = numericTokens(text);
  const evidenceNumbers = new Set(numericTokens(evidence));
  if (!claimNumbers.every(number => evidenceNumbers.has(number))) return { exact: false, matches: 0, total: 0, score: 0 };
  const claimNegations = [...tokens(text)].filter(token => NEGATION_TOKENS.has(token));
  const evidenceTokenSet = tokens(evidence);
  if (claimNegations.some(token => !evidenceTokenSet.has(token))) return { exact: false, matches: 0, total: 0, score: 0 };
  const exact = evidenceNorm.includes(textNorm);
  const terms = groundingTerms(text);
  const matches = terms.filter(token => evidenceTokenSet.has(token)).length;
  const score = terms.length ? matches / terms.length : 0;
  return { exact, matches, total: terms.length, score };
}

function recoverMissingClaims(candidate, sources = [], format = '') {
  if (!candidate || !Array.isArray(candidate.slides)) return candidate;
  const existing = new Set(normalizeClaims(candidate.slides).map(claim => claim.field).filter(Boolean));
  const evidence = sources.flatMap((source, index) => evidenceCandidates(source?.text).map(item => ({ sourceId: `source-${index + 1}`, evidence: item })));
  const totalSlides = candidate.slides.length;
  candidate.slides.forEach((slide, slideIndex) => {
    for (const field of slideFields(slide, slideIndex)) {
      if (!field.value || existing.has(field.key) || !requiresSourceEvidence(field.value, slide.section, field.kind, slideIndex, totalSlides, format)) continue;
      let best = null;
      for (const item of evidence) {
        const support = evidenceSupport(field.value, item.evidence);
        const acceptable = support.exact || (support.total >= 3 && support.matches >= 3 && support.score >= 0.8);
        if (!acceptable) continue;
        if (!best || Number(support.exact) > Number(best.support.exact) || support.score > best.support.score) best = { item, support };
      }
      if (!best) continue;
      if (!Array.isArray(slide.claims)) slide.claims = [];
      slide.claims.push({ field: field.key, text: field.value, sourceId: best.item.sourceId, evidence: best.item.evidence });
      existing.add(field.key);
    }
  });
  return candidate;
}

function topicRelevanceTerms(manualTopic) {
  const entityTerms = topicEntityTokens(manualTopic).filter(token => !GENERIC_ENTITY_TOKENS.has(token));
  if (entityTerms.length) return entityTerms;
  return [...tokens(manualTopic)].filter(token => token.length > 2 && !TOPIC_RELEVANCE_STOPWORDS.has(token));
}

function validateSlideTopicRelevance(manualTopic, slides = [], verifiedClaimFields = new Set()) {
  const terms = topicRelevanceTerms(manualTopic);
  if (!manualTopic || !terms.length) return [];
  const errors = [];
  slides.forEach((slide, index) => {
    const edgeSlide = index === 0 || index === slides.length - 1 || /^(?:PEMBUKA|HOOK|PENUTUP|CTA|TRANSISI)$/i.test(String(slide?.section || '').trim());
    if (edgeSlide) return;
    const fields = slideFields(slide, index);
    if (fields.some(field => verifiedClaimFields.has(field.key))) return;
    const visibleTokens = tokens(fields.map(field => field.value).join(' '));
    if (terms.some(term => visibleTokens.has(term))) return;
    const introducedSpecificTerms = [...visibleTokens].filter(token => token.length > 2 && !TOPIC_RELEVANCE_STOPWORDS.has(token) && !NEUTRAL_RELEVANCE_TOKENS.has(token) && !terms.includes(token));
    if (introducedSpecificTerms.length >= 2) errors.push(`Slide ${index + 1}: isi claim-free menyimpang dari inti topik manual; perbaiki agar tetap membahas ${manualTopic}.`);
  });
  return errors;
}

function validateManualTopicIdentity(manualTopic, slides = []) {
  const anchors = topicEntityTokens(manualTopic);
  if (!anchors.length) return [];
  const required = anchors.filter(anchor => !GENERIC_ENTITY_TOKENS.has(anchor));
  if (!required.length) return [];
  const carouselTokens = tokens(slides.map(slide => `${slide?.title || ''} ${slide?.body || ''} ${(slide?.points || []).join(' ')}`).join(' '));
  if (required.some(anchor => carouselTokens.has(anchor))) return [];
  return [`Isi carousel kehilangan objek utama topik manual: ${required.join(' / ')}.`];
}

function validateVerifiedContent(base, candidate, { contentService, format, manualTopic, sources }) {
  const errors = [];
  if (!candidate || !Array.isArray(candidate.slides)) return ['Verifier tidak mengembalikan slides.'];
  if (candidate.slides.length !== base.slides.length) errors.push('Verifier mengubah jumlah slide.');

  const requestedNorm = normalize(manualTopic);
  const maps = sourceMap(sources);
  candidate.slides.forEach((slide, index) => {
    const baseSlide = base.slides[index];
    if (!baseSlide) return;
    if (String(slide.section || '').trim() !== String(baseSlide.section || '').trim()) errors.push(`Slide ${index + 1}: section berubah.`);
    if (!String(slide.title || '').trim()) errors.push(`Slide ${index + 1}: title kosong.`);
    if (!String(slide.body || '').trim() && !(slide.points || []).length) errors.push(`Slide ${index + 1}: tidak memiliki isi bermakna.`);
    if (requestedNorm && normalize(slide.title) === requestedNorm) errors.push(`Slide ${index + 1}: requestedTopic dipakai mentah sebagai judul.`);
    for (const field of slideFields(slide, index)) if (field.value && likelyEnglishDisplayText(field.value)) errors.push(`${field.key}: copy tampil harus Bahasa Indonesia.`);
    const rendered = `${slide.title || ''} ${slide.body || ''} ${(slide.points || []).join(' ')}`;
    if (/lanjut\s+baca\s+tentang/i.test(rendered)) errors.push(`Slide ${index + 1}: memakai filler "Lanjut baca tentang".`);
    if (BOILERPLATE.test(rendered)) errors.push(`Slide ${index + 1}: metadata/boilerplate website masuk ke konten.`);
  });
  errors.push(...validateManualTopicIdentity(manualTopic, candidate.slides));

  recoverMissingClaims(candidate, sources, format);

  const claims = normalizeClaims(candidate.slides);
  const claimByField = new Map();
  const verifiedClaimFields = new Set();
  for (const claim of claims) {
    let validClaim = true;
    if (!claim.field || !claim.text || !claim.sourceId || !claim.evidence) {
      errors.push('Claim verifier tidak lengkap.');
      continue;
    }
    if (!maps.has(claim.sourceId)) {
      errors.push(`Claim memakai sourceId yang tidak tersedia: ${claim.sourceId}.`);
      validClaim = false;
    }
    const evidenceNorm = normalize(claim.evidence);
    if (!evidenceNorm || !maps.get(claim.sourceId)?.includes(evidenceNorm)) {
      errors.push(`Evidence tidak ditemukan pada ${claim.sourceId}.`);
      validClaim = false;
    }
    if (words(claim.evidence).length < 4 || words(claim.evidence).length > 32) {
      errors.push('Evidence harus 4–32 kata.');
      validClaim = false;
    }
    const claimNumbers = numericTokens(claim.text);
    const evidenceNumbers = new Set(numericTokens(claim.evidence));
    if (!claimNumbers.every(number => evidenceNumbers.has(number))) {
      errors.push(`Angka pada claim tidak didukung evidence: ${claim.text}.`);
      validClaim = false;
    }
    if (claimByField.has(claim.field)) {
      errors.push(`Field ${claim.field} memiliki claim ganda.`);
      validClaim = false;
    }
    claimByField.set(claim.field, claim);
    if (validClaim) verifiedClaimFields.add(claim.field);
  }

  const totalSlides = candidate.slides.length;
  candidate.slides.forEach((slide, slideIndex) => {
    for (const field of slideFields(slide, slideIndex)) {
      if (!field.value) continue;
      const needsEvidence = requiresSourceEvidence(field.value, slide.section, field.kind, slideIndex, totalSlides, format);
      const claim = claimByField.get(field.key);
      if (needsEvidence && !claim) errors.push(`${field.key}: klaim faktual tidak memiliki evidence.`);
      if (claim && normalize(claim.text) !== normalize(field.value)) errors.push(`${field.key}: claim.text tidak sama dengan copy field.`);
    }
  });
  if (String(format || '').toLocaleLowerCase('id-ID') === 'fakta singkat') {
    candidate.slides.forEach((slide, slideIndex) => {
      const section = String(slide?.section || '').trim();
      const substantiveFields = slideFields(slide, slideIndex).filter(field => field.kind !== 'title');
      if (/^KESIMPULAN$/i.test(section)) {
        const hasMeaningfulConclusion = substantiveFields.some(field => field.value && !isQuestion(field.value));
        if (!hasMeaningfulConclusion) {
          errors.push(`slide:${slideIndex}:body: format Fakta singkat membutuhkan kesimpulan bermakna, bukan pertanyaan saja.`);
        }
        return;
      }
      if (!/^(?:FAKTA UTAMA|PENJELASAN|KONTEKS)$/i.test(section)) return;
      const hasVerifiedSourceFact = substantiveFields.some(field => {
        const claim = claimByField.get(field.key);
        return Boolean(field.value)
          && !isQuestion(field.value)
          && verifiedClaimFields.has(field.key)
          && normalize(claim?.text) === normalize(field.value);
      });
      if (!hasVerifiedSourceFact) {
        errors.push(`slide:${slideIndex}:body: format Fakta singkat membutuhkan fakta terverifikasi dari sumber, bukan pertanyaan saja.`);
      }
    });
  }
  errors.push(...validateSlideTopicRelevance(manualTopic, candidate.slides, verifiedClaimFields));

  const verified = { ...base, slides: candidate.slides, verificationStatus: 'source_based', unsupportedClaims: [] };
  const first = verified.slides[0];
  const informative = verified.slides.find(slide => String(slide.body || '').trim() || (slide.points || []).length) || first;
  const last = verified.slides.at(-1);
  verified.hook = String(first?.title || base.hook || '').trim();
  verified.body = String(informative?.body || informative?.points?.join(' ') || base.body || '').trim();
  verified.caption = verified.body;
  verified.cta = String(last?.title || base.cta || '').trim();

  if (contentService?.validateContent) errors.push(...contentService.validateContent(verified, { format, manualTopic: '', validateCopy: false }));
  return { errors: [...new Set(errors)], content: verified };
}

function dropUnsupportedPointClaims(content, semanticErrors = []) {
  if (!content || !Array.isArray(content.slides) || !Array.isArray(semanticErrors)) return null;
  const targets = semanticErrors.map(error => {
    const match = String(error || '').match(/SEMANTIC_SUPPORT:\s+slide:(\d+):point:(\d+)\b/);
    return match ? { slideIndex: Number(match[1]), pointIndex: Number(match[2]) } : null;
  }).filter(Boolean);
  if (!targets.length) return null;
  const slides = content.slides.map(slide => ({
    ...slide,
    points: Array.isArray(slide?.points) ? [...slide.points] : [],
    claims: Array.isArray(slide?.claims) ? slide.claims.map(claim => ({ ...claim })) : []
  }));
  let changed = false;
  const grouped = new Map();
  for (const target of targets) {
    if (!grouped.has(target.slideIndex)) grouped.set(target.slideIndex, new Set());
    grouped.get(target.slideIndex).add(target.pointIndex);
  }
  for (const [slideIndex, pointIndexes] of grouped) {
    const slide = slides[slideIndex];
    if (!slide) continue;
    for (const pointIndex of [...pointIndexes].sort((a, b) => b - a)) {
      if (pointIndex < 0 || pointIndex >= slide.points.length) continue;
      const hasOtherContent = Boolean(String(slide.body || '').trim()) || slide.points.length > 1;
      if (!hasOtherContent) continue;
      slide.points.splice(pointIndex, 1);
      slide.claims = slide.claims.flatMap(claim => {
        const match = String(claim?.field || '').match(new RegExp(`^slide:${slideIndex}:point:(\\d+)$`));
        if (!match) return [claim];
        const claimPointIndex = Number(match[1]);
        if (claimPointIndex === pointIndex) return [];
        if (claimPointIndex > pointIndex) return [{ ...claim, field: `slide:${slideIndex}:point:${claimPointIndex - 1}` }];
        return [claim];
      });
      changed = true;
    }
  }
  return changed ? { ...content, slides } : null;
}

function recoveryFieldKeys(errors = []) {
  return new Set(errors.flatMap(error => {
    const matches = [...String(error || '').matchAll(/slide:(\d+):(title|body|point:\d+)\b/gi)];
    return matches.map(match => `slide:${Number(match[1])}:${match[2].toLocaleLowerCase('id-ID')}`);
  }));
}

function mergeRecoveryFields(draft, candidate, fieldKeys) {
  if (!draft || !Array.isArray(draft.slides) || !candidate || !Array.isArray(candidate.slides) || !fieldKeys?.size) return draft;
  const slides = draft.slides.map((slide, slideIndex) => {
    const incoming = candidate.slides[slideIndex];
    if (!incoming) return slide;
    const next = {
      ...slide,
      points: Array.isArray(slide?.points) ? [...slide.points] : [],
      claims: Array.isArray(slide?.claims) ? slide.claims.map(claim => ({ ...claim })) : []
    };
    for (const kind of ['title', 'body']) {
      const field = `slide:${slideIndex}:${kind}`;
      if (fieldKeys.has(field)) next[kind] = String(incoming?.[kind] || '').trim();
    }

    const targetForSlide = field => fieldKeys.has(String(field || ''));
    next.claims = next.claims.filter(claim => !targetForSlide(claim?.field));
    const pointTargets = [...fieldKeys].map(field => {
      const match = field.match(new RegExp(`^slide:${slideIndex}:point:(\\d+)$`));
      return match ? Number(match[1]) : null;
    }).filter(index => index !== null).sort((a, b) => b - a);
    for (const pointIndex of pointTargets) {
      if (!Array.isArray(incoming.points) || incoming.points.length <= pointIndex) {
        next.points.splice(pointIndex, 1);
        next.claims = next.claims.map(claim => {
          const match = String(claim?.field || '').match(new RegExp(`^slide:${slideIndex}:point:(\\d+)$`));
          if (!match || Number(match[1]) < pointIndex) return claim;
          return { ...claim, field: `slide:${slideIndex}:point:${Number(match[1]) - 1}` };
        });
      } else next.points[pointIndex] = String(incoming.points[pointIndex] || '').trim();
    }

    for (const claim of Array.isArray(incoming?.claims) ? incoming.claims : []) {
      if (targetForSlide(claim?.field)) next.claims.push({ ...claim });
    }
    return next;
  });
  return { ...draft, slides };
}

function semanticAuditPrompt(content, topic, format = '') {
  const claims = normalizeClaims(content?.slides || []).map(({ field, text, sourceId, evidence }) => ({ field, text, sourceId, evidence }));
  const slides = (content?.slides || []).map(slide => ({
    section: slide?.section,
    title: slide?.title,
    body: slide?.body,
    points: slide?.points || []
  }));
  const coherenceRules = String(format || '').toLocaleLowerCase('id-ID') === 'masalah dan solusi'
    ? `\n11. Baca SLIDES sebagai satu alur. Setiap SOLUSI/tips harus langsung menjawab MASALAH yang dibahas, bukan mengambil poin lain dari artikel hanya karena evidence-nya valid;\n12. title, body, dan points dalam satu slide harus menjelaskan satu ide yang sama. Tandai field yang memasukkan ide berbeda atau bullet yang menjadi topik baru;\n13. SOLUSI lanjutan dan HASIL/PENUTUP harus tetap mengikuti fokus masalah dan solusi sebelumnya. Tandai outcome yang tidak didukung atau hanya mengulang outcome lain;\n14. Jangan mengubah kemungkinan menjadi kepastian. Jika evidence memakai can/could/may/help/potential atau dapat/bisa/berpotensi/membantu, tandai claim pasti seperti “meningkat”, “menghasilkan”, atau “pasti lebih baik”;\n15. Nilai hubungan antarklaim memakai konteks SLIDES, tetapi setiap field tetap harus dibuktikan oleh satu evidence miliknya. Jangan menggabungkan dua evidence menjadi kesimpulan baru.`
    : '';
  return `Anda auditor entailment fakta bilingual Indonesia-Inggris. Gunakan HANYA claim, evidence, dan konteks SLIDES yang diberikan. Jangan memakai pengetahuan luar.\n\nTOPIK UTAMA: ${JSON.stringify(topic || '')}\nFORMAT: ${JSON.stringify(format || '')}\nSLIDES: ${JSON.stringify(slides)}\nCLAIMS: ${JSON.stringify(claims)}\n\nUntuk setiap claim, tandai unsupported bila salah satu berlaku:\n1. evidence tidak menyatakan makna yang sama dengan claim.text;\n2. claim menambahkan tujuan, sebab-akibat, manfaat, aplikasi, risiko, keselamatan, masa depan, atau kesimpulan yang tidak dinyatakan evidence;\n3. claim bertentangan dengan evidence, termasuk menyebut sesuatu sederhana ketika evidence menyebutnya sulit;\n4. claim mungkin benar secara umum tetapi evidence yang dipasangkan tidak membuktikannya;\n5. claim/evidence menyimpang jauh dari TOPIK UTAMA dan hanya mengambil side-note artikel yang tidak membantu menjawab topik;\n6. ENTITY TYPE berubah: tool/alat, model, aplikasi, fitur, produk, perusahaan, dan layanan adalah jenis berbeda dan tidak boleh saling ditukar;\n7. NAMED LIST atau SCOPE berubah: pertahankan persis secara makna daftar paket/tier, platform, wilayah, model, atau kelompok pengguna. Menambah, menghapus, atau mengganti anggota daftar adalah unsupported;\n8. MODALITY lebih kuat: can/could/may/help/designed to/intended to harus tetap dapat/bisa/mungkin/membantu/dirancang untuk, bukan pasti/selalu/menjamin/mencegah/menghilangkan;\n9. NEGATION atau EXCLUSION hilang/berbalik, termasuk ketidaktersediaan pada tier tertentu;\n10. TEMPORAL FACT bergeser: tanggal, bulan, tahun, urutan rollout, preview, default, availability, atau perubahan setting harus tetap sama.${coherenceRules}\n\nPeriksa detail-detail ini walaupun tema umum claim benar. Terjemahan/parafrase Indonesia dari evidence Inggris boleh dan harus dianggap supported bila entity type, scope, modalitas, negasi, serta waktu tetap setia. Jangan menolak hanya karena beda bahasa.\nKembalikan HANYA JSON {"unsupported":[{"field":"slide:0:body","reason":"alasan singkat"}]}. Jika semua didukung, kembalikan {"unsupported":[]}.`;
}

async function auditClaimSemantics(openai, content, topic, format = '') {
  const claims = normalizeClaims(content?.slides || []);
  if (!claims.length) return [];
  const response = await openai.chat.completions.create({
    model: config.aiModel,
    messages: [
      { role: 'system', content: 'Anda auditor fakta ketat. Evidence harus benar-benar mendukung arti claim, bukan sekadar membahas tema serupa.' },
      { role: 'user', content: semanticAuditPrompt(content, topic, format) }
    ],
    response_format: { type: 'json_object' }
  });
  let parsed;
  try { parsed = parseJsonResponse(response); }
  catch (error) { return [`SEMANTIC_SUPPORT: audit tidak mengembalikan JSON valid: ${error.message}`]; }
  if (!Array.isArray(parsed.unsupported)) return ['SEMANTIC_SUPPORT: audit tidak mengembalikan array unsupported.'];
  const known = new Set(claims.map(claim => claim.field));
  if (String(format || '').toLocaleLowerCase('id-ID') === 'masalah dan solusi') {
    (content?.slides || []).forEach((slide, slideIndex) => {
      if (String(slide?.title || '').trim()) known.add(`slide:${slideIndex}:title`);
    });
  }
  return parsed.unsupported
    .filter(item => item?.field && known.has(String(item.field)))
    .map(item => `SEMANTIC_SUPPORT: ${String(item.field)} tidak didukung evidence: ${String(item.reason || 'makna claim melampaui evidence')}`);
}

function verifierPrompt({ base, draft = base, bank, topic, format, errors = [] }) {
  const totalSlides = draft?.slides?.length || base?.slides?.length || 0;
  const requiredClaimFields = (draft?.slides || []).flatMap((slide, slideIndex) =>
    slideFields(slide, slideIndex)
      .filter(field => field.value && requiresSourceEvidence(field.value, slide.section, field.kind, slideIndex, totalSlides, format))
      .map(field => ({ field: field.key, text: field.value }))
  );
  const factFormatRules = String(format || '').toLocaleLowerCase('id-ID') === 'fakta singkat'
    ? '- FORMAT FAKTA SINGKAT: section sudah dikunci sebagai label netral fakta. Dilarang mengubahnya menjadi MASALAH, PENYEBAB, SOLUSI, HASIL, TUTORIAL, atau LANGKAH. Jangan memaksa alur sebab-solusi-hasil. Susun isi sebagai pembuka → fakta utama → penjelasan/konteks → kesimpulan yang benar-benar berasal dari sumber.'
    : '';
  const problemSolutionRule = String(format || '').toLocaleLowerCase('id-ID') === 'masalah dan solusi'
    ? '- FORMAT MASALAH DAN SOLUSI: semua masalah, solusi, tips, rekomendasi, dan instruksi konkret wajib didukung FACT_BANK. Dilarang menciptakan langkah perbaikan yang tidak disebut sumber.'
    : '';
  return `Anda adalah FILTER/VERIFIER fakta untuk carousel Indonesia. Anda BUKAN pembuat struktur carousel baru.\n\nTOPIK REFERENSI: ${JSON.stringify(topic || '')}\nFORMAT: ${JSON.stringify(format || '')}\n\nFIELD FAKTUAL CURRENT_DRAFT DAN COPY SUBSTANTIF YANG WAJIB PUNYA CLAIM JIKA DIPERTAHANKAN:\n${JSON.stringify(requiredClaimFields)}\n\nATURAN WAJIB:\n- Pertahankan JUMLAH slide, URUTAN slide, dan SECTION persis seperti ORIGINAL_CONTENT.\n${factFormatRules}\n${problemSolutionRule}\n- requestedTopic hanya referensi topik. Jangan menjadikannya judul mentah.\n- Jika topik menyebut nama orang, produk, model, atau perusahaan, identitas itu harus tetap muncul secara natural dalam carousel.\n- Pertahankan gaya natural ORIGINAL_CONTENT sebanyak mungkin.\n- SETIAP slide wajib tetap berada pada inti TOPIK REFERENSI dan tema FACT_BANK. Jangan mengambil side-note artikel yang tidak membantu menjawab topik hanya karena faktanya benar.\n- Dilarang memperkenalkan tutorial, tool, workflow, prompting, otomatisasi, strategi, aplikasi baru, atau saran baru yang tidak benar-benar terkait dengan topik/sumber hanya untuk mengisi slide.\n- Jika CURRENT_DRAFT punya slide generik atau menyimpang, tulis ulang slide itu memakai fakta/sudut yang relevan dari FACT_BANK; jangan mempertahankan isi generik hanya karena non-faktual.\n- SEMUA COPY YANG TAMPIL (title, body, points) WAJIB Bahasa Indonesia natural. Istilah brand/produk/AI/API boleh tetap asli, tetapi jangan salin kalimat bahasa Inggris dari sumber ke copy tampil.\n- Evidence di dalam claims WAJIB tetap kutipan asli dari FACT_BANK dan BOLEH berbahasa Inggris; jangan menerjemahkan evidence.\n- Source hanya untuk FILTER/VERIFIKASI fakta, bukan untuk menentukan struktur atau jumlah slide.\n- Jangan menambah URL/sumber apa pun.\n- Untuk copy yang masuk FIELD SUBSTANTIF di atas, sertakan claim dengan sourceId + evidence PERSIS dari FACT_BANK.\n- Pada format Masalah dan solusi, dilarang mengakali evidence dengan mengubah klaim menjadi perintah. Contoh “Koreksi warna batch”, “Tambahkan transisi halus”, atau “Periksa audio sinkronisasi” tetap wajib evidence.\n- Evidence harus MEMBUKTIKAN ARTI claim.text, bukan hanya mengandung kata yang mirip atau membahas tema yang sama.\n- Dilarang memasangkan evidence valid ke claim yang menambahkan tujuan, sebab-akibat, manfaat, aplikasi, keselamatan, risiko, atau kesimpulan yang tidak disebut evidence.\n- AUDIT SETIAP title, body, dan point sebelum mengembalikan JSON: semua pernyataan faktual dan semua copy substantif pada format Masalah dan solusi wajib punya claim.\n- Satu claim hanya boleh memakai satu sourceId/evidence. Jangan gabungkan beberapa sumber menjadi kesimpulan baru.\n- Jika fakta ORIGINAL_CONTENT tidak didukung, ubah hanya copy itu menjadi fakta terdekat yang benar-benar didukung, atau menjadi copy netral yang tetap berguna. Jangan mengarang.\n- Hook, pertanyaan, transisi, dan CTA netral boleh tanpa claim jika tidak memuat klaim faktual.\n- Jangan memberi claim pada copy yang sebenarnya hanya CTA/transisi netral jika tidak ada fakta di dalamnya.\n- Setiap slide wajib tetap memiliki title dan minimal body atau points yang bermakna.\n- BATAS COPY FINAL: title maksimal 12 kata; body maksimal 24 kata; points maksimal 3 item; tiap point maksimal 7 kata.\n- Jika error sebelumnya menyebut body/title/point terlalu panjang, ringkas field itu tanpa menambah fakta baru.\n- Jika error sebelumnya menyebut copy tampil harus Bahasa Indonesia, terjemahkan/parafrase FIELD PERSIS itu ke Bahasa Indonesia natural tanpa menambah fakta; evidence tetap kutipan asli.\n- Jika error sebelumnya menyebut slide claim-free menyimpang dari inti topik manual, tulis ulang slide itu agar langsung terkait dengan TOPIK REFERENSI dan FACT_BANK.\n- Jika error sebelumnya diawali SEMANTIC_SUPPORT, ganti claim dengan terjemahan/parafrase setia dari evidence yang benar-benar relevan; jangan mempertahankan klaim lama.\n- Saat memperbaiki SEMANTIC_SUPPORT, pertahankan jenis entitas, daftar/scope paket atau pengguna, modalitas, negasi/pengecualian, serta tanggal dan urutan rollout persis secara makna dari evidence. Jangan melengkapi detail yang tidak disebut evidence.\n- Jika SEMANTIC_SUPPORT mengenai sebuah point dan FACT_BANK tidak punya evidence yang benar-benar mendukung point itu, HAPUS point tersebut. Jangan mengarang point pengganti hanya untuk mempertahankan jumlah bullet.\n- Jika error sebelumnya menyebut klaim faktual tidak memiliki evidence, tambahkan claim untuk FIELD PERSIS itu memakai evidence yang benar-benar mendukung, atau ubah field menjadi copy netral yang akurat. Pada format Masalah dan solusi, solusi/tips konkret tidak boleh dijadikan copy netral untuk menghindari evidence.\n- Title, body, dan points dalam satu slide harus saling melengkapi. Jangan mengulang kalimat atau ide yang sama di field berbeda.\n- Dilarang slide kosong, filler, metadata website, byline/contributor/newsletter, judul hanya topik mentah, atau "Lanjut baca tentang ...".\n- Jangan mengubah hashtag, focus, metadata angle/tool, atau struktur di luar slides.\n- Jangan membuat angka/nama/tanggal/manfaat/sebab-akibat baru.\n\nUntuk setiap claim gunakan field key persis:\nslide:<index>:title\nslide:<index>:body\nslide:<index>:point:<pointIndex>\nindex dimulai dari 0.\nclaim.text harus sama persis dengan copy field yang didukung.\n\nFACT_BANK (hanya dari URL yang diberikan user):\n${JSON.stringify(bank)}\n\nORIGINAL_STRUCTURE (jumlah, urutan, dan section tidak boleh berubah):\n${JSON.stringify((base?.slides || []).map(slide => ({ section: slide.section })))}\n\nCURRENT_DRAFT (perbaiki versi ini; jangan kembali mengulang versi awal):\n${JSON.stringify(draft)}\n${errors.length ? `\nERROR VERIFIKASI SEBELUMNYA YANG HARUS DIPERBAIKI:\n- ${errors.join('\n- ')}` : ''}\n\nKembalikan HANYA JSON:\n{"slides":[{"section":"...","title":"...","body":"...","points":[],"claims":[{"field":"slide:0:body","text":"...","sourceId":"source-1","evidence":"..."}]}]}`;
}

function safeRecoveryPrompt({ base, draft, bank, topic, format, errors }) {
  return `${verifierPrompt({ base, draft, bank, topic, format, errors })}\n\nFINAL SAFE RECOVERY:\n- Perbaiki HANYA field yang disebut dalam error; pertahankan field lain yang sudah valid.\n- Untuk body/title yang gagal, pilih SATU fakta paling relevan dari FACT_BANK lalu tulis paraphrase Bahasa Indonesia yang singkat dan setia, beserta satu claim/evidence yang tepat.\n- Jika error format Fakta singkat menyebut fakta terverifikasi, field target WAJIB menjadi pernyataan yang menjawab topik dengan satu evidence relevan dari FACT_BANK, bukan pertanyaan lain, CTA, filler, atau copy netral kosong. Sertakan claim dengan field, text, sourceId, dan evidence. Jika evidence tidak cocok dengan ide lama, gunakan fakta relevan lain yang masih menjawab TOPIK UTAMA; jangan mengarang demi mempertahankan sudut lama.\n- Jangan menambah sebab-akibat, manfaat, kesimpulan, atau modalitas yang lebih kuat daripada evidence. Jika evidence menyebut can/could/may/help/potential, gunakan dapat/bisa/mungkin/membantu/berpotensi, bukan kepastian.\n- Untuk drift entity/scope/modalitas/pengecualian/waktu, ubah HANYA field target menjadi paraphrase sesempit yang evidence dukung. Jangan mengubah field lain atau menambahkan detail agar kalimat terdengar lengkap.\n- Untuk point yang gagal dan tidak punya dukungan tepat, hapus point serta claim-nya; 1–2 point yang valid lebih baik daripada bullet rekaan.\n- Title boleh dijadikan label struktural/netral yang natural dan selaras dengan body valid tanpa claim faktual baru.\n- PEMBUKA format Fakta singkat boleh berupa pertanyaan atau copy struktural/netral. KESIMPULAN harus merangkum fakta yang sudah didukung atau menjadi penutup netral yang bermakna, bukan pertanyaan kosong; fakta/manfaat di dalamnya tetap wajib evidence.\n- Jumlah slide, urutan, section, dan format HARUS persis sama. Jangan mengosongkan slide.`;
}

function parseJsonResponse(response) {
  const raw = response?.choices?.[0]?.message?.content;
  if (!raw) throw new Error('Verifier sumber tidak mengembalikan konten.');
  return JSON.parse(raw);
}

async function generateFilteredContent({ content, previousTopics = [], options = {}, sources = [], client }) {
  let base = await content.generateContent(previousTopics, {
    ...options,
    useSources: false,
    skipCopyValidation: true,
    skipManualTopicValidation: true,
    sourceContext: '',
    sources: []
  }, client);

  if (!Array.isArray(base?.slides) || !base.slides.length) throw Object.assign(new Error('Konten normal tidak memiliki slide terstruktur untuk diverifikasi sumber.'), { status: 422 });
  base = { ...base, slides: normalizeFactSections(base.slides, options.contentFormat) };

  const topic = options.requestedTopic || options.mainTopic || base.topic || '';
  const bank = extractFactBank(sources, topic);
  if (!bank.length) throw Object.assign(new Error('Sumber tidak memiliki fakta yang layak untuk memverifikasi konten.'), { status: 422 });

  const openai = client || new OpenAI({ apiKey: config.aiApiKey, baseURL: config.aiBaseUrl });
  let errors = [];
  let draft = base;
  for (let attempt = 1; attempt <= MAX_VERIFY_ATTEMPTS; attempt += 1) {
    const response = await openai.chat.completions.create({
      model: config.aiModel,
      messages: [
        { role: 'system', content: 'Anda memfilter fakta carousel. Sumber hanya untuk verifikasi fakta; jangan mengganti struktur konten.' },
        { role: 'user', content: verifierPrompt({ base, draft, bank, topic, format: options.contentFormat, errors }) }
      ],
      response_format: { type: 'json_object' }
    });
    let candidate;
    try { candidate = parseJsonResponse(response); }
    catch (error) { errors = [`JSON verifier tidak valid: ${error.message}`]; continue; }

    const checked = validateVerifiedContent(base, candidate, {
      contentService: content,
      format: options.contentFormat,
      manualTopic: options.topicSource === 'manual' ? options.requestedTopic : '',
      sources
    });
    if (!checked.errors.length) {
      const semanticReady = pruneUnneededClaims(checked.content, options.contentFormat);
      const semanticErrors = await auditClaimSemantics(openai, semanticReady, topic, options.contentFormat);
      if (!semanticErrors.length) return checked.content;
      const reduced = dropUnsupportedPointClaims(checked.content, semanticErrors);
      if (reduced) {
        const reducedChecked = validateVerifiedContent(base, { slides: reduced.slides }, {
          contentService: content,
          format: options.contentFormat,
          manualTopic: options.topicSource === 'manual' ? options.requestedTopic : '',
          sources
        });
        if (!reducedChecked.errors.length) {
          const remainingSemanticErrors = await auditClaimSemantics(openai, reducedChecked.content, topic, options.contentFormat);
          if (!remainingSemanticErrors.length) return reducedChecked.content;
          errors = remainingSemanticErrors;
          draft = { ...base, slides: reducedChecked.content.slides };
          continue;
        }
      }
      errors = semanticErrors;
      draft = { ...base, slides: checked.content.slides };
      continue;
    }
    errors = checked.errors;
    draft = { ...base, slides: Array.isArray(candidate.slides) ? candidate.slides : draft.slides };
  }

  // The strict verifier remains the gate. This last, focused pass gives the model
  // a chance to replace only bad fields from the existing fact bank instead of
  // discarding an otherwise valid carousel.
  const recoveryStates = new Set();
  let safeRecoveryAttempts = 0;
  while (safeRecoveryAttempts < MAX_SAFE_RECOVERY_ATTEMPTS) {
    const fieldKeys = recoveryFieldKeys(errors);
    if (!fieldKeys.size) break;
    const recoveryState = JSON.stringify({ fields: [...fieldKeys].sort(), slides: draft.slides });
    if (recoveryStates.has(recoveryState)) break;
    recoveryStates.add(recoveryState);
    safeRecoveryAttempts += 1;
    const response = await openai.chat.completions.create({
      model: config.aiModel,
      messages: [
        { role: 'system', content: 'Anda melakukan recovery field secara ketat. Jangan mengarang dan jangan mengubah struktur carousel.' },
        { role: 'user', content: safeRecoveryPrompt({ base, draft, bank, topic, format: options.contentFormat, errors }) }
      ],
      response_format: { type: 'json_object' }
    });
    let candidate;
    try { candidate = parseJsonResponse(response); }
    catch (error) { errors = [`JSON safe recovery tidak valid: ${error.message}`]; continue; }
    candidate = mergeRecoveryFields(draft, candidate, fieldKeys);

    const checked = validateVerifiedContent(base, candidate, {
      contentService: content,
      format: options.contentFormat,
      manualTopic: options.topicSource === 'manual' ? options.requestedTopic : '',
      sources
    });
    if (checked.errors.length) {
      errors = checked.errors;
      draft = { ...base, slides: Array.isArray(candidate.slides) ? candidate.slides : draft.slides };
      continue;
    }

    const semanticReady = pruneUnneededClaims(checked.content, options.contentFormat);
    const semanticErrors = await auditClaimSemantics(openai, semanticReady, topic, options.contentFormat);
    if (!semanticErrors.length) return checked.content;

    const reduced = dropUnsupportedPointClaims(checked.content, semanticErrors);
    if (reduced) {
      const reducedChecked = validateVerifiedContent(base, { slides: reduced.slides }, {
        contentService: content,
        format: options.contentFormat,
        manualTopic: options.topicSource === 'manual' ? options.requestedTopic : '',
        sources
      });
      if (!reducedChecked.errors.length) {
        const remainingSemanticErrors = await auditClaimSemantics(openai, pruneUnneededClaims(reducedChecked.content, options.contentFormat), topic, options.contentFormat);
        if (!remainingSemanticErrors.length) return reducedChecked.content;
        errors = remainingSemanticErrors;
        draft = { ...base, slides: reducedChecked.content.slides };
        continue;
      }
      errors = reducedChecked.errors;
      draft = { ...base, slides: reduced.slides };
      continue;
    }
    errors = semanticErrors;
    draft = { ...base, slides: checked.content.slides };
  }

  const recoveryFailed = recoveryFieldKeys(errors).size > 0;
  const failure = recoveryFailed
    ? `Response provider tidak dapat diproses setelah safe recovery: ${errors[0] || 'verifikasi gagal'}`
    : `Konten tidak lolos filter fakta sumber: ${errors[0] || 'verifikasi gagal'}`;
  throw Object.assign(new Error(failure), {
    status: 422,
    validationErrors: errors
  });
}

module.exports = {
  generateFilteredContent,
  extractFactBank,
  requiresEvidence,
  requiresSourceEvidence,
  validateVerifiedContent,
  validateManualTopicIdentity,
  validateSlideTopicRelevance,
  topicRelevanceTerms,
  topicEntityTokens,
  evidenceCandidates,
  recoverMissingClaims,
  evidenceSupport,
  likelyEnglishDisplayText,
  normalizeFactSections,
  auditClaimSemantics,
  dropUnsupportedPointClaims,
  recoveryFieldKeys,
  mergeRecoveryFields,
  pruneUnneededClaims,
  MAX_VERIFY_ATTEMPTS,
  MAX_SAFE_RECOVERY_ATTEMPTS
};
