const BUILT_INS = ['UGC', 'TikTok Ads', 'Google Veo', 'Google Flow', 'Image Ads', 'Shopee', 'Tokopedia', 'Instagram Reels', 'YouTube Shorts'];
const CORE_VARIABLES = ['product', 'brand', 'character', 'voice', 'duration', 'language', 'style', 'camera', 'lighting', 'cta', 'hook'];
const JSON_FIELDS = { character: 'character_data', product: 'product_data', referenceImages: 'reference_images', variables: 'variables', tags: 'tags' };
const COLUMNS = ['name', 'category', 'description', 'target_ai', 'prompt', 'negative_prompt', 'character_data', 'product_data', 'reference_images', 'style', 'camera', 'lighting', 'voice', 'duration', 'resolution', 'aspect_ratio', 'provider', 'model', 'seed', 'temperature', 'notes', 'variables', 'folder', 'tags', 'is_favorite', 'is_archived'];

function bad(message, details) { return Object.assign(new Error(message), { status: 422, details }); }
function normalize(body = {}, previous = {}) {
  const value = { ...previous };
  for (const column of COLUMNS) if (body[column] !== undefined) value[column] = body[column];
  const aliases = { targetAI: 'target_ai', negativePrompt: 'negative_prompt', aspectRatio: 'aspect_ratio', favorite: 'is_favorite', archived: 'is_archived' };
  for (const [key, column] of Object.entries(aliases)) if (body[key] !== undefined) value[column] = body[key];
  for (const [key, column] of Object.entries(JSON_FIELDS)) if (body[key] !== undefined) value[column] = JSON.stringify(body[key]);
  for (const key of ['name', 'category', 'target_ai', 'prompt', 'provider', 'model']) value[key] = String(value[key] || '').trim();
  value.tags = typeof value.tags === 'string' ? value.tags : '[]'; value.variables = typeof value.variables === 'string' ? value.variables : '{}';
  value.character_data = typeof value.character_data === 'string' ? value.character_data : '{}'; value.product_data = typeof value.product_data === 'string' ? value.product_data : '{}'; value.reference_images = typeof value.reference_images === 'string' ? value.reference_images : '[]';
  value.is_favorite = Number(Boolean(value.is_favorite)); value.is_archived = Number(Boolean(value.is_archived));
  return value;
}
function validate(value, assets = []) {
  const missing = ['name', 'category', 'target_ai', 'prompt', 'provider', 'model'].filter(key => !value[key]);
  if (missing.length) throw bad(`Field wajib belum lengkap: ${missing.join(', ')}`, { fields: missing });
  if (!['image', 'video', 'text', 'workflow'].includes(value.target_ai.toLowerCase())) throw bad('Target AI harus image, video, text, atau workflow');
  if (value.temperature !== undefined && value.temperature !== null && (Number(value.temperature) < 0 || Number(value.temperature) > 2)) throw bad('Temperature harus antara 0 dan 2');
  for (const asset of assets) if (!asset || !asset.type || !asset.url) throw bad('Setiap asset wajib memiliki type dan url');
  const declared = JSON.parse(value.variables || '{}');
  const placeholders = [...value.prompt.matchAll(/{{\s*([\w.-]+)\s*}}/g)].map(match => match[1]);
  const invalid = placeholders.filter(name => !CORE_VARIABLES.includes(name) && !Object.prototype.hasOwnProperty.call(declared, name));
  if (invalid.length) throw bad(`Variable custom belum dideklarasikan: ${[...new Set(invalid)].join(', ')}`, { variables: invalid });
}
function parse(row, db) { if (!row) return null; const result = { ...row, favorite: Boolean(row.is_favorite), archived: Boolean(row.is_archived), preset: Boolean(row.is_preset), character: JSON.parse(row.character_data), product: JSON.parse(row.product_data), referenceImages: JSON.parse(row.reference_images), variables: JSON.parse(row.variables), tags: JSON.parse(row.tags) }; delete result.character_data; delete result.product_data; delete result.reference_images; delete result.is_favorite; delete result.is_archived; delete result.is_preset; if (db) result.assets = db.prepare('SELECT * FROM template_assets WHERE template_id=? ORDER BY id').all(row.id).map(asset => ({ ...asset, metadata: JSON.parse(asset.metadata) })); return result; }
function seed(db) {
  const insert = db.prepare(`INSERT INTO templates(name,category,description,target_ai,prompt,negative_prompt,provider,model,variables,tags,is_preset) VALUES(?,?,?,?,?,?,?,?,?,?,1)`);
  const transaction = db.transaction(() => BUILT_INS.forEach(name => { if (!db.prepare('SELECT 1 FROM templates WHERE is_preset=1 AND name=?').get(name)) { const target = /Veo|Flow|Reels|Shorts|UGC|TikTok/.test(name) ? 'video' : 'image'; insert.run(name, name, `Preset bawaan untuk ${name}`, target, '{{hook}}. Create a {{style}} ad for {{brand}} {{product}} featuring {{character}}. Camera: {{camera}}. Lighting: {{lighting}}. CTA: {{cta}}.', '', target === 'video' ? 'google-omni' : 'openai', target === 'video' ? 'veo-3' : 'gpt-image-1', '{}', JSON.stringify(['preset', name.toLowerCase()])); } }));
  transaction();
}
function get(db, id) { const item = parse(db.prepare('SELECT * FROM templates WHERE id=?').get(Number(id)), db); if (!item) throw Object.assign(new Error('Template tidak ditemukan'), { status: 404 }); return item; }
function list(db, query = {}) { seed(db); const clauses = [], args = []; if (query.search) { clauses.push('(name LIKE ? OR description LIKE ? OR prompt LIKE ? OR tags LIKE ?)'); args.push(...Array(4).fill(`%${query.search}%`)); } for (const [queryKey, column] of [['category','category'], ['folder','folder'], ['targetAI','target_ai']]) if (query[queryKey]) { clauses.push(`${column}=?`); args.push(query[queryKey]); } if (query.favorite !== undefined) { clauses.push('is_favorite=?'); args.push(Number(query.favorite === 'true' || query.favorite === '1')); } if (query.archived !== undefined) { clauses.push('is_archived=?'); args.push(Number(query.archived === 'true' || query.archived === '1')); } return db.prepare(`SELECT * FROM templates ${clauses.length ? `WHERE ${clauses.join(' AND ')}` : ''} ORDER BY is_favorite DESC, updated_at DESC, id DESC`).all(...args).map(row => parse(row, db)); }
function saveAssets(db, id, assets) { if (!Array.isArray(assets)) return; db.prepare('DELETE FROM template_assets WHERE template_id=?').run(id); const insert = db.prepare('INSERT INTO template_assets(template_id,name,type,url,metadata) VALUES(?,?,?,?,?)'); assets.forEach(asset => insert.run(id, asset.name || null, asset.type, asset.url, JSON.stringify(asset.metadata || {}))); }
function create(db, body) { const value = normalize(body); validate(value, body.assets || []); const placeholders = COLUMNS.map(() => '?').join(','); const transaction = db.transaction(() => { const info = db.prepare(`INSERT INTO templates(${COLUMNS.join(',')}) VALUES(${placeholders})`).run(...COLUMNS.map(key => value[key] ?? null)); const id = Number(info.lastInsertRowid); saveAssets(db, id, body.assets); const item = get(db, id); db.prepare('INSERT INTO template_versions(template_id,version,snapshot) VALUES(?,?,?)').run(id, 1, JSON.stringify(item)); return item; }); return transaction(); }
function update(db, id, body) { const oldRow = db.prepare('SELECT * FROM templates WHERE id=?').get(Number(id)); if (!oldRow) throw Object.assign(new Error('Template tidak ditemukan'), { status: 404 }); const value = normalize(body, oldRow); validate(value, body.assets || []); const transaction = db.transaction(() => { const version = oldRow.version + 1; db.prepare(`UPDATE templates SET ${COLUMNS.map(key => `${key}=?`).join(',')},version=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...COLUMNS.map(key => value[key] ?? null), version, id); if (body.assets) saveAssets(db, id, body.assets); const item = get(db, id); db.prepare('INSERT INTO template_versions(template_id,version,snapshot) VALUES(?,?,?)').run(id, version, JSON.stringify(item)); return item; }); return transaction(); }
function remove(db, id) { const result = db.prepare('DELETE FROM templates WHERE id=?').run(Number(id)); if (!result.changes) throw Object.assign(new Error('Template tidak ditemukan'), { status: 404 }); return { deleted: true, id: Number(id) }; }
function compose(template, context = {}) { const sources = [context.template, context.project, context.consistency, context.product, context.character, context.promptStudio, context.variables, context]; const variables = Object.assign({}, template.variables, ...sources.filter(x => x && typeof x === 'object')); const unresolved = []; const prompt = template.prompt.replace(/{{\s*([\w.-]+)\s*}}/g, (_, key) => { const value = variables[key]; if (value === undefined || value === null || value === '') { unresolved.push(key); return `{{${key}}}`; } return typeof value === 'object' ? JSON.stringify(value) : String(value); }); return { prompt, variables, unresolved: [...new Set(unresolved)] }; }
function preview(template, context) { const composed = compose(template, context); const tokens = Math.ceil(composed.prompt.length / 4); const rate = { openai: .6, claude: 3, gemini: .35, 'google-omni': 1 }[template.provider] || 0; return { ...composed, tokenCount: tokens, estimatedCost: Number((tokens / 1e6 * rate).toFixed(8)), changed: composed.prompt !== template.prompt }; }
function duplicate(db, id) { const old = get(db, id); return create(db, { ...old, name: `${old.name} (Copy)`, favorite: false, archived: false }); }
module.exports = { BUILT_INS, CORE_VARIABLES, seed, list, get, create, update, remove, compose, preview, duplicate, validate };
