class AssetRepository {
  constructor(db) { this.db = db; }
  create(asset) { this.db.prepare(`INSERT INTO assets(id,name,type,mime_type,storage_provider,storage_key,storage_url,folder_id,size,checksum,tags,metadata,is_generated) VALUES(@id,@name,@type,@mimeType,@storageProvider,@storageKey,@storageUrl,@folderId,@size,@checksum,@tags,@metadata,@isGenerated)`).run(asset); return this.get(asset.id); }
  get(id) { return this.parse(this.db.prepare('SELECT * FROM assets WHERE id=?').get(id)); }
  findDuplicate(checksum, provider) { return this.parse(this.db.prepare("SELECT * FROM assets WHERE checksum=? AND storage_provider=? AND deleted_at IS NULL LIMIT 1").get(checksum, provider)); }
  list(query = {}) { const where = [query.trash === 'true' ? 'deleted_at IS NOT NULL' : 'deleted_at IS NULL']; const args = []; if (query.keyword) { where.push('(name LIKE ? OR tags LIKE ?)'); args.push(`%${query.keyword}%`, `%${query.keyword}%`); } for (const [field, value] of [['type', query.type], ['storage_provider', query.provider], ['folder_id', query.folderId]]) if (value) { where.push(`${field}=?`); args.push(value); } if (query.favorite === 'true') where.push('is_favorite=1'); if (query.createdFrom) { where.push('created_at>=?'); args.push(query.createdFrom); } if (query.createdTo) { where.push('created_at<=?'); args.push(query.createdTo); } if (query.minSize) { where.push('size>=?'); args.push(Number(query.minSize)); } if (query.maxSize) { where.push('size<=?'); args.push(Number(query.maxSize)); } return this.db.prepare(`SELECT * FROM assets WHERE ${where.join(' AND ')} ORDER BY created_at DESC`).all(...args).map(row => this.parse(row)); }
  update(id, patch) { const current = this.get(id); if (!current) return null; this.db.prepare(`UPDATE assets SET name=?,folder_id=?,tags=?,is_favorite=?,storage_key=?,storage_url=?,storage_provider=?,metadata=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(patch.name ?? current.name, patch.folderId === undefined ? current.folder_id : patch.folderId, JSON.stringify(patch.tags ?? current.tags), Number(patch.favorite ?? current.is_favorite), patch.storageKey ?? current.storage_key, patch.storageUrl ?? current.storage_url, patch.storageProvider ?? current.storage_provider, JSON.stringify(patch.metadata ?? current.metadata), id); return this.get(id); }
  trash(id) { return this.db.prepare('UPDATE assets SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(id).changes; }
  restore(id) { return this.db.prepare('UPDATE assets SET deleted_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(id).changes; }
  remove(id) { return this.db.prepare('DELETE FROM assets WHERE id=?').run(id).changes; }
  parse(row) { return row ? { ...row, tags: JSON.parse(row.tags || '[]'), metadata: JSON.parse(row.metadata || '{}'), is_favorite: Boolean(row.is_favorite), is_generated: Boolean(row.is_generated) } : null; }
}
module.exports = { AssetRepository };
