const path = require('node:path');
const crypto = require('node:crypto');
const config = require('../config');
const { encrypt, decrypt } = require('./credentials');
const { LocalStorageAdapter, TencentCosAdapter } = require('./adapters');
const { AssetRepository } = require('./repository');

class StorageService {
  constructor({ db, transport } = {}) { this.db = db; this.transport = transport; this.repository = new AssetRepository(db); }
  row() { return this.db.prepare("SELECT * FROM storage_settings WHERE id=1").get(); }
  publicSettings() { const row = this.row(); return { provider: row.provider, secretId: row.secret_id_encrypted ? '••••••••' : '', secretKey: row.secret_key_encrypted ? '••••••••' : '', hasSecretId: Boolean(row.secret_id_encrypted), hasSecretKey: Boolean(row.secret_key_encrypted), bucket: row.bucket, region: row.region, endpoint: row.endpoint, useHttps: Boolean(row.use_https), signedUrlExpiration: row.signed_url_expiration, publicUrl: row.public_url, encryption: Boolean(row.encryption), storageQuota: row.storage_quota, autoDeleteDays: row.auto_delete_days, retentionDays: row.retention_days, versioning: Boolean(row.versioning), duplicateDetection: Boolean(row.duplicate_detection) }; }
  saveSettings(body) { const old = this.row(); const secretId = body.secretId === undefined || body.secretId === '••••••••' ? old.secret_id_encrypted : encrypt(body.secretId); const secretKey = body.secretKey === undefined || body.secretKey === '••••••••' ? old.secret_key_encrypted : encrypt(body.secretKey); if (!['local', 'tencent-cos'].includes(body.provider || old.provider)) throw Object.assign(new Error('Storage provider tidak didukung'), { status: 422 }); this.db.prepare(`UPDATE storage_settings SET provider=?,secret_id_encrypted=?,secret_key_encrypted=?,bucket=?,region=?,endpoint=?,use_https=?,signed_url_expiration=?,public_url=?,encryption=?,storage_quota=?,auto_delete_days=?,retention_days=?,versioning=?,duplicate_detection=?,updated_at=CURRENT_TIMESTAMP WHERE id=1`).run(body.provider ?? old.provider, secretId, secretKey, body.bucket ?? old.bucket, body.region ?? old.region, body.endpoint ?? old.endpoint, Number(body.useHttps ?? old.use_https), Math.max(60, Number(body.signedUrlExpiration ?? old.signed_url_expiration)), body.publicUrl ?? old.public_url, Number(body.encryption ?? old.encryption), Math.max(0, Number(body.storageQuota ?? old.storage_quota)), Math.max(0, Number(body.autoDeleteDays ?? old.auto_delete_days)), Math.max(0, Number(body.retentionDays ?? old.retention_days)), Number(body.versioning ?? old.versioning), Number(body.duplicateDetection ?? old.duplicate_detection)); return this.publicSettings(); }
  local() { return new LocalStorageAdapter({ root: path.join(config.root, 'data/assets'), publicBaseUrl: config.publicBaseUrl }); }
  adapter(provider = this.row().provider) { if (provider === 'local') return this.local(); const row = this.row(); return new TencentCosAdapter({ secretId: decrypt(row.secret_id_encrypted), secretKey: decrypt(row.secret_key_encrypted), bucket: row.bucket, region: row.region, endpoint: row.endpoint, useHttps: Boolean(row.use_https), publicUrl: row.public_url, encryption: Boolean(row.encryption) }, this.transport); }
  async test() { const settings = this.publicSettings(); const result = await this.adapter().test(); const usage = this.db.prepare('SELECT COALESCE(SUM(size),0) usage FROM assets WHERE deleted_at IS NULL').get().usage; return { ...result, storageUsage: usage, quota: settings.storageQuota }; }
  async upload({ name, mimeType, data, type, folderId, tags = [], metadata = {}, generated = false }) { const buffer = Buffer.isBuffer(data) ? data : Buffer.from(data, 'base64'); if (!buffer.length) throw Object.assign(new Error('File kosong'), { status: 422 }); const row = this.row(); const provider = row.provider; const checksum = crypto.createHash('sha256').update(buffer).digest('hex'); if (row.duplicate_detection) { const duplicate = this.repository.findDuplicate(checksum, provider); if (duplicate) return { ...duplicate, duplicate: true }; } const extension = path.extname(name).replace(/[^.a-zA-Z0-9]/g, ''); const requestedKey = `${new Date().toISOString().slice(0, 10)}/${crypto.randomUUID()}${extension}`; const adapter = this.adapter(provider); const stored = await adapter.upload(requestedKey, buffer, { mimeType }); const key = stored.key || requestedKey; const url = stored.url || adapter.publicUrl(key); const used = this.db.prepare('SELECT COALESCE(SUM(size),0) usage FROM assets WHERE deleted_at IS NULL').get().usage; if (row.storage_quota && used + buffer.length > row.storage_quota) { await adapter.delete(key); throw Object.assign(new Error('Storage quota terlampaui'), { status: 413 }); } return this.repository.create({ id: crypto.randomUUID(), name, type: type || this.inferType(mimeType), mimeType, storageProvider: provider, storageKey: key, storageUrl: url, folderId: folderId || null, size: buffer.length, checksum: stored.checksum || checksum, tags: JSON.stringify(tags), metadata: JSON.stringify(metadata), isGenerated: Number(generated) }); }
  inferType(mime = '') { return mime.startsWith('image/') ? 'image' : mime.startsWith('video/') ? 'video' : mime.startsWith('audio/') ? 'audio' : 'prompt-attachment'; }
  async url(asset) { return this.adapter(asset.storage_provider).signedUrl(asset.storage_key, this.row().signed_url_expiration); }
  async previewUrl(asset) { return this.adapter(asset.storage_provider).previewUrl(asset.storage_key, asset.mime_type, this.row().signed_url_expiration); }
  async accessible(asset) { const url = await this.url(asset); const previewUrl = asset.type === 'image' ? await this.previewUrl(asset) : null; return { ...asset, storage_url: url, url, preview_url: previewUrl }; }
  async accessibleList(query = {}) { return Promise.all(this.repository.list(query).map(asset => this.accessible(asset))); }
  async move(id, patch) { const asset = this.repository.get(id); if (!asset) throw Object.assign(new Error('Asset tidak ditemukan'), { status: 404 }); if (patch.name && patch.name !== asset.name) { const target = `${path.dirname(asset.storage_key)}/${crypto.randomUUID()}${path.extname(patch.name)}`; const adapter = this.adapter(asset.storage_provider); const stored = await adapter.rename(asset.storage_key, target); patch.storageKey = stored.key || target; patch.storageUrl = stored.url || adapter.publicUrl(target); } return this.repository.update(id, patch); }
  async copy(id) { const asset = this.repository.get(id); if (!asset) throw Object.assign(new Error('Asset tidak ditemukan'), { status: 404 }); const key = `${path.dirname(asset.storage_key)}/${crypto.randomUUID()}${path.extname(asset.storage_key)}`; const adapter = this.adapter(asset.storage_provider); const stored = await adapter.copy(asset.storage_key, key); return this.repository.create({ id: crypto.randomUUID(), name: `Copy of ${asset.name}`, type: asset.type, mimeType: asset.mime_type, storageProvider: asset.storage_provider, storageKey: stored.key || key, storageUrl: stored.url || adapter.publicUrl(key), folderId: asset.folder_id, size: asset.size, checksum: asset.checksum, tags: JSON.stringify(asset.tags), metadata: JSON.stringify({ ...asset.metadata, copiedFrom: asset.id }), isGenerated: Number(asset.is_generated) }); }
}
module.exports = { StorageService };
