const express = require('express');
const session = require('express-session');
const config = require('./config');
const contentService = require('./services/content');
const imageService = require('./services/images');
const tiktokService = require('./services/tiktok');

function createApp({ db, content = contentService, images = imageService, tiktok = tiktokService } = {}) {
  const app = express(); app.set('trust proxy', 1); app.use(express.json()); app.use(express.urlencoded({ extended: false }));
  app.use(session({ secret: config.sessionSecret, resave: false, saveUninitialized: false, cookie: { httpOnly: true, sameSite: 'lax', secure: config.publicBaseUrl.startsWith('https://'), maxAge: 10 * 60 * 1000 } }));
  app.use(express.static(`${config.root}/public`));
  app.get('/terms', (req, res) => res.sendFile(`${config.root}/public/terms.html`));
  app.get('/privacy', (req, res) => res.sendFile(`${config.root}/public/privacy.html`));
  app.get('/auth/tiktok', (req, res) => { const state = tiktok.randomState(); req.session.oauthState = state; res.redirect(tiktok.authorizationUrl(state)); });
  app.get('/auth/tiktok/callback', async (req, res, next) => { try { if (!req.query.code || req.query.state !== req.session.oauthState) return res.status(400).send('OAuth state tidak valid.'); const token = await tiktok.exchangeCode(req.query.code); db.prepare(`INSERT INTO oauth_tokens(provider,access_token,refresh_token,expires_at,refresh_expires_at,open_id,scope) VALUES('tiktok',?,?,?,?,?,?) ON CONFLICT(provider) DO UPDATE SET access_token=excluded.access_token,refresh_token=excluded.refresh_token,expires_at=excluded.expires_at,refresh_expires_at=excluded.refresh_expires_at,open_id=excluded.open_id,scope=excluded.scope,updated_at=CURRENT_TIMESTAMP`).run(token.access_token, token.refresh_token, Date.now() + token.expires_in * 1000, Date.now() + token.refresh_expires_in * 1000, token.open_id, token.scope); delete req.session.oauthState; res.redirect('/?oauth=success'); } catch (e) { next(e); } });
  app.post('/generate', async (req, res, next) => { try { const topics = db.prepare('SELECT topic FROM contents ORDER BY id DESC LIMIT 50').all().map(x => x.topic); const c = await content.generateContent(topics); const result = db.prepare('INSERT INTO contents(topic,hook,body,caption,hashtags,cta) VALUES(?,?,?,?,?,?)').run(c.topic, c.hook, c.body, c.caption, JSON.stringify(c.hashtags), c.cta); const slides = await images.createSlides(result.lastInsertRowid, c); db.prepare('UPDATE contents SET slides=? WHERE id=?').run(JSON.stringify(slides), result.lastInsertRowid); res.json(record(db, result.lastInsertRowid)); } catch (e) { next(e); } });
  app.post('/upload-tiktok', async (req, res, next) => { try { const item = record(db, Number(req.body.id)); if (!item) return res.status(404).json({ error: 'Konten tidak ditemukan' }); const token = await validToken(db, tiktok); if (!token) return res.status(401).json({ error: 'Hubungkan akun TikTok terlebih dahulu' }); const caption = String(req.body.caption || item.caption).trim(); db.prepare('UPDATE contents SET caption=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(caption, item.id); const result = await tiktok.publishPhotos(token.access_token, item.slides.map(x => `${config.publicBaseUrl}${x}`), `${caption}\n\n${item.hashtags.join(' ')}`); const publishId = result.data?.publish_id; db.prepare("UPDATE contents SET publish_id=?,publish_status='PROCESSING_UPLOAD',publish_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(publishId, item.id); res.json({ publishId, draft: true, status: 'PROCESSING_UPLOAD' }); } catch (e) { next(e); } });
  app.get('/status/:publishId', async (req, res, next) => { try { const token = await validToken(db, tiktok); if (!token) return res.status(401).json({ error: 'TikTok belum terhubung' }); const result = await tiktok.status(token.access_token, req.params.publishId); const s = result.data?.status || 'UNKNOWN'; db.prepare('UPDATE contents SET publish_status=?,publish_error=?,updated_at=CURRENT_TIMESTAMP WHERE publish_id=?').run(s, result.data?.fail_reason || null, req.params.publishId); res.json(result.data); } catch (e) { next(e); } });
  app.get('/history', (req, res) => res.json(db.prepare('SELECT * FROM contents ORDER BY id DESC').all().map(parseRecord)));
  app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: err.message || 'Kesalahan internal' }); });
  return app;
}
function parseRecord(row) { if (!row) return null; return { ...row, slides: JSON.parse(row.slides), hashtags: JSON.parse(row.hashtags) }; }
function record(db, id) { return parseRecord(db.prepare('SELECT * FROM contents WHERE id=?').get(id)); }
async function validToken(db, tiktok) { let token = db.prepare("SELECT * FROM oauth_tokens WHERE provider='tiktok'").get(); if (!token) return null; if (token.expires_at < Date.now() + 60000) { const next = await tiktok.refresh(token.refresh_token); db.prepare("UPDATE oauth_tokens SET access_token=?,refresh_token=?,expires_at=?,refresh_expires_at=?,updated_at=CURRENT_TIMESTAMP WHERE provider='tiktok'").run(next.access_token, next.refresh_token || token.refresh_token, Date.now() + next.expires_in * 1000, Date.now() + (next.refresh_expires_in || 0) * 1000); token = db.prepare("SELECT * FROM oauth_tokens WHERE provider='tiktok'").get(); } return token; }
module.exports = { createApp };
